// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ApiLoginState: Int {
  /// 登录中
  case logging = 0
  /// 已登录
  case logined = 1
  /// 未登录
  case logout = 2
}

/// Alexa 语音状态 (未启用)
enum ApiVoiceState: Int {
  /// 无状态
  case none = 0
  /// 准备
  case ready = 1
  /// 开始
  case starting = 2
  /// 结束
  case finished = 3
}

/// 国家及语言
enum ApiLanguageType: Int {
  /// 德语
  case german = 0
  /// 英语 澳大利亚
  case australia = 1
  /// 英语 加拿大
  case canadaEn = 2
  /// 英语 英国
  case unitedKingdom = 3
  /// 英语 印度
  case india = 4
  ///英语 美国
  case usa = 5
  /// 西班牙语 西班牙
  case spainEs = 6
  /// 西班牙语 墨西哥
  case mexico = 7
  /// 西班牙语 美国
  case spainUs = 8
  /// 法语 加拿大
  case frenchCanada = 9
  /// 法语 法国
  case frenchFrench = 10
  /// 印地语 印度
  case hindiIndia = 11
  /// 意大利语
  case italianItaly = 12
  /// 日语
  case japan = 13
  /// 葡萄牙语
  case portugal = 14
}

/// 健康数据类型
enum ApiGetValueType: Int {
  /// 当天步数
  case pedometer = 0
  /// 当天卡路里
  case calorie = 1
  /// 当天最近一次测量的心率
  case heartRate = 2
  /// 当天血氧
  case spO2 = 3
  /// 当天距离（米）
  case kilometer = 4
  /// 当天室内游泳距离（米）
  case swimmingDistance = 5
  /// 当天睡眠得分
  case sleepScore = 6
  /// 当天跑步次数
  case runningCount = 7
  /// 当天游泳次数
  case swimmingCount = 8
  /// 当天运动次数
  case dayWorkoutCount = 9
  /// 当周运动次数
  case weekWorkoutCount = 10
  /// 身体电量
  case bodyBattery = 11
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AlexaAuthDelegate {
  /// Alexa认证需要打开的url和userCode
  func callbackPairCode(userCode: String, verificationUri: String) throws
  /// 监听登录状态
  func loginStateChanged(state: ApiLoginState) throws
  /// 监听语音状态
  func voiceStateChanged(state: ApiVoiceState) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AlexaAuthDelegateSetup {
  /// The codec used by AlexaAuthDelegate.
  /// Sets up an instance of `AlexaAuthDelegate` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AlexaAuthDelegate?) {
    /// Alexa认证需要打开的url和userCode
    let callbackPairCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.callbackPairCode", binaryMessenger: binaryMessenger)
    if let api = api {
      callbackPairCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userCodeArg = args[0] as! String
        let verificationUriArg = args[1] as! String
        do {
          try api.callbackPairCode(userCode: userCodeArg, verificationUri: verificationUriArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      callbackPairCodeChannel.setMessageHandler(nil)
    }
    /// 监听登录状态
    let loginStateChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.loginStateChanged", binaryMessenger: binaryMessenger)
    if let api = api {
      loginStateChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = ApiLoginState(rawValue: args[0] as! Int)!
        do {
          try api.loginStateChanged(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loginStateChangedChannel.setMessageHandler(nil)
    }
    /// 监听语音状态
    let voiceStateChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.voiceStateChanged", binaryMessenger: binaryMessenger)
    if let api = api {
      voiceStateChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = ApiVoiceState(rawValue: args[0] as! Int)!
        do {
          try api.voiceStateChanged(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      voiceStateChangedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AlexaDataSource {
  /// 获取健康数据
  func getHealthValue(valueType: ApiGetValueType, completion: @escaping (Result<Int64, Error>) -> Void)
  /// 获取心率
  func getHrValue(dataType: Int64, timeType: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  /// 功能控制
  ///
  /// funType 0 关闭找手机功能
  func functionControl(funType: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AlexaDataSourceSetup {
  /// The codec used by AlexaDataSource.
  /// Sets up an instance of `AlexaDataSource` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AlexaDataSource?) {
    /// 获取健康数据
    let getHealthValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaDataSource.getHealthValue", binaryMessenger: binaryMessenger)
    if let api = api {
      getHealthValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueTypeArg = ApiGetValueType(rawValue: args[0] as! Int)!
        api.getHealthValue(valueType: valueTypeArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getHealthValueChannel.setMessageHandler(nil)
    }
    /// 获取心率
    let getHrValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaDataSource.getHrValue", binaryMessenger: binaryMessenger)
    if let api = api {
      getHrValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataTypeArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let timeTypeArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        api.getHrValue(dataType: dataTypeArg, timeType: timeTypeArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getHrValueChannel.setMessageHandler(nil)
    }
    /// 功能控制
    ///
    /// funType 0 关闭找手机功能
    let functionControlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.AlexaDataSource.functionControl", binaryMessenger: binaryMessenger)
    if let api = api {
      functionControlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let funTypeArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.functionControl(funType: funTypeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      functionControlChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class Alexa {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// 是否已登录
  func isLogin(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.isLogin", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 获取当前语言
  func currentLanguage(completion: @escaping (ApiLanguageType) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.currentLanguage", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = ApiLanguageType(rawValue: response as! Int)!
      completion(result)
    }
  }
  /// 注册alexa
  /// ```dart
  /// clientId Alexa后台生成的ID
  /// writeToFile 写log文件
  /// outputToConsole 打印到控制台
  /// logLevel 日志级别（该值只会在debug模式下有效）
  /// ```
  func registerAlexa(clientId clientIdArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.registerAlexa", binaryMessenger: binaryMessenger)
    channel.sendMessage([clientIdArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 网络变更需实时调用此方法(重要!!!)
  func onNetworkChanged(hasNetwork hasNetworkArg: Bool, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.onNetworkChanged", binaryMessenger: binaryMessenger)
    channel.sendMessage([hasNetworkArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 切换语言 默认英语
  func changeLanguage(type typeArg: ApiLanguageType, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.changeLanguage", binaryMessenger: binaryMessenger)
    channel.sendMessage([typeArg.rawValue] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// Alexa CBL授权
  /// ```dart
  /// productId 在alexa后台注册的产品ID
  /// func 回调Alexa认证需要打开的url和userCode
  /// 返回 0 成功，1 失败，2 超时
  /// ```
  func authorizeRequest(productId productIdArg: String, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.authorizeRequest", binaryMessenger: binaryMessenger)
    channel.sendMessage([productIdArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// 停止登录 (结束当前执行中的相关登录操作)
  func stopLogin(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.stopLogin", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  /// 退出登录
  func logout(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.logout", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  /// 是否支持语音测试
  func isSupportAudioTesting(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.isSupportAudioTesting", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 测试pcm上传 (内部使用)
  func testUploadPCM(pcmPath pcmPathArg: String, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.testUploadPCM", binaryMessenger: binaryMessenger)
    channel.sendMessage([pcmPathArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  func debugTest(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.debugTest", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func refreshToken(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Alexa.refreshToken", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
