// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class Bind {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// 绑定状态
  func isBinded(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.isBinded", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 是否在绑定中 (绑定中，切换设备将受到限制）
  func isBinding(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.isBinding", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 0 绑定失败 1绑定成功 2已经绑定 3需要授权码绑定 4拒绝绑定 5绑定错误设备 6授权码校验失败
  /// 7取消绑定 8绑定失败（获取功能表失败) 9绑定失败（获取设备信息失败)
  /// 10绑定超时（支持该功能的设备专用）
  /// 11新账户绑定，用户确定删除设备数据（支持该功能的设备专用）
  /// 12新账户绑定，用户不删除设备数据，绑定失败（支持该功能的设备专用）
  /// 13新账户绑定，用户不选择，设备超时（支持该功能的设备专用）
  /// 14设备同意配对(绑定)请求，等待APP下发配对结果（支持该功能的设备专用）
  func bind(osVersion osVersionArg: Int64, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.bind", binaryMessenger: binaryMessenger)
    channel.sendMessage([osVersionArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  func cancelBind(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.cancelBind", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  /// APP下发绑定结果(仅限需要app确认绑定结果的设备使用)
  /// ```
  /// 注：当startBind(...) 返回BindStatus.needAuthByApp 时，APP需要发送
  /// CmdEvtType.sendBindResult指令，在调用成功后，再调用appMarkBindResult方法
  /// ```
  func appMarkBindResult(success successArg: Bool, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.appMarkBindResult", binaryMessenger: binaryMessenger)
    channel.sendMessage([successArg] as [Any?]) { _ in
      completion()
    }
  }
  func unbind(macAddress macAddressArg: String, isForceRemove isForceRemoveArg: Bool, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.unbind", binaryMessenger: binaryMessenger)
    channel.sendMessage([macAddressArg, isForceRemoveArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  func setAuthCode(code codeArg: String, osVersion osVersionArg: Int64, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Bind.setAuthCode", binaryMessenger: binaryMessenger)
    channel.sendMessage([codeArg, osVersionArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
}
