// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceLogDelegate {
  /// 监听日志获取状态
  func listenLogStatus(status: Bool) throws
  /// 监听日志目录地址
  func listenLogDirPath(dirPath: String) throws
  /// 日志整体进度 0-100
  func callbackLogProgress(progress: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceLogDelegateSetup {
  /// The codec used by DeviceLogDelegate.
  /// Sets up an instance of `DeviceLogDelegate` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceLogDelegate?) {
    /// 监听日志获取状态
    let listenLogStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogStatus", binaryMessenger: binaryMessenger)
    if let api = api {
      listenLogStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let statusArg = args[0] as! Bool
        do {
          try api.listenLogStatus(status: statusArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listenLogStatusChannel.setMessageHandler(nil)
    }
    /// 监听日志目录地址
    let listenLogDirPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogDirPath", binaryMessenger: binaryMessenger)
    if let api = api {
      listenLogDirPathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dirPathArg = args[0] as! String
        do {
          try api.listenLogDirPath(dirPath: dirPathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listenLogDirPathChannel.setMessageHandler(nil)
    }
    /// 日志整体进度 0-100
    let callbackLogProgressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.callbackLogProgress", binaryMessenger: binaryMessenger)
    if let api = api {
      callbackLogProgressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let progressArg = args[0] as! Double
        do {
          try api.callbackLogProgress(progress: progressArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      callbackLogProgressChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class DeviceLog {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// 判断日志状态
  func getLogIng(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLog.getLogIng", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 获取所有日志目录地址，每个日志目录下存放以时间戳命名的文件
  /// flash 日志目录 =>  Flash
  /// 电池日志目录 => Battery
  /// 过热日志目录 => Heat
  /// 旧的重启日志目录 => Reboot
  func logDirPath(completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLog.logDirPath", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! String
      completion(result)
    }
  }
  /// 开始获取日志
  /// type 1: 旧的重启日志 2: 通用日志 3: 复位日志
  /// 4: 硬件日志 5: 算法日志 6: 新重启日志 7:电池日志 8: 过热日志
  func startGet(types typesArg: [Int64], timeOut timeOutArg: Int64, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLog.startGet", binaryMessenger: binaryMessenger)
    channel.sendMessage([typesArg, timeOutArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 取消
  func cancel(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.DeviceLog.cancel", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
