// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct ApiPhotoDialConfig {
  /// 背景图路径
  var bgPicPath: String? = nil
  /// 预览图路径
  var previewPicPath: String? = nil
  /// 时间颜色
  var timeColor: Int64? = nil
  /// 功能颜色
  var functionColor: Int64? = nil
  /// 位置
  var position: Int64? = nil
  /// 要展示的功能，不支持功能则不传 [PhotoDialConstants.WidgetFunction]
  var showFunction: Int64? = nil

  static func fromList(_ list: [Any?]) -> ApiPhotoDialConfig? {
    let bgPicPath: String? = nilOrValue(list[0])
    let previewPicPath: String? = nilOrValue(list[1])
    let timeColor: Int64? = isNullish(list[2]) ? nil : (list[2] is Int64? ? list[2] as! Int64? : Int64(list[2] as! Int32))
    let functionColor: Int64? = isNullish(list[3]) ? nil : (list[3] is Int64? ? list[3] as! Int64? : Int64(list[3] as! Int32))
    let position: Int64? = isNullish(list[4]) ? nil : (list[4] is Int64? ? list[4] as! Int64? : Int64(list[4] as! Int32))
    let showFunction: Int64? = isNullish(list[5]) ? nil : (list[5] is Int64? ? list[5] as! Int64? : Int64(list[5] as! Int32))

    return ApiPhotoDialConfig(
      bgPicPath: bgPicPath,
      previewPicPath: previewPicPath,
      timeColor: timeColor,
      functionColor: functionColor,
      position: position,
      showFunction: showFunction
    )
  }
  func toList() -> [Any?] {
    return [
      bgPicPath,
      previewPicPath,
      timeColor,
      functionColor,
      position,
      showFunction,
    ]
  }
}
private class ApiPhotoDialDelegateCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return ApiPhotoDialConfig.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ApiPhotoDialDelegateCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ApiPhotoDialConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiPhotoDialDelegateCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiPhotoDialDelegateCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiPhotoDialDelegateCodecWriter(data: data)
  }
}

class ApiPhotoDialDelegateCodec: FlutterStandardMessageCodec {
  static let shared = ApiPhotoDialDelegateCodec(readerWriter: ApiPhotoDialDelegateCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ApiPhotoDialDelegate {
  func onSuccess() throws
  func onFailed(errCode: Int64, errMsg: Any) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ApiPhotoDialDelegateSetup {
  /// The codec used by ApiPhotoDialDelegate.
  static var codec: FlutterStandardMessageCodec { ApiPhotoDialDelegateCodec.shared }
  /// Sets up an instance of `ApiPhotoDialDelegate` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ApiPhotoDialDelegate?) {
    let onSuccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiPhotoDialDelegate.onSuccess", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onSuccessChannel.setMessageHandler { _, reply in
        do {
          try api.onSuccess()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onSuccessChannel.setMessageHandler(nil)
    }
    let onFailedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiPhotoDialDelegate.onFailed", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onFailedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let errCodeArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let errMsgArg = args[1]!
        do {
          try api.onFailed(errCode: errCodeArg, errMsg: errMsgArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onFailedChannel.setMessageHandler(nil)
    }
  }
}
private class ApiPhotoDialCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return ApiPhotoDialConfig.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ApiPhotoDialCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ApiPhotoDialConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiPhotoDialCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiPhotoDialCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiPhotoDialCodecWriter(data: data)
  }
}

class ApiPhotoDialCodec: FlutterStandardMessageCodec {
  static let shared = ApiPhotoDialCodec(readerWriter: ApiPhotoDialCodecReaderWriter())
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class ApiPhotoDial {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return ApiPhotoDialCodec.shared
  }
  /// 异步解析表盘配置包
  /// [dialPackagePath] 表盘配置包路径
  /// 返回表盘支持的一些配置项，如颜色、位置（坐标），组件功能json
  func prepare(dialPackagePath dialPackagePathArg: String, completion: @escaping (String?) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiPhotoDial.prepare", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dialPackagePathArg] as [Any?]) { response in
      let result: String? = nilOrValue(response)
      completion(result)
    }
  }
  /// 安装表盘
  /// [config] 表盘配置
  func install(config configArg: ApiPhotoDialConfig, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiPhotoDial.install", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([configArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 取消安装
  func cancelInstall(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiPhotoDial.cancelInstall", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
