// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// EPO升级状态
enum ApiEpoUpgradeStatus: Int {
  /// 空闲
  case idle = 0
  /// 准备更新
  case ready = 1
  /// 下载中
  case downing = 2
  /// 制作中
  case making = 3
  /// 发送中
  case sending = 4
  /// 安装中
  case installing = 5
  /// 成功
  case success = 6
  /// 失败
  case failure = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct ApiOTAGpsInfo {
  ///	晶振偏移
  var tcxoOffset: Int64? = nil
  /// 经度
  var longitude: Double? = nil
  /// 纬度
  var latitude: Double? = nil
  /// 海拔高度
  var altitude: Double? = nil

  static func fromList(_ list: [Any?]) -> ApiOTAGpsInfo? {
    let tcxoOffset: Int64? = isNullish(list[0]) ? nil : (list[0] is Int64? ? list[0] as! Int64? : Int64(list[0] as! Int32))
    let longitude: Double? = nilOrValue(list[1])
    let latitude: Double? = nilOrValue(list[2])
    let altitude: Double? = nilOrValue(list[3])

    return ApiOTAGpsInfo(
      tcxoOffset: tcxoOffset,
      longitude: longitude,
      latitude: latitude,
      altitude: altitude
    )
  }
  func toList() -> [Any?] {
    return [
      tcxoOffset,
      longitude,
      latitude,
      altitude,
    ]
  }
}

private class ApiEpoManagerDelegateCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return ApiOTAGpsInfo.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ApiEpoManagerDelegateCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ApiOTAGpsInfo {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiEpoManagerDelegateCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiEpoManagerDelegateCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiEpoManagerDelegateCodecWriter(data: data)
  }
}

class ApiEpoManagerDelegateCodec: FlutterStandardMessageCodec {
  static let shared = ApiEpoManagerDelegateCodec(readerWriter: ApiEpoManagerDelegateCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ApiEpoManagerDelegate {
  /// 升级状态
  func onEpoStatusChanged(status: ApiEpoUpgradeStatus) throws
  /// 下载进度
  func onEpoDownloadProgress(progress: Double) throws
  /// 发送进度
  func onEpoSendProgress(progress: Double) throws
  /// 升级完成（成功或失败）
  /// errorCode：0 升级成功，非0升级失败
  func onEpoComplete(errorCode: Int64) throws
  /// app提供当前手机gps信息，用于设备快速定位
  func onGetGps(completion: @escaping (Result<ApiOTAGpsInfo?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ApiEpoManagerDelegateSetup {
  /// The codec used by ApiEpoManagerDelegate.
  static var codec: FlutterStandardMessageCodec { ApiEpoManagerDelegateCodec.shared }
  /// Sets up an instance of `ApiEpoManagerDelegate` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ApiEpoManagerDelegate?) {
    /// 升级状态
    let onEpoStatusChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoStatusChanged", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onEpoStatusChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let statusArg = ApiEpoUpgradeStatus(rawValue: args[0] as! Int)!
        do {
          try api.onEpoStatusChanged(status: statusArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onEpoStatusChangedChannel.setMessageHandler(nil)
    }
    /// 下载进度
    let onEpoDownloadProgressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoDownloadProgress", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onEpoDownloadProgressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let progressArg = args[0] as! Double
        do {
          try api.onEpoDownloadProgress(progress: progressArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onEpoDownloadProgressChannel.setMessageHandler(nil)
    }
    /// 发送进度
    let onEpoSendProgressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoSendProgress", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onEpoSendProgressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let progressArg = args[0] as! Double
        do {
          try api.onEpoSendProgress(progress: progressArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onEpoSendProgressChannel.setMessageHandler(nil)
    }
    /// 升级完成（成功或失败）
    /// errorCode：0 升级成功，非0升级失败
    let onEpoCompleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoComplete", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onEpoCompleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let errorCodeArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.onEpoComplete(errorCode: errorCodeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onEpoCompleteChannel.setMessageHandler(nil)
    }
    /// app提供当前手机gps信息，用于设备快速定位
    let onGetGpsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onGetGps", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onGetGpsChannel.setMessageHandler { _, reply in
        api.onGetGps() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onGetGpsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class ApiEPOManager {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// 启用自动epo升级，默认为 关
  ///
  /// ```dart
  /// 触发条件：
  /// 1、每次快速配置完成后倒计时1分钟；
  /// 2、数据同步完成后立即执行；
  /// ```
  func enableAutoUpgrade(completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.enableAutoUpgrade", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 启用自动epo升级，默认为 关
  ///
  /// ```dart
  /// 触发条件：
  /// 1、每次快速配置完成后倒计时1分钟；
  /// 2、数据同步完成后立即执行；
  /// ```
  func setEnableAutoUpgrade(value valueArg: Bool, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.setEnableAutoUpgrade", binaryMessenger: binaryMessenger)
    channel.sendMessage([valueArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 获取最后一次更新的时间戳，单位：秒
  ///
  /// 无记录则返回0
  func lastUpdateTimestamp(completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.lastUpdateTimestamp", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// 是否需要更新
  func shouldUpdateForEPO(isForce isForceArg: Bool, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.shouldUpdateForEPO", binaryMessenger: binaryMessenger)
    channel.sendMessage([isForceArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 启动升级任务
  ///
  /// ```dart
  /// isForce 是否强制更新
  /// retryCount 重试次数，默认0次
  /// ```
  func willStartInstall(isForce isForceArg: Bool, retryCount retryCountArg: Int64, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.willStartInstall", binaryMessenger: binaryMessenger)
    channel.sendMessage([isForceArg, retryCountArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 停止升级任务
  ///
  /// 注：只支持下载中和发送中的任务，不支持正在升级的任务
  func stop(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.ApiEPOManager.stop", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
