// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FuncTableDelegate {
  /// 功能表变更通知
  func listenFuncTableChanged(funcTableJson: String) throws
  /// 绑定时获取的功能表通知(绑定专用)
  func listenFuncTableOnBind(funcTableJson: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FuncTableDelegateSetup {
  /// The codec used by FuncTableDelegate.
  /// Sets up an instance of `FuncTableDelegate` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FuncTableDelegate?) {
    /// 功能表变更通知
    let listenFuncTableChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableChanged", binaryMessenger: binaryMessenger)
    if let api = api {
      listenFuncTableChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let funcTableJsonArg = args[0] as! String
        do {
          try api.listenFuncTableChanged(funcTableJson: funcTableJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listenFuncTableChangedChannel.setMessageHandler(nil)
    }
    /// 绑定时获取的功能表通知(绑定专用)
    let listenFuncTableOnBindChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableOnBind", binaryMessenger: binaryMessenger)
    if let api = api {
      listenFuncTableOnBindChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let funcTableJsonArg = args[0] as! String
        do {
          try api.listenFuncTableOnBind(funcTableJson: funcTableJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listenFuncTableOnBindChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FuncTable {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// 加载指定设备功能表 返回json
  func loadFuncTableByDisk(macAddress macAddressArg: String, completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.FuncTable.loadFuncTableByDisk", binaryMessenger: binaryMessenger)
    channel.sendMessage([macAddressArg] as [Any?]) { response in
      let result = response as! String
      completion(result)
    }
  }
  /// 导出功能表 返回json文件绝对路径
  func exportFuncTableFile(macAddress macAddressArg: String, completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.FuncTable.exportFuncTableFile", binaryMessenger: binaryMessenger)
    channel.sendMessage([macAddressArg] as [Any?]) { response in
      let result = response as! String
      completion(result)
    }
  }
}
