// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 设备信息
///
/// Generated class from Pigeon that represents data sent in messages.
struct VersionInfo {
  /// 协议库版本号
  var verMain: String? = nil
  /// c库版本
  var verClib: String? = nil
  /// Alexa库版本
  var verAlexa: String? = nil

  static func fromList(_ list: [Any?]) -> VersionInfo? {
    let verMain: String? = nilOrValue(list[0])
    let verClib: String? = nilOrValue(list[1])
    let verAlexa: String? = nilOrValue(list[2])

    return VersionInfo(
      verMain: verMain,
      verClib: verClib,
      verAlexa: verAlexa
    )
  }
  func toList() -> [Any?] {
    return [
      verMain,
      verClib,
      verAlexa,
    ]
  }
}
private class ToolCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return VersionInfo.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ToolCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VersionInfo {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ToolCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ToolCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ToolCodecWriter(data: data)
  }
}

class ToolCodec: FlutterStandardMessageCodec {
  static let shared = ToolCodec(readerWriter: ToolCodecReaderWriter())
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class Tool {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return ToolCodec.shared
  }
  /// 图片转换格式 png->bmp
  /// ```dart
  /// inPath 用于转换的png路径(包含文件名及后缀)
  /// outPath 转换完的bmp路径(包含文件名及后缀)
  /// format 转换成bmp的文件格式
  /// 返回 0 成功
  /// ```dart
  func png2Bmp(inPath inPathArg: String, outPath outPathArg: String, format formatArg: Int64, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.png2Bmp", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([inPathArg, outPathArg, formatArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// 压缩png图片质量
  /// ```dart
  /// inputFilePath   输入文件路径
  /// outputFilePath 输出文件路径
  /// 返回 0 成功
  /// ```
  func compressToPNG(inputFilePath inputFilePathArg: String, outputFilePath outputFilePathArg: String, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.compressToPNG", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([inputFilePathArg, outputFilePathArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// 创建EPO.DAT文件
  /// ```dart
  /// dirPath 存放要制作epo文件的目录
  /// epoFilePath 制作的epo文件存放路径
  /// ```
  func makeEpoFile(dirPath dirPathArg: String, epoFilePath epoFilePathArg: String, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.makeEpoFile", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dirPathArg, epoFilePathArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// 设置流数据是否输出开关
  ///
  /// iswrite 控制写入流数据开关公开 0不写入 1写入 默认不写入流数据
  /// 0 成功
  func setWriteStreamByte(isWrite isWriteArg: Bool, completion: @escaping (Bool) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.setWriteStreamByte", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isWriteArg] as [Any?]) { response in
      let result = response as! Bool
      completion(result)
    }
  }
  /// gsp运动后优化轨迹,根据运动类型初始化速度阈值，若输入其他运动类型，会导致无运动轨迹
  ///
  /// [motionTypeIn] 运动类型：
  /// ```dart
  /// 1、户外走路 = 52, 走路 = 1, 徒步 = 4, 运动类型设为0
  /// 2、户外跑步 = 48, 跑步 = 2, 运动类型设为1
  /// 3、户外骑行 = 50, 骑行 = 3, 运动型性设为2
  /// ```dart
  func gpsInitType(motionTypeIn motionTypeInArg: Int64, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.gpsInitType", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([motionTypeInArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// gps数据实时处理入口,需要对输出的数据进行判断，若纬度为-180则为错误值，不应该输出
  /// ```dart
  /// { lon,经度,数据类型double
  ///  lat,纬度,数据类型double
  ///  timestamp,时间戳,数据类型int
  ///  accuracy,定位精度,数据类型double
  ///  gpsaccuracystatus,定位等级，0 = 定位未知, 1 = 定位好, 2 = 定位差,数据类型int }
  /// ```dart
  func gpsAlgProcessRealtime(json jsonArg: String, completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.gpsAlgProcessRealtime", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([jsonArg] as [Any?]) { response in
      let result = response as! String
      completion(result)
    }
  }
  /// 平滑数据，结果保存在数组lat和lon中
  /// ```dart
  /// {lat,纬度数组,长度为len,数据类型double
  ///  lon,经度数组,长度为len,数据类型double len,数据长度}
  /// ```dart
  func gpsSmoothData(json jsonArg: String, completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.gpsSmoothData", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([jsonArg] as [Any?]) { response in
      let result = response as! String
      completion(result)
    }
  }
  ///  v2发送来电提醒以及来电电话号码和来电联系人(部分设备实现)
  /// ```dart
  /// contactText：联系人名称
  /// phoneNumber：号码
  /// 返回 0 成功
  /// ```
  func setV2CallEvt(contactText contactTextArg: String, phoneNumber phoneNumberArg: String, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.setV2CallEvt", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([contactTextArg, phoneNumberArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// v2发送信息提醒以及信息内容(部分设备实现)
  ///
  /// ```dart
  /// type 信息类型
  /// contactText 通知内容
  /// phoneNumber 号码
  /// dataText 消息内容
  /// 返回 0 成功
  /// ```
  func setV2NoticeEvt(type typeArg: Int64, contactText contactTextArg: String, phoneNumber phoneNumberArg: String, dataText dataTextArg: String, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.setV2NoticeEvt", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([typeArg, contactTextArg, phoneNumberArg, dataTextArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// v2发送来电提醒状态为来电已接, 告诉设备停止提醒用户(部分设备实现)
  ///
  /// 返回 0 成功
  func stopV2CallEvt(completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.stopV2CallEvt", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// v2发送来电提醒状态为来电已拒, 告诉设备停止提醒用户(部分设备实现)
  ///
  /// 返回 0 成功
  func missedV2MissedCallEvt(completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.missedV2MissedCallEvt", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
  /// 记录原生层log
  func logNative(msg msgArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.logNative", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([msgArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 获取版本号
  func getSDKVersionInfo(completion: @escaping (VersionInfo?) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.getSDKVersionInfo", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      let result: VersionInfo? = nilOrValue(response)
      completion(result)
    }
  }
  /// 获取mp3音频采样率
  /// ```dart
  /// mp3FilePath 输入带路径MP3文件名
  /// return int 输入的MP3文件的采样率如：441000， 异常返回-1
  /// ```
  func mp3SamplingRate(mp3FilePath mp3FilePathArg: String, completion: @escaping (Int64) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protocol_channel.Tool.mp3SamplingRate", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([mp3FilePathArg] as [Any?]) { response in
      let result = response is Int64 ? response as! Int64 : Int64(response as! Int32)
      completion(result)
    }
  }
}
