// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'function_table_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FunctionTableModel _$FunctionTableModelFromJson(Map<String, dynamic> json) =>
    FunctionTableModel(
      airohaGpsChip: json['Airoha_gps_chip'] as bool?,
      BindAuth: json['BindAuth'] as bool?,
      BindCodeAuth: json['BindCodeAuth'] as bool?,
      BloodPressure: json['BloodPressure'] as bool?,
      FiveHRInterval: json['FiveHRInterval'] as bool?,
      Gmail: json['Gmail'] as bool?,
      HIDPhoto: json['HIDPhoto'] as bool?,
      HIIT: json['HIIT'] as bool?,
      KakaoTalk: json['KakaoTalk'] as bool?,
      Line: json['Line'] as bool?,
      Outlook: json['Outlook'] as bool?,
      Snapchat: json['Snapchat'] as bool?,
      Telegram: json['Telegram'] as bool?,
      v2SupportGetHeartRateMode:
          json['V2_support_get_heart_rate_mode'] as bool?,
      v2SupportGetSwitchStatusAppend:
          json['V2_support_get_switch_status_append'] as bool?,
      v2SupportSetGetTimeGoalType:
          json['V2_support_set_get_time_goal_type'] as bool?,
      v3VeryfitNotSupportPhotoWallpaper:
          json['V3_Veryfit_not_support_photo_wallpaper'] as bool?,
      v3AlexaReminderAddSec: json['V3_alexa_reminder_add_sec'] as bool?,
      v3AlexaSetEasyOperate: json['V3_alexa_set_easy_operate'] as bool?,
      v3AlexaSetGetAlexaAlarm: json['V3_alexa_set_get_alexa_alarm'] as bool?,
      v3AlexaSetJumpSportUi: json['V3_alexa_set_jump_sport_ui'] as bool?,
      v3AlexaSetJumpUi: json['V3_alexa_set_jump_ui'] as bool?,
      v3AlexaSetSetOnOffType: json['V3_alexa_set_set_on_off_type'] as bool?,
      v3AlexaSetWeather: json['V3_alexa_set_weather'] as bool?,
      v3AlexaTimeNew: json['V3_alexa_time_new'] as bool?,
      v3AutoActivitySwitch: json['V3_auto_activity_switch'] as bool?,
      v3AutomaticSyncV3HealthData:
          json['V3_automatic_sync_v3_health_data'] as bool?,
      v3DevSupportPairEachConnect:
          json['V3_dev_support_pair_each_connect'] as bool?,
      v3DrinkWaterAddNotifyFlag:
          json['V3_drink_water_add_notify_flag'] as bool?,
      v3GetBatteryLog: json['V3_get_battery_log'] as bool?,
      v3GetCalorieDistanceGoal: json['V3_get_calorie_distance_goal'] as bool?,
      v3GetDevLogState: json['V3_get_dev_log_state'] as bool?,
      v3GetMenuList: json['V3_get_menu_list'] as bool?,
      v3GetWalkReminder: json['V3_get_walk_reminder'] as bool?,
      v3GetWatchListNew: json['V3_get_watch_list_new'] as bool?,
      v3HealthSyncNoise: json['V3_health_sync_noise'] as bool?,
      v3HealthSyncTemperature: json['V3_health_sync_temperature'] as bool?,
      v3MenstrualAddNotifyFlag: json['V3_menstrual_add_notify_flag'] as bool?,
      v3MusicControl02AddSingerName:
          json['V3_music_control_02_add_singer_name'] as bool?,
      v3PressureAddNotifyFlagAndMode:
          json['V3_pressure_add_notify_flag_and_mode'] as bool?,
      v3ScheduleReminder: json['V3_schedule_reminder'] as bool?,
      v3Set100SportSort: json['V3_set_100_sport_sort'] as bool?,
      v3Set20BaseSportParamSort:
          json['V3_set_20_base_sport_param_sort'] as bool?,
      v3SetMainUiSort: json['V3_set_main_ui_sort'] as bool?,
      v3SetMidHighTimeGoal: json['V3_set_mid_high_time_goal'] as bool?,
      v3SetSharkingGrade: json['V3_set_sharking_grade'] as bool?,
      v3SetWalkReminderGoalTime:
          json['V3_set_walk_reminder_goal_time'] as bool?,
      v3SetWallpaperDial: json['V3_set_wallpaper_dial'] as bool?,
      v3SetWatchDialSort: json['V3_set_watch_dial_sort'] as bool?,
      v3Spo2AddNotifyFlag: json['V3_spo2_add_notify_flag'] as bool?,
      v3Support189email: json['V3_support_189email'] as bool?,
      v3Support99taxi: json['V3_support_99taxi'] as bool?,
      v3SupportAliexpress: json['V3_support_Aliexpress'] as bool?,
      v3SupportAmericanas: json['V3_support_Americanas'] as bool?,
      v3SupportEnjoei: json['V3_support_Enjoei'] as bool?,
      v3SupportExchangeemail: json['V3_support_Exchangeemail'] as bool?,
      v3SupportGoogleMeet: json['V3_support_Google_meet'] as bool?,
      v3SupportInstantemail: json['V3_support_Instantemail'] as bool?,
      v3SupportMagalu: json['V3_support_Magalu'] as bool?,
      v3SupportMercadoLivre: json['V3_support_Mercado_livre'] as bool?,
      v3SupportMormaiiSmartwatch:
          json['V3_support_Mormaii_Smartwatch'] as bool?,
      v3SupportMotoemail: json['V3_support_Motoemail'] as bool?,
      v3SupportOla: json['V3_support_Ola'] as bool?,
      v3SupportRappi: json['V3_support_Rappi'] as bool?,
      v3SupportShopee: json['V3_support_Shopee'] as bool?,
      v3SupportTeams: json['V3_support_Teams'] as bool?,
      v3SupportTechnosConnect: json['V3_support_Technos_Connect'] as bool?,
      v3SupportUber: json['V3_support_Uber'] as bool?,
      v3SupportUberEats: json['V3_support_Uber_Eats'] as bool?,
      v3SupportWhatsappBusiness: json['V3_support_WhatsApp_Business'] as bool?,
      v3SupportYtmusic: json['V3_support_YTmusic'] as bool?,
      v3SupportYahoo: json['V3_support_Yahoo'] as bool?,
      v3SupportAlibabaEmail: json['V3_support_alibaba_email'] as bool?,
      v3SupportAppSendVoiceToBle:
          json['V3_support_app_send_voice_to_ble'] as bool?,
      v3SupportAsuseemail: json['V3_support_asuseemail'] as bool?,
      v3SupportBlueemail: json['V3_support_blueemail'] as bool?,
      v3SupportBpCalibration: json['V3_support_bp_calibration'] as bool?,
      v3SupportCalendario: json['V3_support_calendario'] as bool?,
      v3SupportCalorieUnit: json['V3_support_calorie_unit'] as bool?,
      v3SupportCyclingUnit: json['V3_support_cycling_unit'] as bool?,
      v3SupportDataTranContinue: json['V3_support_data_tran_continue'] as bool?,
      v3SupportDokidokemail: json['V3_support_dokidokemail'] as bool?,
      v3SupportGeneral: json['V3_support_general'] as bool?,
      v3SupportGetActivitySwitch:
          json['V3_support_get_activity_switch'] as bool?,
      v3SupportGetAlexaDefaultLanguage:
          json['V3_support_get_alexa_default_language'] as bool?,
      v3SupportGetHealthSwitchState:
          json['V3_support_get_health_switch_state'] as bool?,
      v3SupportGetMainSportGoal:
          json['V3_support_get_main_sport_goal'] as bool?,
      v3SupportGooglegmail: json['V3_support_googleGmail'] as bool?,
      v3SupportHrv: json['V3_support_hrv'] as bool?,
      v3SupportHtcemail: json['V3_support_htcemail'] as bool?,
      v3SupportInboxemail: json['V3_support_inboxemail'] as bool?,
      v3SupportLfood: json['V3_support_lfood'] as bool?,
      v3SupportMailruemail: json['V3_support_mailruemail'] as bool?,
      v3SupportMattersRemind: json['V3_support_matters_remind'] as bool?,
      v3SupportMicrosoft: json['V3_support_microsoft'] as bool?,
      v3SupportMissedCalls: json['V3_support_missed_calls'] as bool?,
      v3SupportMobiemail: json['V3_support_mobiemail'] as bool?,
      v3SupportMyemail: json['V3_support_myemail'] as bool?,
      v3SupportNeteasemail: json['V3_support_neteasemail'] as bool?,
      v3SupportNhnemail: json['V3_support_nhnemail'] as bool?,
      v3SupportNiosefit: json['V3_support_niosefit'] as bool?,
      v3SupportOutlookemail: json['V3_support_outlookemail'] as bool?,
      v3SupportQqemail: json['V3_support_qqemail'] as bool?,
      v3SupportScientificSleep: json['V3_support_scientific_sleep'] as bool?,
      v3SupportSetScientificSleepSwitch:
          json['V3_support_set_scientific_sleep_switch'] as bool?,
      v3SupportSetSmartHeartRate:
          json['V3_support_set_smart_heart_rate'] as bool?,
      v3SupportSetSpo2AllDayOnOff:
          json['V3_support_set_spo2_all_day_on_off'] as bool?,
      v3SupportSetSpo2LowValueRemind:
          json['V3_support_set_spo2_low_value_remind'] as bool?,
      v3SupportSetTemperatureSwitch:
          json['V3_support_set_temperature_switch'] as bool?,
      v3SupportSetV3MusicName: json['V3_support_set_v3_music_name'] as bool?,
      v3SupportSetV3NotifyAddAppName:
          json['V3_support_set_v3_notify_add_app_name'] as bool?,
      v3SupportSetV3Weather: json['V3_support_set_v3_weather'] as bool?,
      v3SupportSetV3WorldTime: json['V3_support_set_v3_world_time'] as bool?,
      v3SupportSetWeatherSunTime:
          json['V3_support_set_weather_sun_time'] as bool?,
      v3SupportShowDetectionTime:
          json['V3_support_show_detection_time'] as bool?,
      v3SupportSwimPoolUnit: json['V3_support_swim_pool_unit'] as bool?,
      v3SupportSwimmingDataExhibit:
          json['V3_support_swimming_data_exhibit'] as bool?,
      v3SupportSyncContact: json['V3_support_sync_contact'] as bool?,
      v3SupportSyncOverHighLowHeartData:
          json['V3_support_sync_over_high_low_heart_data'] as bool?,
      v3SupportTrtfbluemail: json['V3_support_trtfbluemail'] as bool?,
      v3SupportV3BleMusic: json['V3_support_v3_ble_music'] as bool?,
      v3SupportV3ExchangeDataReplyAddRealTimeSpeedPace:
          json['V3_support_v3_exchange_data_reply_add_real_time_speed_pace']
              as bool?,
      v3SupportV3GetSportSortField:
          json['V3_support_v3_get_sport_sort_field'] as bool?,
      v3SupportV3LongCityName: json['V3_support_v3_long_city_name'] as bool?,
      v3SupportV3NotifyIconAdaptive:
          json['V3_support_v3_notify_icon_adaptive'] as bool?,
      v3SupportVeryfit: json['V3_support_veryfit'] as bool?,
      v3SupportWalkingRunningUnit:
          json['V3_support_walking_running_unit'] as bool?,
      v3SupportWatchCapacitySizeDisplay:
          json['V3_support_watch_capacity_size_display'] as bool?,
      v3SupportWatchPhotoPositionMove:
          json['V3_support_watch_photo_position_move'] as bool?,
      v3SupportWearFlag: json['V3_support_wear_flag'] as bool?,
      v3SupportYahooemail: json['V3_support_yahooemail'] as bool?,
      v3SupportZohoemail: json['V3_support_zohoemail'] as bool?,
      v3SyncV3ActivityAddParam: json['V3_sync_v3_activity_add_param'] as bool?,
      v3V202EbFirmwareBtVersion01Create:
          json['V3_v2_02_EB_firmware_bt_version_01_create'] as bool?,
      v3V2MenstrualRemind02AddPregnancy:
          json['V3_v2_menstrual_remind_02_add_pregnancy'] as bool?,
      v3V3333dHistoricalMenstruation01Create:
          json['V3_v3_33_3D_historical_menstruation_01_create'] as bool?,
      v3WalkReminderAddNotifyFlag:
          json['V3_walk_reminder_add_notify_flag'] as bool?,
      v3WatchDailSetAddSize: json['V3_watch_dail_set_add_size'] as bool?,
      VKontakte: json['VKontakte'] as bool?,
      Viber: json['Viber'] as bool?,
      WatchDial: json['WatchDial'] as bool?,
      activitySwitch: json['activity_switch'] as bool?,
      aerobicsBodybuildingExercise:
          json['aerobics_bodybuilding_exercise'] as bool?,
      agpsOffline: json['agps_offline'] as bool?,
      agpsOnline: json['agps_online'] as bool?,
      alarmBath: json['alarmBath'] as bool?,
      alarmBrushTeeth: json['alarmBrushTeeth'] as bool?,
      alarmClock: json['alarmClock'] as bool?,
      alarmCount: json['alarmCount'] as int?,
      alarmCourse: json['alarmCourse'] as bool?,
      alarmCustom: json['alarmCustom'] as bool?,
      alarmDating: json['alarmDating'] as bool?,
      alarmDinner: json['alarmDinner'] as bool?,
      alarmLearn: json['alarmLearn'] as bool?,
      alarmMedicine: json['alarmMedicine'] as bool?,
      alarmMetting: json['alarmMetting'] as bool?,
      alarmParty: json['alarmParty'] as bool?,
      alarmPlayTime: json['alarmPlayTime'] as bool?,
      alarmRest: json['alarmRest'] as bool?,
      alarmSleep: json['alarmSleep'] as bool?,
      alarmSport: json['alarmSport'] as bool?,
      alarmWakeUp: json['alarmWakeUp'] as bool?,
      allAppNotice: json['allAppNotice'] as bool?,
      ancs: json['ancs'] as bool?,
      antilost: json['antilost'] as bool?,
      autoActivityEndSwitchNotDisplay:
          json['auto_activity_end_switch_not_display'] as bool?,
      autoActivityPauseSwitchNotDisplay:
          json['auto_activity_pause_switch_not_display'] as bool?,
      autoActivitySetGetUseNewStructExchange:
          json['auto_activity_set_get_use_new_struct_exchange'] as bool?,
      autoActivitySwitchAddBicycle:
          json['auto_activity_switch_add_bicycle'] as bool?,
      autoActivitySwitchAddSmartRope:
          json['auto_activity_switch_add_smart_rope'] as bool?,
      battlingRope: json['battling_rope'] as bool?,
      beachTennis: json['beach_tennis'] as bool?,
      bilateralAntiLost: json['bilateralAntiLost'] as bool?,
      bleControlMusic: json['bleControlMusic'] as bool?,
      bleControlTakePhoto: json['bleControlTakePhoto'] as bool?,
      breatheTrain: json['breathe_train'] as bool?,
      calendar: json['calendar'] as bool?,
      calling: json['calling'] as bool?,
      callingContact: json['callingContact'] as bool?,
      callingNum: json['callingNum'] as bool?,
      chooseOtherOtaMode: json['choose_other_ota_mode'] as bool?,
      cricket: json['cricket'] as bool?,
      dataTranOverWaitBle: json['data_tran_over_wait_ble'] as bool?,
      defaultConfig: json['defaultConfig'] as bool?,
      defaultSportType: json['defaultSportType'] as bool?,
      deviceUpdate: json['deviceUpdate'] as bool?,
      deviceControlFastModeAlone:
          json['device_control_fast_mode_alone'] as bool?,
      displayMode: json['displayMode'] as bool?,
      disturbHaveRangRepeat: json['disturb_have_rang_repeat'] as bool?,
      doNotDisturb: json['doNotDisturb'] as bool?,
      downloadLanguage: json['downloadLanguage'] as bool?,
      elliptical: json['elliptical'] as bool?,
      exFuncTable: json['exFuncTable'] as bool?,
      exActivityTimeSync: json['ex_activity_time_sync'] as bool?,
      exDhNewAppNotice: json['ex_dh_new_app_notice'] as bool?,
      exGps: json['ex_gps'] as bool?,
      exId107LDial: json['ex_id107_l_dial'] as bool?,
      exLang1Danish: json['ex_lang1_danish'] as bool?,
      exLang1Slovak: json['ex_lang1_slovak'] as bool?,
      exLang2Croatian: json['ex_lang2_croatian'] as bool?,
      exLang2Hindi: json['ex_lang2_hindi'] as bool?,
      exLang2Indonesian: json['ex_lang2_indonesian'] as bool?,
      exLang2Korean: json['ex_lang2_korean'] as bool?,
      exLang2Portuguese: json['ex_lang2_portuguese'] as bool?,
      exLang2Turkish: json['ex_lang2_turkish'] as bool?,
      exLang3Arabic: json['ex_lang3_arabic'] as bool?,
      exLang3Burmese: json['ex_lang3_burmese'] as bool?,
      exLang3Filipino: json['ex_lang3_filipino'] as bool?,
      exLang3Greek: json['ex_lang3_greek'] as bool?,
      exLang3Sweden: json['ex_lang3_sweden'] as bool?,
      exLang3Thai: json['ex_lang3_thai'] as bool?,
      exLang3TraditionalChinese: json['ex_lang3_traditional_chinese'] as bool?,
      exLang3Vietnamese: json['ex_lang3_vietnamese'] as bool?,
      exLangDutch: json['ex_lang_dutch'] as bool?,
      exLangHungarian: json['ex_lang_hungarian'] as bool?,
      exLangLithuanian: json['ex_lang_lithuanian'] as bool?,
      exLangPolish: json['ex_lang_polish'] as bool?,
      exLangRomanian: json['ex_lang_romanian'] as bool?,
      exLangRussian: json['ex_lang_russian'] as bool?,
      exLangSlovenian: json['ex_lang_slovenian'] as bool?,
      exLangUkrainian: json['ex_lang_ukrainian'] as bool?,
      exMain3CalorieGoal: json['ex_main3_calorie_goal'] as bool?,
      exMain3DistanceGoal: json['ex_main3_distance_goal'] as bool?,
      exMain3GetDoNotDisturb: json['ex_main3_get_do_not_disturb'] as bool?,
      exMain3Menstruation: json['ex_main3_menstruation'] as bool?,
      exMain3V3Pressure: json['ex_main3_v3_pressure'] as bool?,
      exMain3V3Spo2Data: json['ex_main3_v3_spo2_data'] as bool?,
      exMain4DrinkWaterReminder: json['ex_main4_drink_water_reminder'] as bool?,
      exMain4IosAutoPair: json['ex_main4_ios_auto_pair'] as bool?,
      exMain4IosNoDisconnectPair:
          json['ex_main4_ios_no_disconnect_pair'] as bool?,
      exMain4V3ActivityData: json['ex_main4_v3_activity_data'] as bool?,
      exMain4V3GpsDataData: json['ex_main4_v3_gps_data_data'] as bool?,
      exMain4V3HrData: json['ex_main4_v3_hr_data'] as bool?,
      exMain4V3Swim: json['ex_main4_v3_swim'] as bool?,
      exMain7ChargingTime: json['ex_main7_charging_time'] as bool?,
      exMain7MenuList: json['ex_main7_menu_list'] as bool?,
      exMain7PhotoWallpaper: json['ex_main7_photo_wallpaper'] as bool?,
      exMain7UtcTimeZone: json['ex_main7_utc_time_zone'] as bool?,
      exNoitice128byte: json['ex_noitice_128byte'] as bool?,
      exNotice250byte: json['ex_notice_250byte'] as bool?,
      exScreenBrightness: json['ex_screen_brightness'] as bool?,
      exSleepPeriod: json['ex_sleep_period'] as bool?,
      exTableMain10ClearBleCache:
          json['ex_table_main10_clear_ble_cache'] as bool?,
      exTableMain10GetDevName: json['ex_table_main10_get_dev_name'] as bool?,
      exTableMain10GetWatchId: json['ex_table_main10_get_watch_id'] as bool?,
      exTableMain10SetHandWashingReminder:
          json['ex_table_main10_set_hand_washing_reminder'] as bool?,
      exTableMain10SetPhoneVoice:
          json['ex_table_main10_set_phone_voice'] as bool?,
      exTableMain10V3GetLangLibrary:
          json['ex_table_main10_v3_get_lang_library'] as bool?,
      exTableMain10V3NotifyMsg: json['ex_table_main10_v3_notify_msg'] as bool?,
      exTableMain10V3VoiceSupportAlexa:
          json['ex_table_main10_v3_voice_support_alexa'] as bool?,
      exTableMain11AlarmOtherIsNoLabel:
          json['ex_table_main11_alarm_other_is_no_label'] as bool?,
      exTableMain11NotSupportHeartRateHighAlarm:
          json['ex_table_main11_not_support_heart_rate_high_alarm'] as bool?,
      exTableMain11NotSupportV3ActivityGpsExchange:
          json['ex_table_main11_not_support_v3_activity_gps_exchange'] as bool?,
      exTableMain11PressureHighThresholdReminder:
          json['ex_table_main11_pressure_high_threshold_reminder'] as bool?,
      exTableMain11SupportCloudDial:
          json['ex_table_main11_support_cloud_dial'] as bool?,
      exTableMain11TakingMedicine:
          json['ex_table_main11_taking_medicine'] as bool?,
      exTableMain11UseAesEncode:
          json['ex_table_main11_use_aes_encode'] as bool?,
      exTableMain7ChoiceUse: json['ex_table_main7_choice_use'] as bool?,
      exTableMain7HeartRateInterval:
          json['ex_table_main7_heart_rate_interval'] as bool?,
      exTableMain7V3SportsType: json['ex_table_main7_v3_sports_type'] as bool?,
      exTableMain7VoiceTransmission:
          json['ex_table_main7_voice_transmission'] as bool?,
      exTableMain8EncryptedAuth: json['ex_table_main8_encrypted_auth'] as bool?,
      exTableMain8ScreenBrightness3Level:
          json['ex_table_main8_screen_brightness_3_level'] as bool?,
      exTableMain8UbloxModel: json['ex_table_main8_ublox_model'] as bool?,
      exTableMain8V3GetHeatLog: json['ex_table_main8_v3_get_heat_log'] as bool?,
      exTableMain8V3Sleep: json['ex_table_main8_v3_sleep'] as bool?,
      exTableMain8V3Spo2OffChange:
          json['ex_table_main8_v3_spo2_off_change'] as bool?,
      exTableMain8V3SyncActivity:
          json['ex_table_main8_v3_sync_activity'] as bool?,
      exTableMain8V3SyncAlarm: json['ex_table_main8_v3_sync_alarm'] as bool?,
      exTableMain9FastMsgData: json['ex_table_main9_fast_msg_data'] as bool?,
      exTableMain9GetDeviceUpdateState:
          json['ex_table_main9_get_device_update_state'] as bool?,
      exTableMain9GetScreenBrightness:
          json['ex_table_main9_get_screen_brightness'] as bool?,
      exTableMain9GetUpHandGesture:
          json['ex_table_main9_get_up_hand_gesture'] as bool?,
      exTableMain9IsWatch: json['ex_table_main9_is_watch'] as bool?,
      exTableMain9RestoreFactory:
          json['ex_table_main9_restore_factory'] as bool?,
      exTableMain9V3ActivityExchangeData:
          json['ex_table_main9_v3_activity_exchange_data'] as bool?,
      exTableMain9V3Sports: json['ex_table_main9_v3_sports'] as bool?,
      exV3Log: json['ex_v3_log'] as bool?,
      factoryReset: json['factory_reset'] as bool?,
      fastSync: json['fastSync'] as bool?,
      findDevice: json['findDevice'] as bool?,
      findPhone: json['findPhone'] as bool?,
      fineTImeControl: json['fineTImeControl'] as bool?,
      flashLog: json['flashLog'] as bool?,
      flipScreen: json['flipScreen'] as bool?,
      footvolley: json['footvolley'] as bool?,
      healthSyncV3ActivityEndTimeUseUtcMode:
          json['health_sync_v3_activity_end_time_use_utc_mode'] as bool?,
      heartRate: json['heartRate'] as bool?,
      heartRateMonitor: json['heartRateMonitor'] as bool?,
      heartRateOffByDefault: json['heart_rate_off_by_default'] as bool?,
      hidPhoto: json['hidPhoto'] as bool?,
      highBar: json['high_bar'] as bool?,
      indoorCycle: json['indoor_cycle'] as bool?,
      indoorRun: json['indoor_run'] as bool?,
      indoorWalk: json['indoor_walk'] as bool?,
      instagram: json['instagram'] as bool?,
      isNeedSyncV2: json['is_need_sync_v2'] as bool?,
      langBengali: json['lang_bengali'] as bool?,
      langBrazilianPortuguese: json['lang_brazilian_portuguese'] as bool?,
      langCh: json['lang_ch'] as bool?,
      langCzech: json['lang_czech'] as bool?,
      langEng: json['lang_eng'] as bool?,
      langFinland: json['lang_finland'] as bool?,
      langFrench: json['lang_french'] as bool?,
      langGerman: json['lang_german'] as bool?,
      langHebrew: json['lang_hebrew'] as bool?,
      langItalian: json['lang_italian'] as bool?,
      langJapanese: json['lang_japanese'] as bool?,
      langKhmer: json['lang_khmer'] as bool?,
      langMalay: json['lang_malay'] as bool?,
      langNorwegian: json['lang_norwegian'] as bool?,
      langPersia: json['lang_persia'] as bool?,
      langSerbian: json['lang_serbian'] as bool?,
      langSpanish: json['lang_spanish'] as bool?,
      level5HrInterval: json['level5_hr_interval'] as bool?,
      liftingWristBacklight: json['liftingWristBacklight'] as bool?,
      linkedIn: json['linked_in'] as bool?,
      logIn: json['logIn'] as bool?,
      longMtu: json['long_mtu'] as bool?,
      mediumToHighActiveDuration: json['mediumToHighActiveDuration'] as bool?,
      messengre: json['messengre'] as bool?,
      mountainBiking: json['mountain_biking'] as bool?,
      mountaineering: json['mountaineering'] as bool?,
      multiActivityNoUseApp: json['multiActivityNoUseApp'] as bool?,
      multiDial: json['multiDial'] as bool?,
      nightAutoBrightness: json['night_auto_brightness'] as bool?,
      noShowHRInterval: json['noShowHRInterval'] as bool?,
      noiseSupportSetNotifyFlag: json['noise_support_set_notify_flag'] as bool?,
      noiseSupportSetOverwarning:
          json['noise_support_set_overwarning'] as bool?,
      notSupportAppSendRunPlan: json['not_support_app_send_run_plan'] as bool?,
      notSupportDeleteAddSportSort:
          json['not_support_delete_add_sport_sort'] as bool?,
      notSupportIndoorRunGetVo2max:
          json['not_support_indoor_run_get_vo2max'] as bool?,
      notSupportSetOvulation: json['not_support_set_ovulation'] as bool?,
      noticeEmail: json['noticeEmail'] as bool?,
      noticeFacebook: json['noticeFacebook'] as bool?,
      noticeMessage: json['noticeMessage'] as bool?,
      noticeQQ: json['noticeQQ'] as bool?,
      noticeSinaWeibo: json['noticeSinaWeibo'] as bool?,
      noticeTwitter: json['noticeTwitter'] as bool?,
      noticeWeixin: json['noticeWeixin'] as bool?,
      noticeAmazon: json['notice_Amazon'] as bool?,
      noticeDailyhunt: json['notice_Dailyhunt'] as bool?,
      noticeFlipkart: json['notice_Flipkart'] as bool?,
      noticeGpay: json['notice_Gpay'] as bool?,
      noticeHotstar: json['notice_Hotstar'] as bool?,
      noticeInshorts: json['notice_Inshorts'] as bool?,
      noticeJioTv: json['notice_Jio_Tv'] as bool?,
      noticeMakeMyTrip: json['notice_Make_My_Trip'] as bool?,
      noticeNetflix: json['notice_Netflix'] as bool?,
      noticePaytm: json['notice_Paytm'] as bool?,
      noticePhonpe: json['notice_Phonpe'] as bool?,
      noticePrime: json['notice_Prime'] as bool?,
      noticeRedbus: json['notice_Redbus'] as bool?,
      noticeSwiggy: json['notice_Swiggy'] as bool?,
      noticeTiktok: json['notice_TikTok'] as bool?,
      noticeZomato: json['notice_Zomato'] as bool?,
      noticeChatwork: json['notice_chatwork'] as bool?,
      noticeKeep: json['notice_keep'] as bool?,
      noticePinterestYahoo: json['notice_pinterest_yahoo'] as bool?,
      noticeSlack: json['notice_slack'] as bool?,
      noticeStepper: json['notice_stepper'] as bool?,
      noticeTumblr: json['notice_tumblr'] as bool?,
      noticeYahooMail: json['notice_yahoo_mail'] as bool?,
      noticeYoutube: json['notice_youtube'] as bool?,
      onetouchCalling: json['onetouchCalling'] as bool?,
      openWaterSwim: json['open_water_swim'] as bool?,
      orienteering: json['orienteering'] as bool?,
      other: json['other'] as bool?,
      otherActivity: json['other_activity'] as bool?,
      outdoorCycle: json['outdoor_cycle'] as bool?,
      outdoorFun: json['outdoor_fun'] as bool?,
      outdoorRun: json['outdoor_run'] as bool?,
      outdoorWalk: json['outdoor_walk'] as bool?,
      parachuting: json['parachuting'] as bool?,
      parallelBars: json['parallel_bars'] as bool?,
      pickleball: json['pickleball'] as bool?,
      pilates: json['pilates'] as bool?,
      poolSwim: json['pool_swim'] as bool?,
      protocolV3SportRecordShowConfig:
          json['protocol_v3_sport_record_show_config'] as bool?,
      pullUp: json['pull_up'] as bool?,
      realtimeData: json['realtimeData'] as bool?,
      rower: json['rower'] as bool?,
      scheduleReminderNotDisplayTitle:
          json['schedule_reminder_not_display_title'] as bool?,
      scientificSleepSwitchOffByDefault:
          json['scientific_sleep_switch_off_by_default'] as bool?,
      screenBrightness5Level: json['screen_brightness_5_level'] as bool?,
      sedentariness: json['sedentariness'] as bool?,
      shortcut: json['shortcut'] as bool?,
      singleSport: json['singleSport'] as bool?,
      skype: json['skype'] as bool?,
      sleepMonitor: json['sleepMonitor'] as bool?,
      smartRope: json['smart_rope'] as bool?,
      sportModeSort: json['sport_mode_sort'] as bool?,
      sportShowNum: json['sport_show_num'] as int?,
      sportType0Badminton: json['sport_type0_badminton'] as bool?,
      sportType0ByBike: json['sport_type0_by_bike'] as bool?,
      sportType0MountainClimbing:
          json['sport_type0_mountain_climbing'] as bool?,
      sportType0OnFoot: json['sport_type0_on_foot'] as bool?,
      sportType0Other: json['sport_type0_other'] as bool?,
      sportType0Run: json['sport_type0_run'] as bool?,
      sportType0Swim: json['sport_type0_swim'] as bool?,
      sportType0Walk: json['sport_type0_walk'] as bool?,
      sportType1Dumbbell: json['sport_type1_dumbbell'] as bool?,
      sportType1Ellipsoid: json['sport_type1_ellipsoid'] as bool?,
      sportType1Fitness: json['sport_type1_fitness'] as bool?,
      sportType1PushUp: json['sport_type1_push_up'] as bool?,
      sportType1SitUp: json['sport_type1_sit_up'] as bool?,
      sportType1Spinning: json['sport_type1_spinning'] as bool?,
      sportType1Treadmill: json['sport_type1_treadmill'] as bool?,
      sportType1Weightlifting: json['sport_type1_weightlifting'] as bool?,
      sportType2Basketball: json['sport_type2_basketball'] as bool?,
      sportType2BodybuildingExercise:
          json['sport_type2_bodybuilding_exercise'] as bool?,
      sportType2Footballl: json['sport_type2_footballl'] as bool?,
      sportType2RopeSkipping: json['sport_type2_rope_skipping'] as bool?,
      sportType2TableTennis: json['sport_type2_table_tennis'] as bool?,
      sportType2Tennis: json['sport_type2_tennis'] as bool?,
      sportType2Volleyball: json['sport_type2_volleyball'] as bool?,
      sportType2Yoga: json['sport_type2_yoga'] as bool?,
      sportType3Baseball: json['sport_type3_baseball'] as bool?,
      sportType3CoreTraining: json['sport_type3_core_training'] as bool?,
      sportType3Dance: json['sport_type3_dance'] as bool?,
      sportType3Golf: json['sport_type3_golf'] as bool?,
      sportType3RollerSkating: json['sport_type3_roller_skating'] as bool?,
      sportType3Skiing: json['sport_type3_skiing'] as bool?,
      sportType3StrengthTraining:
          json['sport_type3_strength_training'] as bool?,
      sportType3TidyUpRelax: json['sport_type3_tidy_up_relax'] as bool?,
      sportTypeTraditionalStrengthTraining:
          json['sport_type_traditional_strength_training'] as bool?,
      squat: json['squat'] as bool?,
      standingWaterSkiing: json['standing_water_skiing'] as bool?,
      staticHR: json['staticHR'] as bool?,
      stepCalculation: json['stepCalculation'] as bool?,
      supportAchievedRemindOnOff:
          json['support_achieved_remind_on_off'] as bool?,
      supportActivityExchangeSetGpsCoordinates:
          json['support_activity_exchange_set_gps_coordinates'] as bool?,
      supportAlipay: json['support_alipay'] as bool?,
      supportAppSendPhoneSystemInfo:
          json['support_app_send_phone_system_info'] as bool?,
      supportBaidu: json['support_baidu'] as bool?,
      supportBarometricAltimeter: json['support_barometric_altimeter'] as bool?,
      supportBleControlPhotograph:
          json['support_ble_control_photograph'] as bool?,
      supportBleToAppDailChange:
          json['support_ble_to_app_dail_change'] as bool?,
      supportBloodPressureModelFileUpdate:
          json['support_blood_pressure_model_file_update'] as bool?,
      supportCalendarReminder: json['support_calendar_reminder'] as bool?,
      supportCallList: json['support_call_list'] as bool?,
      supportCallingQuickReply: json['support_calling_quick_reply'] as bool?,
      supportCompass: json['support_compass'] as bool?,
      supportConfigDefaultMegApplicationList:
          json['support_config_default_meg_application_list'] as bool?,
      supportControlMiniProgram: json['support_control_mini_program'] as bool?,
      supportDialFrameEncodeFormatArgb6666:
          json['support_dial_frame_encode_format_argb6666'] as bool?,
      supportDingtalk: json['support_dingtalk'] as bool?,
      supportDisplayNapSleep: json['support_display_nap_sleep'] as bool?,
      supportDouyin: json['support_douyin'] as bool?,
      supportDrinkPlan: json['support_drink_plan'] as bool?,
      supportECardOperate: json['support_e_card_operate'] as bool?,
      supportEleme: json['support_eleme'] as bool?,
      supportEncryptedCodeResend0405:
          json['support_encrypted_code_resend_04_05'] as bool?,
      supportExchangeActivityGetAltitudeRiseLoss:
          json['support_exchange_activity_get_altitude_rise_loss'] as bool?,
      supportExchangeActivityGetGpsStatus:
          json['support_exchange_activity_get_gps_status'] as bool?,
      supportFahrenheit: json['support_fahrenheit'] as bool?,
      supportFastrackReflexWorld:
          json['support_fastrack_reflex_world'] as bool?,
      supportGetFlashLogSize: json['support_get_flash_log_size'] as bool?,
      supportGetPeripheralsInfo: json['support_get_peripherals_info'] as bool?,
      supportGetPressureSwitchInfo:
          json['support_get_pressure_switch_info'] as bool?,
      supportGetProtocolV3OperateAlgFile:
          json['support_get_protocol_v3_operate_alg_file'] as bool?,
      supportGetSetMaxItemsNum: json['support_get_set_max_items_num'] as bool?,
      supportGetSmartHeartRate: json['support_get_smart_heart_rate'] as bool?,
      supportGetSnInfo: json['support_get_sn_info'] as bool?,
      supportGetSpo2SwitchInfo: json['support_get_spo2_switch_info'] as bool?,
      supportGetUnit: json['support_get_unit'] as bool?,
      supportGetV3DeviceAlgorithmVersion:
          json['support_get_v3_device_algorithm_version'] as bool?,
      supportGetV3DeviceBtConnectPhoneModel:
          json['support_get_v3_device_bt_connect_phone_model'] as bool?,
      supportGetWalkReminder: json['support_get_walk_reminder'] as bool?,
      supportHamaFitMove: json['support_hama_fit_move'] as bool?,
      supportJd: json['support_jd'] as bool?,
      supportLoopsFit: json['support_loops_fit'] as bool?,
      supportLoudspeaker: json['support_loudspeaker'] as bool?,
      supportLvglDialFrame: json['support_lvgl_dial_frame'] as bool?,
      supportMakeWatchDialDeocdeJpg:
          json['support_make_watch_dial_deocde_jpg'] as bool?,
      supportMeituan: json['support_meituan'] as bool?,
      supportMorningEdition: json['support_morning_edition'] as bool?,
      supportOnekeyDoubleContact:
          json['support_onekey_double_contact'] as bool?,
      supportOverFindPhone: json['support_over_find_phone'] as bool?,
      supportPerMinuteOne: json['support_per_minute_one'] as bool?,
      supportPinduoduo: json['support_pinduoduo'] as bool?,
      supportRecoverTimeAndVo2max:
          json['support_recover_time_and_vo2max'] as bool?,
      supportRyzeConnect: json['support_ryze_connect'] as bool?,
      supportSecondSportIcon: json['support_second_sport_icon'] as bool?,
      supportSedentaryTensileHabitInfo:
          json['support_sedentary_tensile_habit_info'] as bool?,
      supportSendBindDeviceTable:
          json['support_send_bind_device_table'] as bool?,
      supportSendEncryptedDataWithBind:
          json['support_send_encrypted_data_with_bind'] as bool?,
      supportSendGpsLongitudeAndLatitude:
          json['support_send_gps_longitude_and_latitude'] as bool?,
      supportSendOriginalSize: json['support_send_original_size'] as bool?,
      supportSendScalesModelMapTable:
          json['support_send_scales_model_map_table'] as bool?,
      supportSetCallQuickReplyOnOff:
          json['support_set_call_quick_reply_on_off'] as bool?,
      supportSetEcgReminder: json['support_set_ecg_reminder'] as bool?,
      supportSetEciReminder: json['support_set_eci_reminder'] as bool?,
      supportSetFastModeWhenSyncConfig:
          json['support_set_fast_mode_when_sync_config'] as bool?,
      supportSetFitnessGuidance: json['support_set_fitness_guidance'] as bool?,
      supportSetGameTimeReminder:
          json['support_set_game_time_reminder'] as bool?,
      supportSetHistoricalMenstruationUseVersion2:
          json['support_set_historical_menstruation_use_version2'] as bool?,
      supportSetListStyle: json['support_set_list_style'] as bool?,
      supportSetMenstrualReminderOnOff:
          json['support_set_menstrual_reminder_on_off'] as bool?,
      supportSetMenuListTypeMeasure:
          json['support_set_menu_list_type_measure'] as bool?,
      supportSetNoticeMessageStateUseVersion0x20:
          json['support_set_notice_message_state_use_version0x20'] as bool?,
      supportSetPeripheralsInfo: json['support_set_peripherals_info'] as bool?,
      supportSetScreenBrightInterval:
          json['support_set_screen_bright_interval'] as bool?,
      supportSetV3HeartInterval: json['support_set_v3_heart_interval'] as bool?,
      supportSetV3WeatcherAddAtmosphericPressure:
          json['support_set_v3_weatcher_add_atmospheric_pressure'] as bool?,
      supportSetV3WeatcherAddSnowDepth:
          json['support_set_v3_weatcher_add_snow_depth'] as bool?,
      supportSetV3WeatcherAddSnowfall:
          json['support_set_v3_weatcher_add_snowfall'] as bool?,
      supportSetV3WeatcherSendStructVersion04:
          json['support_set_v3_weatcher_send_struct_version_04'] as bool?,
      supportSetVersionInformation:
          json['support_set_version_information'] as bool?,
      supportSetVoiceAssistantStatus:
          json['support_set_voice_assistant_status'] as bool?,
      supportSetWeatherHistoryFutureAqi:
          json['support_set_weather_history_future_aqi'] as bool?,
      supportSixAxisSensor: json['support_six_axis_sensor'] as bool?,
      supportSleepPlan: json['support_sleep_plan'] as bool?,
      supportSmartCompetitor: json['support_smart_competitor'] as bool?,
      supportSyncActivityData3dDistanceSpeed:
          json['support_sync_activity_data_3d_distance_speed'] as bool?,
      supportSyncActivityDataAltitudeInfo:
          json['support_sync_activity_data_altitude_info'] as bool?,
      supportSyncActivityDataAvgSlope:
          json['support_sync_activity_data_avg_slope'] as bool?,
      supportSyncActivityGetAnaerobicTrainingEffect:
          json['support_sync_activity_get_anaerobic_training_effect'] as bool?,
      supportSyncActivityGetLoad:
          json['support_sync_activity_get_load'] as bool?,
      supportSyncActivityGetRealTimeOxygenConsumption:
          json['support_sync_activity_get_real_time_oxygen_consumption']
              as bool?,
      supportSyncActivityGetRealTimePhysicalExertion:
          json['support_sync_activity_get_real_time_physical_exertion']
              as bool?,
      supportSyncActivityGetRopeInfo:
          json['support_sync_activity_get_rope_info'] as bool?,
      supportSyncActivityGetRunningPowerInfo:
          json['support_sync_activity_get_running_power_info'] as bool?,
      supportSyncActivityTypeTreadmillsShowStep:
          json['support_sync_activity_type_treadmills_show_step'] as bool?,
      supportSyncEcg: json['support_sync_ecg'] as bool?,
      supportSyncHealthHrUseVersionCompatible:
          json['support_sync_health_hr_use_version_compatible'] as bool?,
      supportSyncHealthSwimGetAvgFrequency:
          json['support_sync_health_swim_get_avg_frequency'] as bool?,
      supportSyncHealthSwimGetAvgSpeed:
          json['support_sync_health_swim_get_avg_speed'] as bool?,
      supportTaobao: json['support_taobao'] as bool?,
      supportTasSmart: json['support_tas_smart'] as bool?,
      supportTmail: json['support_tmail'] as bool?,
      supportToutiao: json['support_toutiao'] as bool?,
      supportTypeResetDeviceBluetooth:
          json['support_type_reset_device_bluetooth'] as bool?,
      supportUpdateGps: json['support_update_gps'] as bool?,
      supportV2DisturbAllDaySwitch:
          json['support_v2_disturb_all_day_switch'] as bool?,
      supportV2DisturbSmartSwitch:
          json['support_v2_disturb_smart_switch'] as bool?,
      supportV2GetDeletableMeunList:
          json['support_v2_get_deletable_meun_list'] as bool?,
      supportV2SetShowMusicInfoSwitch:
          json['support_v2_set_show_music_info_switch'] as bool?,
      supportV3SleepHealthSyncAddSleepAvgHr:
          json['support_v3_sleep_health_sync_add_sleep_avg_hr'] as bool?,
      supportV3SleepHealthSyncAddSleepAvgRespirRate:
          json['support_v3_sleep_health_sync_add_sleep_avg_respir_rate']
              as bool?,
      supportV3SleepHealthSyncAddSleepAvgSpo2:
          json['support_v3_sleep_health_sync_add_sleep_avg_spo2'] as bool?,
      supportVoiceMemoOperate: json['support_voice_memo_operate'] as bool?,
      supportWalkGoalSteps: json['support_walk_goal_steps'] as bool?,
      supportWarmUpBeforeRunning:
          json['support_warm_up_before_running'] as bool?,
      supportWeibo: json['support_weibo'] as bool?,
      suppportPingIos: json['suppport_ping_ios'] as bool?,
      surfing: json['surfing'] as bool?,
      surpportNewRetainData: json['surpport_new_retain_data'] as bool?,
      syncV3HealthSleepDataTypeNotLimit:
          json['sync_v3_health_sleep_data_type_not_limit'] as bool?,
      timeLine: json['timeLine'] as bool?,
      tipInfoContact: json['tipInfoContact'] as bool?,
      tipInfoContent: json['tipInfoContent'] as bool?,
      tipInfoNum: json['tipInfoNum'] as bool?,
      trailRunning: json['trail_running'] as bool?,
      uiControllSports: json['ui_controll_sports'] as bool?,
      unitSet: json['unitSet'] as bool?,
      upHandGestrue: json['upHandGestrue'] as bool?,
      v2GetBtAddr: json['v2_get_bt_addr'] as bool?,
      v2SendCalibrationThreshold:
          json['v2_send_calibration_threshold'] as bool?,
      v2SendNoticeCallTime: json['v2_send_notice_call_time'] as bool?,
      v2SendSetSmartHeartTime: json['v2_send_set_smart_heart_time'] as bool?,
      v2SetAlexaOperation100brightness:
          json['v2_set_alexa_operation_100brightness'] as bool?,
      v2SetNoticeMissedCall: json['v2_set_notice_missed_call'] as bool?,
      v2SetNotificationStatus: json['v2_set_notification_status'] as bool?,
      v2SetStressCalibration: json['v2_set_stress_calibration'] as bool?,
      v2SetUnreadAppReminder03Ea:
          json['v2_set_unread_app_reminder_03_EA'] as bool?,
      v2SupportAddNightLevel: json['v2_support_add_night_level'] as bool?,
      v2SupportAdjustNightTurnOnAfterSunset:
          json['v2_support_adjust_night_turn_on_after_sunset'] as bool?,
      v2SupportDisableFunc: json['v2_support_disable_func'] as bool?,
      v2SupportDisturbThreeOnOff:
          json['v2_support_disturb_three_on_off'] as bool?,
      v2SupportGetAllContact: json['v2_support_get_all_contact'] as bool?,
      v2SupportGetBatteryMode: json['v2_support_get_battery_mode'] as bool?,
      v2SupportNoticeIconInformation:
          json['v2_support_notice_icon_information'] as bool?,
      v2SupportSetBrightScreenTime:
          json['v2_support_set_bright_screen_time'] as bool?,
      v2SupportSetGetMsgAllSwitch:
          json['v2_support_set_get_msg_all_switch'] as bool?,
      v2SupportSetGetNoReminderOnWalkReminder:
          json['v2_support_set_get_no_reminder_on_walk_reminder'] as bool?,
      v2SupportSetNoReminderOnDrinkReminder:
          json['v2_support_set_no_reminder_on_drink_reminder'] as bool?,
      v2SupportSetStepDataType: json['v2_support_set_step_data_type'] as bool?,
      v2SupportSetTimeZoneFloat:
          json['v2_support_set_time_zone_float'] as bool?,
      v2SupportWallpaperWatchFaceOnlyTimeColor:
          json['v2_support_wallpaper_watch_face_only_time_color'] as bool?,
      v2SurportBpSetOrMeasurement:
          json['v2_surport_bp_set_or_measurement'] as bool?,
      v2SurportCallingDelayThreeSeconds:
          json['v2_surport_calling_delay_three_seconds'] as bool?,
      v2SurportTranFlashTelinkLog:
          json['v2_surport_tran_flash_telink_log'] as bool?,
      v2V3SupportRespirationRate:
          json['v2_v3_support_respiration_rate'] as bool?,
      v3BodyPower: json['v3_body_power'] as bool?,
      v3FastMsgData: json['v3_fast_msg_data'] as bool?,
      v3FunctionTable331a: json['v3_function_table_33_1a'] as bool?,
      v3GetHealthSizeByOffset: json['v3_get_health_size_by_offset'] as bool?,
      v3HeartSetRateModeCustom: json['v3_heart_set_rate_mode_custom'] as bool?,
      v3OxygenDataSupportGrade: json['v3_oxygen_data_support_grade'] as bool?,
      v3ScheduleReminderPhaseTwo:
          json['v3_schedule_reminder_phase_two'] as bool?,
      v3SetGetAlarmSpecifyType: json['v3_set_get_alarm_specify_type'] as bool?,
      v3Skateboard: json['v3_skateboard'] as bool?,
      v3SupportActivitySyncRealTime:
          json['v3_support_activity_sync_real_time'] as bool?,
      v3SupportDataTranGetNewErrorCode:
          json['v3_support_data_tran_get_new_error_code'] as bool?,
      v3SupportGetBleBeep: json['v3_support_get_ble_beep'] as bool?,
      v3SupportGetBleMusicInfoVersion0x10:
          json['v3_support_get_ble_music_info_version_0x10'] as bool?,
      v3SupportGetHabitData: json['v3_support_get_habit_data'] as bool?,
      v3SupportGetWatchSize: json['v3_support_get_watch_size'] as bool?,
      v3SupportPerBp: json['v3_support_per_bp'] as bool?,
      v3SupportSetContactVersion0x10:
          json['v3_support_set_contact_version_0x10'] as bool?,
      v3SupportSetGetEmergencyConnact:
          json['v3_support_set_get_emergency_connact'] as bool?,
      v3SupportSetHotStartParam:
          json['v3_support_set_hot_start_param'] as bool?,
      v3SupportSetRepeatTypeOnScheduleReminder:
          json['v3_support_set_repeat_type_on_schedule_reminder'] as bool?,
      v3SupportSetRepeatWeekTypeOnScheduleReminder:
          json['v3_support_set_repeat_week_type_on_schedule_reminder'] as bool?,
      v3SupportSetV3Add48HourWeatherData:
          json['v3_support_set_v3_add_48_hour_weather_data'] as bool?,
      v3SupportSetV3Add48HourWeatherDataOrCityname:
          json['v3_support_set_v3_add_48_hour_weather_data_or_cityname']
              as bool?,
      v3SupportSetV3WeatcherAddAirGrade:
          json['v3_support_set_v3_weatcher_add_air_grade'] as bool?,
      v3SupportSetV3WeatcherAddSunrise:
          json['v3_support_set_v3_weatcher_add_sunrise'] as bool?,
      v3SupportSportsPlan: json['v3_support_sports_plan'] as bool?,
      v3SurportSportMediumIcon: json['v3_surport_sport_medium_icon'] as bool?,
      versionInfo: json['versionInfo'] as bool?,
      walkReminder: json['walk_reminder'] as bool?,
      weather: json['weather'] as bool?,
      weatherCity: json['weather_city'] as bool?,
      wechatSport: json['wechatSport'] as bool?,
      whatsapp: json['whatsapp'] as bool?,
      zumba: json['zumba'] as bool?,
    );

Map<String, dynamic> _$FunctionTableModelToJson(FunctionTableModel instance) =>
    <String, dynamic>{
      'Airoha_gps_chip': instance.airohaGpsChip,
      'BindAuth': instance.BindAuth,
      'BindCodeAuth': instance.BindCodeAuth,
      'BloodPressure': instance.BloodPressure,
      'FiveHRInterval': instance.FiveHRInterval,
      'Gmail': instance.Gmail,
      'HIDPhoto': instance.HIDPhoto,
      'HIIT': instance.HIIT,
      'KakaoTalk': instance.KakaoTalk,
      'Line': instance.Line,
      'Outlook': instance.Outlook,
      'Snapchat': instance.Snapchat,
      'Telegram': instance.Telegram,
      'V2_support_get_heart_rate_mode': instance.v2SupportGetHeartRateMode,
      'V2_support_get_switch_status_append':
          instance.v2SupportGetSwitchStatusAppend,
      'V2_support_set_get_time_goal_type': instance.v2SupportSetGetTimeGoalType,
      'V3_Veryfit_not_support_photo_wallpaper':
          instance.v3VeryfitNotSupportPhotoWallpaper,
      'V3_alexa_reminder_add_sec': instance.v3AlexaReminderAddSec,
      'V3_alexa_set_easy_operate': instance.v3AlexaSetEasyOperate,
      'V3_alexa_set_get_alexa_alarm': instance.v3AlexaSetGetAlexaAlarm,
      'V3_alexa_set_jump_sport_ui': instance.v3AlexaSetJumpSportUi,
      'V3_alexa_set_jump_ui': instance.v3AlexaSetJumpUi,
      'V3_alexa_set_set_on_off_type': instance.v3AlexaSetSetOnOffType,
      'V3_alexa_set_weather': instance.v3AlexaSetWeather,
      'V3_alexa_time_new': instance.v3AlexaTimeNew,
      'V3_auto_activity_switch': instance.v3AutoActivitySwitch,
      'V3_automatic_sync_v3_health_data': instance.v3AutomaticSyncV3HealthData,
      'V3_dev_support_pair_each_connect': instance.v3DevSupportPairEachConnect,
      'V3_drink_water_add_notify_flag': instance.v3DrinkWaterAddNotifyFlag,
      'V3_get_battery_log': instance.v3GetBatteryLog,
      'V3_get_calorie_distance_goal': instance.v3GetCalorieDistanceGoal,
      'V3_get_dev_log_state': instance.v3GetDevLogState,
      'V3_get_menu_list': instance.v3GetMenuList,
      'V3_get_walk_reminder': instance.v3GetWalkReminder,
      'V3_get_watch_list_new': instance.v3GetWatchListNew,
      'V3_health_sync_noise': instance.v3HealthSyncNoise,
      'V3_health_sync_temperature': instance.v3HealthSyncTemperature,
      'V3_menstrual_add_notify_flag': instance.v3MenstrualAddNotifyFlag,
      'V3_music_control_02_add_singer_name':
          instance.v3MusicControl02AddSingerName,
      'V3_pressure_add_notify_flag_and_mode':
          instance.v3PressureAddNotifyFlagAndMode,
      'V3_schedule_reminder': instance.v3ScheduleReminder,
      'V3_set_100_sport_sort': instance.v3Set100SportSort,
      'V3_set_20_base_sport_param_sort': instance.v3Set20BaseSportParamSort,
      'V3_set_main_ui_sort': instance.v3SetMainUiSort,
      'V3_set_mid_high_time_goal': instance.v3SetMidHighTimeGoal,
      'V3_set_sharking_grade': instance.v3SetSharkingGrade,
      'V3_set_walk_reminder_goal_time': instance.v3SetWalkReminderGoalTime,
      'V3_set_wallpaper_dial': instance.v3SetWallpaperDial,
      'V3_set_watch_dial_sort': instance.v3SetWatchDialSort,
      'V3_spo2_add_notify_flag': instance.v3Spo2AddNotifyFlag,
      'V3_support_189email': instance.v3Support189email,
      'V3_support_99taxi': instance.v3Support99taxi,
      'V3_support_Aliexpress': instance.v3SupportAliexpress,
      'V3_support_Americanas': instance.v3SupportAmericanas,
      'V3_support_Enjoei': instance.v3SupportEnjoei,
      'V3_support_Exchangeemail': instance.v3SupportExchangeemail,
      'V3_support_Google_meet': instance.v3SupportGoogleMeet,
      'V3_support_Instantemail': instance.v3SupportInstantemail,
      'V3_support_Magalu': instance.v3SupportMagalu,
      'V3_support_Mercado_livre': instance.v3SupportMercadoLivre,
      'V3_support_Mormaii_Smartwatch': instance.v3SupportMormaiiSmartwatch,
      'V3_support_Motoemail': instance.v3SupportMotoemail,
      'V3_support_Ola': instance.v3SupportOla,
      'V3_support_Rappi': instance.v3SupportRappi,
      'V3_support_Shopee': instance.v3SupportShopee,
      'V3_support_Teams': instance.v3SupportTeams,
      'V3_support_Technos_Connect': instance.v3SupportTechnosConnect,
      'V3_support_Uber': instance.v3SupportUber,
      'V3_support_Uber_Eats': instance.v3SupportUberEats,
      'V3_support_WhatsApp_Business': instance.v3SupportWhatsappBusiness,
      'V3_support_YTmusic': instance.v3SupportYtmusic,
      'V3_support_Yahoo': instance.v3SupportYahoo,
      'V3_support_alibaba_email': instance.v3SupportAlibabaEmail,
      'V3_support_app_send_voice_to_ble': instance.v3SupportAppSendVoiceToBle,
      'V3_support_asuseemail': instance.v3SupportAsuseemail,
      'V3_support_blueemail': instance.v3SupportBlueemail,
      'V3_support_bp_calibration': instance.v3SupportBpCalibration,
      'V3_support_calendario': instance.v3SupportCalendario,
      'V3_support_calorie_unit': instance.v3SupportCalorieUnit,
      'V3_support_cycling_unit': instance.v3SupportCyclingUnit,
      'V3_support_data_tran_continue': instance.v3SupportDataTranContinue,
      'V3_support_dokidokemail': instance.v3SupportDokidokemail,
      'V3_support_general': instance.v3SupportGeneral,
      'V3_support_get_activity_switch': instance.v3SupportGetActivitySwitch,
      'V3_support_get_alexa_default_language':
          instance.v3SupportGetAlexaDefaultLanguage,
      'V3_support_get_health_switch_state':
          instance.v3SupportGetHealthSwitchState,
      'V3_support_get_main_sport_goal': instance.v3SupportGetMainSportGoal,
      'V3_support_googleGmail': instance.v3SupportGooglegmail,
      'V3_support_hrv': instance.v3SupportHrv,
      'V3_support_htcemail': instance.v3SupportHtcemail,
      'V3_support_inboxemail': instance.v3SupportInboxemail,
      'V3_support_lfood': instance.v3SupportLfood,
      'V3_support_mailruemail': instance.v3SupportMailruemail,
      'V3_support_matters_remind': instance.v3SupportMattersRemind,
      'V3_support_microsoft': instance.v3SupportMicrosoft,
      'V3_support_missed_calls': instance.v3SupportMissedCalls,
      'V3_support_mobiemail': instance.v3SupportMobiemail,
      'V3_support_myemail': instance.v3SupportMyemail,
      'V3_support_neteasemail': instance.v3SupportNeteasemail,
      'V3_support_nhnemail': instance.v3SupportNhnemail,
      'V3_support_niosefit': instance.v3SupportNiosefit,
      'V3_support_outlookemail': instance.v3SupportOutlookemail,
      'V3_support_qqemail': instance.v3SupportQqemail,
      'V3_support_scientific_sleep': instance.v3SupportScientificSleep,
      'V3_support_set_scientific_sleep_switch':
          instance.v3SupportSetScientificSleepSwitch,
      'V3_support_set_smart_heart_rate': instance.v3SupportSetSmartHeartRate,
      'V3_support_set_spo2_all_day_on_off':
          instance.v3SupportSetSpo2AllDayOnOff,
      'V3_support_set_spo2_low_value_remind':
          instance.v3SupportSetSpo2LowValueRemind,
      'V3_support_set_temperature_switch':
          instance.v3SupportSetTemperatureSwitch,
      'V3_support_set_v3_music_name': instance.v3SupportSetV3MusicName,
      'V3_support_set_v3_notify_add_app_name':
          instance.v3SupportSetV3NotifyAddAppName,
      'V3_support_set_v3_weather': instance.v3SupportSetV3Weather,
      'V3_support_set_v3_world_time': instance.v3SupportSetV3WorldTime,
      'V3_support_set_weather_sun_time': instance.v3SupportSetWeatherSunTime,
      'V3_support_show_detection_time': instance.v3SupportShowDetectionTime,
      'V3_support_swim_pool_unit': instance.v3SupportSwimPoolUnit,
      'V3_support_swimming_data_exhibit': instance.v3SupportSwimmingDataExhibit,
      'V3_support_sync_contact': instance.v3SupportSyncContact,
      'V3_support_sync_over_high_low_heart_data':
          instance.v3SupportSyncOverHighLowHeartData,
      'V3_support_trtfbluemail': instance.v3SupportTrtfbluemail,
      'V3_support_v3_ble_music': instance.v3SupportV3BleMusic,
      'V3_support_v3_exchange_data_reply_add_real_time_speed_pace':
          instance.v3SupportV3ExchangeDataReplyAddRealTimeSpeedPace,
      'V3_support_v3_get_sport_sort_field':
          instance.v3SupportV3GetSportSortField,
      'V3_support_v3_long_city_name': instance.v3SupportV3LongCityName,
      'V3_support_v3_notify_icon_adaptive':
          instance.v3SupportV3NotifyIconAdaptive,
      'V3_support_veryfit': instance.v3SupportVeryfit,
      'V3_support_walking_running_unit': instance.v3SupportWalkingRunningUnit,
      'V3_support_watch_capacity_size_display':
          instance.v3SupportWatchCapacitySizeDisplay,
      'V3_support_watch_photo_position_move':
          instance.v3SupportWatchPhotoPositionMove,
      'V3_support_wear_flag': instance.v3SupportWearFlag,
      'V3_support_yahooemail': instance.v3SupportYahooemail,
      'V3_support_zohoemail': instance.v3SupportZohoemail,
      'V3_sync_v3_activity_add_param': instance.v3SyncV3ActivityAddParam,
      'V3_v2_02_EB_firmware_bt_version_01_create':
          instance.v3V202EbFirmwareBtVersion01Create,
      'V3_v2_menstrual_remind_02_add_pregnancy':
          instance.v3V2MenstrualRemind02AddPregnancy,
      'V3_v3_33_3D_historical_menstruation_01_create':
          instance.v3V3333dHistoricalMenstruation01Create,
      'V3_walk_reminder_add_notify_flag': instance.v3WalkReminderAddNotifyFlag,
      'V3_watch_dail_set_add_size': instance.v3WatchDailSetAddSize,
      'VKontakte': instance.VKontakte,
      'Viber': instance.Viber,
      'WatchDial': instance.WatchDial,
      'activity_switch': instance.activitySwitch,
      'aerobics_bodybuilding_exercise': instance.aerobicsBodybuildingExercise,
      'agps_offline': instance.agpsOffline,
      'agps_online': instance.agpsOnline,
      'alarmBath': instance.alarmBath,
      'alarmBrushTeeth': instance.alarmBrushTeeth,
      'alarmClock': instance.alarmClock,
      'alarmCount': instance.alarmCount,
      'alarmCourse': instance.alarmCourse,
      'alarmCustom': instance.alarmCustom,
      'alarmDating': instance.alarmDating,
      'alarmDinner': instance.alarmDinner,
      'alarmLearn': instance.alarmLearn,
      'alarmMedicine': instance.alarmMedicine,
      'alarmMetting': instance.alarmMetting,
      'alarmParty': instance.alarmParty,
      'alarmPlayTime': instance.alarmPlayTime,
      'alarmRest': instance.alarmRest,
      'alarmSleep': instance.alarmSleep,
      'alarmSport': instance.alarmSport,
      'alarmWakeUp': instance.alarmWakeUp,
      'allAppNotice': instance.allAppNotice,
      'ancs': instance.ancs,
      'antilost': instance.antilost,
      'auto_activity_end_switch_not_display':
          instance.autoActivityEndSwitchNotDisplay,
      'auto_activity_pause_switch_not_display':
          instance.autoActivityPauseSwitchNotDisplay,
      'auto_activity_set_get_use_new_struct_exchange':
          instance.autoActivitySetGetUseNewStructExchange,
      'auto_activity_switch_add_bicycle': instance.autoActivitySwitchAddBicycle,
      'auto_activity_switch_add_smart_rope':
          instance.autoActivitySwitchAddSmartRope,
      'battling_rope': instance.battlingRope,
      'beach_tennis': instance.beachTennis,
      'bilateralAntiLost': instance.bilateralAntiLost,
      'bleControlMusic': instance.bleControlMusic,
      'bleControlTakePhoto': instance.bleControlTakePhoto,
      'breathe_train': instance.breatheTrain,
      'calendar': instance.calendar,
      'calling': instance.calling,
      'callingContact': instance.callingContact,
      'callingNum': instance.callingNum,
      'choose_other_ota_mode': instance.chooseOtherOtaMode,
      'cricket': instance.cricket,
      'data_tran_over_wait_ble': instance.dataTranOverWaitBle,
      'defaultConfig': instance.defaultConfig,
      'defaultSportType': instance.defaultSportType,
      'deviceUpdate': instance.deviceUpdate,
      'device_control_fast_mode_alone': instance.deviceControlFastModeAlone,
      'displayMode': instance.displayMode,
      'disturb_have_rang_repeat': instance.disturbHaveRangRepeat,
      'doNotDisturb': instance.doNotDisturb,
      'downloadLanguage': instance.downloadLanguage,
      'elliptical': instance.elliptical,
      'exFuncTable': instance.exFuncTable,
      'ex_activity_time_sync': instance.exActivityTimeSync,
      'ex_dh_new_app_notice': instance.exDhNewAppNotice,
      'ex_gps': instance.exGps,
      'ex_id107_l_dial': instance.exId107LDial,
      'ex_lang1_danish': instance.exLang1Danish,
      'ex_lang1_slovak': instance.exLang1Slovak,
      'ex_lang2_croatian': instance.exLang2Croatian,
      'ex_lang2_hindi': instance.exLang2Hindi,
      'ex_lang2_indonesian': instance.exLang2Indonesian,
      'ex_lang2_korean': instance.exLang2Korean,
      'ex_lang2_portuguese': instance.exLang2Portuguese,
      'ex_lang2_turkish': instance.exLang2Turkish,
      'ex_lang3_arabic': instance.exLang3Arabic,
      'ex_lang3_burmese': instance.exLang3Burmese,
      'ex_lang3_filipino': instance.exLang3Filipino,
      'ex_lang3_greek': instance.exLang3Greek,
      'ex_lang3_sweden': instance.exLang3Sweden,
      'ex_lang3_thai': instance.exLang3Thai,
      'ex_lang3_traditional_chinese': instance.exLang3TraditionalChinese,
      'ex_lang3_vietnamese': instance.exLang3Vietnamese,
      'ex_lang_dutch': instance.exLangDutch,
      'ex_lang_hungarian': instance.exLangHungarian,
      'ex_lang_lithuanian': instance.exLangLithuanian,
      'ex_lang_polish': instance.exLangPolish,
      'ex_lang_romanian': instance.exLangRomanian,
      'ex_lang_russian': instance.exLangRussian,
      'ex_lang_slovenian': instance.exLangSlovenian,
      'ex_lang_ukrainian': instance.exLangUkrainian,
      'ex_main3_calorie_goal': instance.exMain3CalorieGoal,
      'ex_main3_distance_goal': instance.exMain3DistanceGoal,
      'ex_main3_get_do_not_disturb': instance.exMain3GetDoNotDisturb,
      'ex_main3_menstruation': instance.exMain3Menstruation,
      'ex_main3_v3_pressure': instance.exMain3V3Pressure,
      'ex_main3_v3_spo2_data': instance.exMain3V3Spo2Data,
      'ex_main4_drink_water_reminder': instance.exMain4DrinkWaterReminder,
      'ex_main4_ios_auto_pair': instance.exMain4IosAutoPair,
      'ex_main4_ios_no_disconnect_pair': instance.exMain4IosNoDisconnectPair,
      'ex_main4_v3_activity_data': instance.exMain4V3ActivityData,
      'ex_main4_v3_gps_data_data': instance.exMain4V3GpsDataData,
      'ex_main4_v3_hr_data': instance.exMain4V3HrData,
      'ex_main4_v3_swim': instance.exMain4V3Swim,
      'ex_main7_charging_time': instance.exMain7ChargingTime,
      'ex_main7_menu_list': instance.exMain7MenuList,
      'ex_main7_photo_wallpaper': instance.exMain7PhotoWallpaper,
      'ex_main7_utc_time_zone': instance.exMain7UtcTimeZone,
      'ex_noitice_128byte': instance.exNoitice128byte,
      'ex_notice_250byte': instance.exNotice250byte,
      'ex_screen_brightness': instance.exScreenBrightness,
      'ex_sleep_period': instance.exSleepPeriod,
      'ex_table_main10_clear_ble_cache': instance.exTableMain10ClearBleCache,
      'ex_table_main10_get_dev_name': instance.exTableMain10GetDevName,
      'ex_table_main10_get_watch_id': instance.exTableMain10GetWatchId,
      'ex_table_main10_set_hand_washing_reminder':
          instance.exTableMain10SetHandWashingReminder,
      'ex_table_main10_set_phone_voice': instance.exTableMain10SetPhoneVoice,
      'ex_table_main10_v3_get_lang_library':
          instance.exTableMain10V3GetLangLibrary,
      'ex_table_main10_v3_notify_msg': instance.exTableMain10V3NotifyMsg,
      'ex_table_main10_v3_voice_support_alexa':
          instance.exTableMain10V3VoiceSupportAlexa,
      'ex_table_main11_alarm_other_is_no_label':
          instance.exTableMain11AlarmOtherIsNoLabel,
      'ex_table_main11_not_support_heart_rate_high_alarm':
          instance.exTableMain11NotSupportHeartRateHighAlarm,
      'ex_table_main11_not_support_v3_activity_gps_exchange':
          instance.exTableMain11NotSupportV3ActivityGpsExchange,
      'ex_table_main11_pressure_high_threshold_reminder':
          instance.exTableMain11PressureHighThresholdReminder,
      'ex_table_main11_support_cloud_dial':
          instance.exTableMain11SupportCloudDial,
      'ex_table_main11_taking_medicine': instance.exTableMain11TakingMedicine,
      'ex_table_main11_use_aes_encode': instance.exTableMain11UseAesEncode,
      'ex_table_main7_choice_use': instance.exTableMain7ChoiceUse,
      'ex_table_main7_heart_rate_interval':
          instance.exTableMain7HeartRateInterval,
      'ex_table_main7_v3_sports_type': instance.exTableMain7V3SportsType,
      'ex_table_main7_voice_transmission':
          instance.exTableMain7VoiceTransmission,
      'ex_table_main8_encrypted_auth': instance.exTableMain8EncryptedAuth,
      'ex_table_main8_screen_brightness_3_level':
          instance.exTableMain8ScreenBrightness3Level,
      'ex_table_main8_ublox_model': instance.exTableMain8UbloxModel,
      'ex_table_main8_v3_get_heat_log': instance.exTableMain8V3GetHeatLog,
      'ex_table_main8_v3_sleep': instance.exTableMain8V3Sleep,
      'ex_table_main8_v3_spo2_off_change': instance.exTableMain8V3Spo2OffChange,
      'ex_table_main8_v3_sync_activity': instance.exTableMain8V3SyncActivity,
      'ex_table_main8_v3_sync_alarm': instance.exTableMain8V3SyncAlarm,
      'ex_table_main9_fast_msg_data': instance.exTableMain9FastMsgData,
      'ex_table_main9_get_device_update_state':
          instance.exTableMain9GetDeviceUpdateState,
      'ex_table_main9_get_screen_brightness':
          instance.exTableMain9GetScreenBrightness,
      'ex_table_main9_get_up_hand_gesture':
          instance.exTableMain9GetUpHandGesture,
      'ex_table_main9_is_watch': instance.exTableMain9IsWatch,
      'ex_table_main9_restore_factory': instance.exTableMain9RestoreFactory,
      'ex_table_main9_v3_activity_exchange_data':
          instance.exTableMain9V3ActivityExchangeData,
      'ex_table_main9_v3_sports': instance.exTableMain9V3Sports,
      'ex_v3_log': instance.exV3Log,
      'factory_reset': instance.factoryReset,
      'fastSync': instance.fastSync,
      'findDevice': instance.findDevice,
      'findPhone': instance.findPhone,
      'fineTImeControl': instance.fineTImeControl,
      'flashLog': instance.flashLog,
      'flipScreen': instance.flipScreen,
      'footvolley': instance.footvolley,
      'health_sync_v3_activity_end_time_use_utc_mode':
          instance.healthSyncV3ActivityEndTimeUseUtcMode,
      'heartRate': instance.heartRate,
      'heartRateMonitor': instance.heartRateMonitor,
      'heart_rate_off_by_default': instance.heartRateOffByDefault,
      'hidPhoto': instance.hidPhoto,
      'high_bar': instance.highBar,
      'indoor_cycle': instance.indoorCycle,
      'indoor_run': instance.indoorRun,
      'indoor_walk': instance.indoorWalk,
      'instagram': instance.instagram,
      'is_need_sync_v2': instance.isNeedSyncV2,
      'lang_bengali': instance.langBengali,
      'lang_brazilian_portuguese': instance.langBrazilianPortuguese,
      'lang_ch': instance.langCh,
      'lang_czech': instance.langCzech,
      'lang_eng': instance.langEng,
      'lang_finland': instance.langFinland,
      'lang_french': instance.langFrench,
      'lang_german': instance.langGerman,
      'lang_hebrew': instance.langHebrew,
      'lang_italian': instance.langItalian,
      'lang_japanese': instance.langJapanese,
      'lang_khmer': instance.langKhmer,
      'lang_malay': instance.langMalay,
      'lang_norwegian': instance.langNorwegian,
      'lang_persia': instance.langPersia,
      'lang_serbian': instance.langSerbian,
      'lang_spanish': instance.langSpanish,
      'level5_hr_interval': instance.level5HrInterval,
      'liftingWristBacklight': instance.liftingWristBacklight,
      'linked_in': instance.linkedIn,
      'logIn': instance.logIn,
      'long_mtu': instance.longMtu,
      'mediumToHighActiveDuration': instance.mediumToHighActiveDuration,
      'messengre': instance.messengre,
      'mountain_biking': instance.mountainBiking,
      'mountaineering': instance.mountaineering,
      'multiActivityNoUseApp': instance.multiActivityNoUseApp,
      'multiDial': instance.multiDial,
      'night_auto_brightness': instance.nightAutoBrightness,
      'noShowHRInterval': instance.noShowHRInterval,
      'noise_support_set_notify_flag': instance.noiseSupportSetNotifyFlag,
      'noise_support_set_overwarning': instance.noiseSupportSetOverwarning,
      'not_support_app_send_run_plan': instance.notSupportAppSendRunPlan,
      'not_support_delete_add_sport_sort':
          instance.notSupportDeleteAddSportSort,
      'not_support_indoor_run_get_vo2max':
          instance.notSupportIndoorRunGetVo2max,
      'not_support_set_ovulation': instance.notSupportSetOvulation,
      'noticeEmail': instance.noticeEmail,
      'noticeFacebook': instance.noticeFacebook,
      'noticeMessage': instance.noticeMessage,
      'noticeQQ': instance.noticeQQ,
      'noticeSinaWeibo': instance.noticeSinaWeibo,
      'noticeTwitter': instance.noticeTwitter,
      'noticeWeixin': instance.noticeWeixin,
      'notice_Amazon': instance.noticeAmazon,
      'notice_Dailyhunt': instance.noticeDailyhunt,
      'notice_Flipkart': instance.noticeFlipkart,
      'notice_Gpay': instance.noticeGpay,
      'notice_Hotstar': instance.noticeHotstar,
      'notice_Inshorts': instance.noticeInshorts,
      'notice_Jio_Tv': instance.noticeJioTv,
      'notice_Make_My_Trip': instance.noticeMakeMyTrip,
      'notice_Netflix': instance.noticeNetflix,
      'notice_Paytm': instance.noticePaytm,
      'notice_Phonpe': instance.noticePhonpe,
      'notice_Prime': instance.noticePrime,
      'notice_Redbus': instance.noticeRedbus,
      'notice_Swiggy': instance.noticeSwiggy,
      'notice_TikTok': instance.noticeTiktok,
      'notice_Zomato': instance.noticeZomato,
      'notice_chatwork': instance.noticeChatwork,
      'notice_keep': instance.noticeKeep,
      'notice_pinterest_yahoo': instance.noticePinterestYahoo,
      'notice_slack': instance.noticeSlack,
      'notice_stepper': instance.noticeStepper,
      'notice_tumblr': instance.noticeTumblr,
      'notice_yahoo_mail': instance.noticeYahooMail,
      'notice_youtube': instance.noticeYoutube,
      'onetouchCalling': instance.onetouchCalling,
      'open_water_swim': instance.openWaterSwim,
      'orienteering': instance.orienteering,
      'other': instance.other,
      'other_activity': instance.otherActivity,
      'outdoor_cycle': instance.outdoorCycle,
      'outdoor_fun': instance.outdoorFun,
      'outdoor_run': instance.outdoorRun,
      'outdoor_walk': instance.outdoorWalk,
      'parachuting': instance.parachuting,
      'parallel_bars': instance.parallelBars,
      'pickleball': instance.pickleball,
      'pilates': instance.pilates,
      'pool_swim': instance.poolSwim,
      'protocol_v3_sport_record_show_config':
          instance.protocolV3SportRecordShowConfig,
      'pull_up': instance.pullUp,
      'realtimeData': instance.realtimeData,
      'rower': instance.rower,
      'schedule_reminder_not_display_title':
          instance.scheduleReminderNotDisplayTitle,
      'scientific_sleep_switch_off_by_default':
          instance.scientificSleepSwitchOffByDefault,
      'screen_brightness_5_level': instance.screenBrightness5Level,
      'sedentariness': instance.sedentariness,
      'shortcut': instance.shortcut,
      'singleSport': instance.singleSport,
      'skype': instance.skype,
      'sleepMonitor': instance.sleepMonitor,
      'smart_rope': instance.smartRope,
      'sport_mode_sort': instance.sportModeSort,
      'sport_show_num': instance.sportShowNum,
      'sport_type0_badminton': instance.sportType0Badminton,
      'sport_type0_by_bike': instance.sportType0ByBike,
      'sport_type0_mountain_climbing': instance.sportType0MountainClimbing,
      'sport_type0_on_foot': instance.sportType0OnFoot,
      'sport_type0_other': instance.sportType0Other,
      'sport_type0_run': instance.sportType0Run,
      'sport_type0_swim': instance.sportType0Swim,
      'sport_type0_walk': instance.sportType0Walk,
      'sport_type1_dumbbell': instance.sportType1Dumbbell,
      'sport_type1_ellipsoid': instance.sportType1Ellipsoid,
      'sport_type1_fitness': instance.sportType1Fitness,
      'sport_type1_push_up': instance.sportType1PushUp,
      'sport_type1_sit_up': instance.sportType1SitUp,
      'sport_type1_spinning': instance.sportType1Spinning,
      'sport_type1_treadmill': instance.sportType1Treadmill,
      'sport_type1_weightlifting': instance.sportType1Weightlifting,
      'sport_type2_basketball': instance.sportType2Basketball,
      'sport_type2_bodybuilding_exercise':
          instance.sportType2BodybuildingExercise,
      'sport_type2_footballl': instance.sportType2Footballl,
      'sport_type2_rope_skipping': instance.sportType2RopeSkipping,
      'sport_type2_table_tennis': instance.sportType2TableTennis,
      'sport_type2_tennis': instance.sportType2Tennis,
      'sport_type2_volleyball': instance.sportType2Volleyball,
      'sport_type2_yoga': instance.sportType2Yoga,
      'sport_type3_baseball': instance.sportType3Baseball,
      'sport_type3_core_training': instance.sportType3CoreTraining,
      'sport_type3_dance': instance.sportType3Dance,
      'sport_type3_golf': instance.sportType3Golf,
      'sport_type3_roller_skating': instance.sportType3RollerSkating,
      'sport_type3_skiing': instance.sportType3Skiing,
      'sport_type3_strength_training': instance.sportType3StrengthTraining,
      'sport_type3_tidy_up_relax': instance.sportType3TidyUpRelax,
      'sport_type_traditional_strength_training':
          instance.sportTypeTraditionalStrengthTraining,
      'squat': instance.squat,
      'standing_water_skiing': instance.standingWaterSkiing,
      'staticHR': instance.staticHR,
      'stepCalculation': instance.stepCalculation,
      'support_achieved_remind_on_off': instance.supportAchievedRemindOnOff,
      'support_activity_exchange_set_gps_coordinates':
          instance.supportActivityExchangeSetGpsCoordinates,
      'support_alipay': instance.supportAlipay,
      'support_app_send_phone_system_info':
          instance.supportAppSendPhoneSystemInfo,
      'support_baidu': instance.supportBaidu,
      'support_barometric_altimeter': instance.supportBarometricAltimeter,
      'support_ble_control_photograph': instance.supportBleControlPhotograph,
      'support_ble_to_app_dail_change': instance.supportBleToAppDailChange,
      'support_blood_pressure_model_file_update':
          instance.supportBloodPressureModelFileUpdate,
      'support_calendar_reminder': instance.supportCalendarReminder,
      'support_call_list': instance.supportCallList,
      'support_calling_quick_reply': instance.supportCallingQuickReply,
      'support_compass': instance.supportCompass,
      'support_config_default_meg_application_list':
          instance.supportConfigDefaultMegApplicationList,
      'support_control_mini_program': instance.supportControlMiniProgram,
      'support_dial_frame_encode_format_argb6666':
          instance.supportDialFrameEncodeFormatArgb6666,
      'support_dingtalk': instance.supportDingtalk,
      'support_display_nap_sleep': instance.supportDisplayNapSleep,
      'support_douyin': instance.supportDouyin,
      'support_drink_plan': instance.supportDrinkPlan,
      'support_e_card_operate': instance.supportECardOperate,
      'support_eleme': instance.supportEleme,
      'support_encrypted_code_resend_04_05':
          instance.supportEncryptedCodeResend0405,
      'support_exchange_activity_get_altitude_rise_loss':
          instance.supportExchangeActivityGetAltitudeRiseLoss,
      'support_exchange_activity_get_gps_status':
          instance.supportExchangeActivityGetGpsStatus,
      'support_fahrenheit': instance.supportFahrenheit,
      'support_fastrack_reflex_world': instance.supportFastrackReflexWorld,
      'support_get_flash_log_size': instance.supportGetFlashLogSize,
      'support_get_peripherals_info': instance.supportGetPeripheralsInfo,
      'support_get_pressure_switch_info': instance.supportGetPressureSwitchInfo,
      'support_get_protocol_v3_operate_alg_file':
          instance.supportGetProtocolV3OperateAlgFile,
      'support_get_set_max_items_num': instance.supportGetSetMaxItemsNum,
      'support_get_smart_heart_rate': instance.supportGetSmartHeartRate,
      'support_get_sn_info': instance.supportGetSnInfo,
      'support_get_spo2_switch_info': instance.supportGetSpo2SwitchInfo,
      'support_get_unit': instance.supportGetUnit,
      'support_get_v3_device_algorithm_version':
          instance.supportGetV3DeviceAlgorithmVersion,
      'support_get_v3_device_bt_connect_phone_model':
          instance.supportGetV3DeviceBtConnectPhoneModel,
      'support_get_walk_reminder': instance.supportGetWalkReminder,
      'support_hama_fit_move': instance.supportHamaFitMove,
      'support_jd': instance.supportJd,
      'support_loops_fit': instance.supportLoopsFit,
      'support_loudspeaker': instance.supportLoudspeaker,
      'support_lvgl_dial_frame': instance.supportLvglDialFrame,
      'support_make_watch_dial_deocde_jpg':
          instance.supportMakeWatchDialDeocdeJpg,
      'support_meituan': instance.supportMeituan,
      'support_morning_edition': instance.supportMorningEdition,
      'support_onekey_double_contact': instance.supportOnekeyDoubleContact,
      'support_over_find_phone': instance.supportOverFindPhone,
      'support_per_minute_one': instance.supportPerMinuteOne,
      'support_pinduoduo': instance.supportPinduoduo,
      'support_recover_time_and_vo2max': instance.supportRecoverTimeAndVo2max,
      'support_ryze_connect': instance.supportRyzeConnect,
      'support_second_sport_icon': instance.supportSecondSportIcon,
      'support_sedentary_tensile_habit_info':
          instance.supportSedentaryTensileHabitInfo,
      'support_send_bind_device_table': instance.supportSendBindDeviceTable,
      'support_send_encrypted_data_with_bind':
          instance.supportSendEncryptedDataWithBind,
      'support_send_gps_longitude_and_latitude':
          instance.supportSendGpsLongitudeAndLatitude,
      'support_send_original_size': instance.supportSendOriginalSize,
      'support_send_scales_model_map_table':
          instance.supportSendScalesModelMapTable,
      'support_set_call_quick_reply_on_off':
          instance.supportSetCallQuickReplyOnOff,
      'support_set_ecg_reminder': instance.supportSetEcgReminder,
      'support_set_eci_reminder': instance.supportSetEciReminder,
      'support_set_fast_mode_when_sync_config':
          instance.supportSetFastModeWhenSyncConfig,
      'support_set_fitness_guidance': instance.supportSetFitnessGuidance,
      'support_set_game_time_reminder': instance.supportSetGameTimeReminder,
      'support_set_historical_menstruation_use_version2':
          instance.supportSetHistoricalMenstruationUseVersion2,
      'support_set_list_style': instance.supportSetListStyle,
      'support_set_menstrual_reminder_on_off':
          instance.supportSetMenstrualReminderOnOff,
      'support_set_menu_list_type_measure':
          instance.supportSetMenuListTypeMeasure,
      'support_set_notice_message_state_use_version0x20':
          instance.supportSetNoticeMessageStateUseVersion0x20,
      'support_set_peripherals_info': instance.supportSetPeripheralsInfo,
      'support_set_screen_bright_interval':
          instance.supportSetScreenBrightInterval,
      'support_set_v3_heart_interval': instance.supportSetV3HeartInterval,
      'support_set_v3_weatcher_add_atmospheric_pressure':
          instance.supportSetV3WeatcherAddAtmosphericPressure,
      'support_set_v3_weatcher_add_snow_depth':
          instance.supportSetV3WeatcherAddSnowDepth,
      'support_set_v3_weatcher_add_snowfall':
          instance.supportSetV3WeatcherAddSnowfall,
      'support_set_v3_weatcher_send_struct_version_04':
          instance.supportSetV3WeatcherSendStructVersion04,
      'support_set_version_information': instance.supportSetVersionInformation,
      'support_set_voice_assistant_status':
          instance.supportSetVoiceAssistantStatus,
      'support_set_weather_history_future_aqi':
          instance.supportSetWeatherHistoryFutureAqi,
      'support_six_axis_sensor': instance.supportSixAxisSensor,
      'support_sleep_plan': instance.supportSleepPlan,
      'support_smart_competitor': instance.supportSmartCompetitor,
      'support_sync_activity_data_3d_distance_speed':
          instance.supportSyncActivityData3dDistanceSpeed,
      'support_sync_activity_data_altitude_info':
          instance.supportSyncActivityDataAltitudeInfo,
      'support_sync_activity_data_avg_slope':
          instance.supportSyncActivityDataAvgSlope,
      'support_sync_activity_get_anaerobic_training_effect':
          instance.supportSyncActivityGetAnaerobicTrainingEffect,
      'support_sync_activity_get_load': instance.supportSyncActivityGetLoad,
      'support_sync_activity_get_real_time_oxygen_consumption':
          instance.supportSyncActivityGetRealTimeOxygenConsumption,
      'support_sync_activity_get_real_time_physical_exertion':
          instance.supportSyncActivityGetRealTimePhysicalExertion,
      'support_sync_activity_get_rope_info':
          instance.supportSyncActivityGetRopeInfo,
      'support_sync_activity_get_running_power_info':
          instance.supportSyncActivityGetRunningPowerInfo,
      'support_sync_activity_type_treadmills_show_step':
          instance.supportSyncActivityTypeTreadmillsShowStep,
      'support_sync_ecg': instance.supportSyncEcg,
      'support_sync_health_hr_use_version_compatible':
          instance.supportSyncHealthHrUseVersionCompatible,
      'support_sync_health_swim_get_avg_frequency':
          instance.supportSyncHealthSwimGetAvgFrequency,
      'support_sync_health_swim_get_avg_speed':
          instance.supportSyncHealthSwimGetAvgSpeed,
      'support_taobao': instance.supportTaobao,
      'support_tas_smart': instance.supportTasSmart,
      'support_tmail': instance.supportTmail,
      'support_toutiao': instance.supportToutiao,
      'support_type_reset_device_bluetooth':
          instance.supportTypeResetDeviceBluetooth,
      'support_update_gps': instance.supportUpdateGps,
      'support_v2_disturb_all_day_switch':
          instance.supportV2DisturbAllDaySwitch,
      'support_v2_disturb_smart_switch': instance.supportV2DisturbSmartSwitch,
      'support_v2_get_deletable_meun_list':
          instance.supportV2GetDeletableMeunList,
      'support_v2_set_show_music_info_switch':
          instance.supportV2SetShowMusicInfoSwitch,
      'support_v3_sleep_health_sync_add_sleep_avg_hr':
          instance.supportV3SleepHealthSyncAddSleepAvgHr,
      'support_v3_sleep_health_sync_add_sleep_avg_respir_rate':
          instance.supportV3SleepHealthSyncAddSleepAvgRespirRate,
      'support_v3_sleep_health_sync_add_sleep_avg_spo2':
          instance.supportV3SleepHealthSyncAddSleepAvgSpo2,
      'support_voice_memo_operate': instance.supportVoiceMemoOperate,
      'support_walk_goal_steps': instance.supportWalkGoalSteps,
      'support_warm_up_before_running': instance.supportWarmUpBeforeRunning,
      'support_weibo': instance.supportWeibo,
      'suppport_ping_ios': instance.suppportPingIos,
      'surfing': instance.surfing,
      'surpport_new_retain_data': instance.surpportNewRetainData,
      'sync_v3_health_sleep_data_type_not_limit':
          instance.syncV3HealthSleepDataTypeNotLimit,
      'timeLine': instance.timeLine,
      'tipInfoContact': instance.tipInfoContact,
      'tipInfoContent': instance.tipInfoContent,
      'tipInfoNum': instance.tipInfoNum,
      'trail_running': instance.trailRunning,
      'ui_controll_sports': instance.uiControllSports,
      'unitSet': instance.unitSet,
      'upHandGestrue': instance.upHandGestrue,
      'v2_get_bt_addr': instance.v2GetBtAddr,
      'v2_send_calibration_threshold': instance.v2SendCalibrationThreshold,
      'v2_send_notice_call_time': instance.v2SendNoticeCallTime,
      'v2_send_set_smart_heart_time': instance.v2SendSetSmartHeartTime,
      'v2_set_alexa_operation_100brightness':
          instance.v2SetAlexaOperation100brightness,
      'v2_set_notice_missed_call': instance.v2SetNoticeMissedCall,
      'v2_set_notification_status': instance.v2SetNotificationStatus,
      'v2_set_stress_calibration': instance.v2SetStressCalibration,
      'v2_set_unread_app_reminder_03_EA': instance.v2SetUnreadAppReminder03Ea,
      'v2_support_add_night_level': instance.v2SupportAddNightLevel,
      'v2_support_adjust_night_turn_on_after_sunset':
          instance.v2SupportAdjustNightTurnOnAfterSunset,
      'v2_support_disable_func': instance.v2SupportDisableFunc,
      'v2_support_disturb_three_on_off': instance.v2SupportDisturbThreeOnOff,
      'v2_support_get_all_contact': instance.v2SupportGetAllContact,
      'v2_support_get_battery_mode': instance.v2SupportGetBatteryMode,
      'v2_support_notice_icon_information':
          instance.v2SupportNoticeIconInformation,
      'v2_support_set_bright_screen_time':
          instance.v2SupportSetBrightScreenTime,
      'v2_support_set_get_msg_all_switch': instance.v2SupportSetGetMsgAllSwitch,
      'v2_support_set_get_no_reminder_on_walk_reminder':
          instance.v2SupportSetGetNoReminderOnWalkReminder,
      'v2_support_set_no_reminder_on_drink_reminder':
          instance.v2SupportSetNoReminderOnDrinkReminder,
      'v2_support_set_step_data_type': instance.v2SupportSetStepDataType,
      'v2_support_set_time_zone_float': instance.v2SupportSetTimeZoneFloat,
      'v2_support_wallpaper_watch_face_only_time_color':
          instance.v2SupportWallpaperWatchFaceOnlyTimeColor,
      'v2_surport_bp_set_or_measurement': instance.v2SurportBpSetOrMeasurement,
      'v2_surport_calling_delay_three_seconds':
          instance.v2SurportCallingDelayThreeSeconds,
      'v2_surport_tran_flash_telink_log': instance.v2SurportTranFlashTelinkLog,
      'v2_v3_support_respiration_rate': instance.v2V3SupportRespirationRate,
      'v3_body_power': instance.v3BodyPower,
      'v3_fast_msg_data': instance.v3FastMsgData,
      'v3_function_table_33_1a': instance.v3FunctionTable331a,
      'v3_get_health_size_by_offset': instance.v3GetHealthSizeByOffset,
      'v3_heart_set_rate_mode_custom': instance.v3HeartSetRateModeCustom,
      'v3_oxygen_data_support_grade': instance.v3OxygenDataSupportGrade,
      'v3_schedule_reminder_phase_two': instance.v3ScheduleReminderPhaseTwo,
      'v3_set_get_alarm_specify_type': instance.v3SetGetAlarmSpecifyType,
      'v3_skateboard': instance.v3Skateboard,
      'v3_support_activity_sync_real_time':
          instance.v3SupportActivitySyncRealTime,
      'v3_support_data_tran_get_new_error_code':
          instance.v3SupportDataTranGetNewErrorCode,
      'v3_support_get_ble_beep': instance.v3SupportGetBleBeep,
      'v3_support_get_ble_music_info_version_0x10':
          instance.v3SupportGetBleMusicInfoVersion0x10,
      'v3_support_get_habit_data': instance.v3SupportGetHabitData,
      'v3_support_get_watch_size': instance.v3SupportGetWatchSize,
      'v3_support_per_bp': instance.v3SupportPerBp,
      'v3_support_set_contact_version_0x10':
          instance.v3SupportSetContactVersion0x10,
      'v3_support_set_get_emergency_connact':
          instance.v3SupportSetGetEmergencyConnact,
      'v3_support_set_hot_start_param': instance.v3SupportSetHotStartParam,
      'v3_support_set_repeat_type_on_schedule_reminder':
          instance.v3SupportSetRepeatTypeOnScheduleReminder,
      'v3_support_set_repeat_week_type_on_schedule_reminder':
          instance.v3SupportSetRepeatWeekTypeOnScheduleReminder,
      'v3_support_set_v3_add_48_hour_weather_data':
          instance.v3SupportSetV3Add48HourWeatherData,
      'v3_support_set_v3_add_48_hour_weather_data_or_cityname':
          instance.v3SupportSetV3Add48HourWeatherDataOrCityname,
      'v3_support_set_v3_weatcher_add_air_grade':
          instance.v3SupportSetV3WeatcherAddAirGrade,
      'v3_support_set_v3_weatcher_add_sunrise':
          instance.v3SupportSetV3WeatcherAddSunrise,
      'v3_support_sports_plan': instance.v3SupportSportsPlan,
      'v3_surport_sport_medium_icon': instance.v3SurportSportMediumIcon,
      'versionInfo': instance.versionInfo,
      'walk_reminder': instance.walkReminder,
      'weather': instance.weather,
      'weather_city': instance.weatherCity,
      'wechatSport': instance.wechatSport,
      'whatsapp': instance.whatsapp,
      'zumba': instance.zumba,
    };
