// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.native_channel.pigeon_generate.api_tools

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ApiTools {
  /** 获取appName， 返回形如："VeryFit" */
  fun getAppName(): String
  /** 获取当前时区， 返回形如："Asia/Shanghai" */
  fun getCurrentTimeZone(): String
  /** 获取Document目录路径, 返回形如：/xx/.../ */
  fun getDocumentPath(): String?
  /**
   * 获取平台设备信息, 返回：
   * ```dart
   * {
   *   "model": "String",          手机型号
   *   "systemVersion": "String",  系统版本
   *   "isJailbroken": false       是否越狱
   * }
   * ```
   */
  fun getPlatformDeviceInfo(): Map<Any, Any?>?
  /**
   * 生成自定义表盘文件，数据采用大端模式 （杰里平台）
   *
   * [dialFilePath] 表盘文件保存路径
   * [bgPath] 背景图片路径
   * [previewPath] 预览图图片路径，覆盖在背景图上方，透明只带时间组件
   * [color] 字体颜色
   * [baseBinPath] 基础bin包文件路径
   */
  fun makeJieLiDialFile(dialFilePath: String, bgPath: String, previewPath: String, color: Long, baseBinPath: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by ApiTools. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `ApiTools` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: ApiTools?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ApiTools.getAppName", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getAppName())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ApiTools.getCurrentTimeZone", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getCurrentTimeZone())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ApiTools.getDocumentPath", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getDocumentPath())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ApiTools.getPlatformDeviceInfo", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getPlatformDeviceInfo())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ApiTools.makeJieLiDialFile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dialFilePathArg = args[0] as String
            val bgPathArg = args[1] as String
            val previewPathArg = args[2] as String
            val colorArg = args[3].let { if (it is Int) it.toLong() else it as Long }
            val baseBinPathArg = args[4] as String
            api.makeJieLiDialFile(dialFilePathArg, bgPathArg, previewPathArg, colorArg, baseBinPathArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class ToolsDelegate(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by ToolsDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
  }
  /** 获取Native日志， 返回形如："2021-06-01 10:00:00.000000000 +0800" */
  fun getNativeLog(msgArg: String, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_channel.ToolsDelegate.getNativeLog", codec)
    channel.send(listOf(msgArg)) {
      callback()
    }
  }
}
