name: protocol_alexa
description: ido protocol_alexa lib (private)
version: 2.0.9
homepage:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.3.1'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.0.1
  dio: ^5.1.0
  crypto: ^3.0.2
  rxdart: ^0.27.5
  http_parser: ^4.0.2
  uuid: ^3.0.7

  get_storage_lite:
    path: ../plugins/get_storage_lite
  protocol_lib:
    path: ../protocol_lib/
  alexa_net:
    path: ../plugins/alexa_net
  ido_logger:
    path: ../plugins/ido_logger/
  native_channel:
    path: ../plugins/native_channel/
  json_annotation: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  retrofit_generator: ^6.0.0+1
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: 6.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
