// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_bind

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Bind(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Bind. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
  }
  /** 绑定状态 */
  fun isBinded(callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.isBinded", codec)
    channel.send(null) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 是否在绑定中 (绑定中，切换设备将受到限制） */
  fun isBinding(callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.isBinding", codec)
    channel.send(null) {
      val result = it as Boolean
      callback(result)
    }
  }
  /**
   * 0 绑定失败 1绑定成功 2已经绑定 3需要授权码绑定 4拒绝绑定 5绑定错误设备 6授权码校验失败
   * 7取消绑定 8绑定失败（获取功能表失败) 9绑定失败（获取设备信息失败)
   * 10绑定超时（支持该功能的设备专用）
   * 11新账户绑定，用户确定删除设备数据（支持该功能的设备专用）
   * 12新账户绑定，用户不删除设备数据，绑定失败（支持该功能的设备专用）
   * 13新账户绑定，用户不选择，设备超时（支持该功能的设备专用）
   * 14设备同意配对(绑定)请求，等待APP下发配对结果（支持该功能的设备专用）
   */
  fun bind(osVersionArg: Long, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.bind", codec)
    channel.send(listOf(osVersionArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  fun cancelBind(callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.cancelBind", codec)
    channel.send(null) {
      callback()
    }
  }
  /**
   * APP下发绑定结果(仅限需要app确认绑定结果的设备使用)
   * ```
   * 注：当startBind(...) 返回BindStatus.needAuthByApp 时，APP需要发送
   * CmdEvtType.sendBindResult指令，在调用成功后，再调用appMarkBindResult方法
   * ```
   */
  fun appMarkBindResult(successArg: Boolean, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.appMarkBindResult", codec)
    channel.send(listOf(successArg)) {
      callback()
    }
  }
  fun unbind(macAddressArg: String, isForceRemoveArg: Boolean, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.unbind", codec)
    channel.send(listOf(macAddressArg, isForceRemoveArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  fun setAuthCode(codeArg: String, osVersionArg: Long, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bind.setAuthCode", codec)
    channel.send(listOf(codeArg, osVersionArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
}
