// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_bluetooth

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 连接状态：
 * 断开连接，
 * 连接中，
 * 已连接，
 * 断开连接中
 */
internal enum class DeviceStateType(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3);

  companion object {
    fun ofRaw(raw: Int): DeviceStateType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 蓝牙状态：
 * 未知，
 * 系统服务重启中，
 * 不支持，
 * 未授权，
 * 蓝牙关闭，
 * 蓝牙打开
 */
internal enum class BluetoothStateType(val raw: Int) {
  UNKNOWN(0),
  RESETTING(1),
  UNSUPPORTED(2),
  UNAUTHORIZED(3),
  POWEREDOFF(4),
  POWEREDON(5);

  companion object {
    fun ofRaw(raw: Int): BluetoothStateType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 扫描状态
 * 扫描中
 * 扫描结束
 * 找到设备（android）
 */
internal enum class BluetoothScanType(val raw: Int) {
  SCANNING(0),
  STOP(1),
  FIND(2);

  companion object {
    fun ofRaw(raw: Int): BluetoothScanType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 连接错误
 * 无状态
 * UUID或Mac地址异常
 * 蓝牙关闭
 * 主动断开连接
 * 连接失败
 * 连接超时
 * 发现服务失败
 * 发现特征失败
 * 配对异常
 * 获取基本信息失败
 * 设备已绑定并且不支持重复绑定
 * app 绑定的设备被重置了
 * 连接被终止，比如在 ota 中，不需要执行重连了
 */
internal enum class ConnectErrorType(val raw: Int) {
  NONE(0),
  ABNORMALUUIDMACADDRESS(1),
  BLUETOOTHOFF(2),
  CONNECTCANCEL(3),
  FAIL(4),
  TIMEOUT(5),
  SERVICEFAIL(6),
  CHARACTERISTICSFAIL(7),
  PAIRFAIL(8),
  INFORMATIONFAIL(9),
  CANCELBYUSER(10),
  DEVICEALREADYBINDANDNOTSUPPORTREBIND(11),
  DEVICEHASBEENRESET(12),
  CONNECTTERMINATED(13);

  companion object {
    fun ofRaw(raw: Int): ConnectErrorType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 写数据状态
 * 有响应
 * 无响应
 * 错误
 */
internal enum class WriteType(val raw: Int) {
  WITHRESPONSE(0),
  WITHOUTRESPONSE(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): WriteType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * spp:
 * 开始连接
 * 连接成功
 * 连接失败
 * 断链
 */
internal enum class SPPStateType(val raw: Int) {
  ONSTART(0),
  ONSUCCESS(1),
  ONFAIL(2),
  ONBREAK(3);

  companion object {
    fun ofRaw(raw: Int): SPPStateType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class DeviceModel (
  /** rssi */
  val rssi: Long? = null,
  /** 设备名称 */
  val name: String? = null,
  /** 设备状态 */
  val state: DeviceStateType? = null,
  /**uuid */
  val uuid: String? = null,
  /**mac address */
  val macAddress: String? = null,
  /** ota mac address */
  val otaMacAddress: String? = null,
  /** bt mac address */
  val btMacAddress: String? = null,
  /** 设备ID */
  val deviceId: Long? = null,
  /** 设备类型 0:无效 1: 手表 2: 手环 */
  val deviceType: Long? = null,
  /** 是否ota模式 */
  val isOta: Boolean? = null,
  /**是否泰凌微ota */
  val isTlwOta: Boolean? = null,
  /**bt版本号 */
  val bltVersion: Long? = null,
  /**配对状态（Android） */
  val isPair: Boolean? = null,
  /**平台 */
  val platform: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeviceModel {
      val rssi = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val name = list[1] as String?
      val state: DeviceStateType? = (list[2] as Int?)?.let {
        DeviceStateType.ofRaw(it)
      }
      val uuid = list[3] as String?
      val macAddress = list[4] as String?
      val otaMacAddress = list[5] as String?
      val btMacAddress = list[6] as String?
      val deviceId = list[7].let { if (it is Int) it.toLong() else it as Long? }
      val deviceType = list[8].let { if (it is Int) it.toLong() else it as Long? }
      val isOta = list[9] as Boolean?
      val isTlwOta = list[10] as Boolean?
      val bltVersion = list[11].let { if (it is Int) it.toLong() else it as Long? }
      val isPair = list[12] as Boolean?
      val platform = list[13].let { if (it is Int) it.toLong() else it as Long? }
      return DeviceModel(rssi, name, state, uuid, macAddress, otaMacAddress, btMacAddress, deviceId, deviceType, isOta, isTlwOta, bltVersion, isPair, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      rssi,
      name,
      state?.raw,
      uuid,
      macAddress,
      otaMacAddress,
      btMacAddress,
      deviceId,
      deviceType,
      isOta,
      isTlwOta,
      bltVersion,
      isPair,
      platform,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class BluetoothStateModel (
  val type: BluetoothStateType? = null,
  val scanType: BluetoothScanType? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BluetoothStateModel {
      val type: BluetoothStateType? = (list[0] as Int?)?.let {
        BluetoothStateType.ofRaw(it)
      }
      val scanType: BluetoothScanType? = (list[1] as Int?)?.let {
        BluetoothScanType.ofRaw(it)
      }
      return BluetoothStateModel(type, scanType)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type?.raw,
      scanType?.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class DeviceStateModel (
  val uuid: String? = null,
  val macAddress: String? = null,
  val state: DeviceStateType? = null,
  val errorState: ConnectErrorType? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeviceStateModel {
      val uuid = list[0] as String?
      val macAddress = list[1] as String?
      val state: DeviceStateType? = (list[2] as Int?)?.let {
        DeviceStateType.ofRaw(it)
      }
      val errorState: ConnectErrorType? = (list[3] as Int?)?.let {
        ConnectErrorType.ofRaw(it)
      }
      return DeviceStateModel(uuid, macAddress, state, errorState)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      uuid,
      macAddress,
      state?.raw,
      errorState?.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class WriteStateModel (
  /** 写入状态是否成功 */
  val state: Boolean? = null,
  /** uuid */
  val uuid: String? = null,
  /** mac address */
  val macAddress: String? = null,
  /** 写入类型 */
  val type: WriteType? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): WriteStateModel {
      val state = list[0] as Boolean?
      val uuid = list[1] as String?
      val macAddress = list[2] as String?
      val type: WriteType? = (list[3] as Int?)?.let {
        WriteType.ofRaw(it)
      }
      return WriteStateModel(state, uuid, macAddress, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      state,
      uuid,
      macAddress,
      type?.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class ReceiveData (
  /** 蓝牙字节数据 */
  val data: ByteArray? = null,
  /** uuid */
  val uuid: String? = null,
  /** mac address */
  val macAddress: String? = null,
  /** spp */
  val spp: Boolean? = null,
  /** 0 爱都, 1 恒玄, 2 VC */
  val platform: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ReceiveData {
      val data = list[0] as ByteArray?
      val uuid = list[1] as String?
      val macAddress = list[2] as String?
      val spp = list[3] as Boolean?
      val platform = list[4].let { if (it is Int) it.toLong() else it as Long? }
      return ReceiveData(data, uuid, macAddress, spp, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      data,
      uuid,
      macAddress,
      spp,
      platform,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class SPPStateModel (
  val type: SPPStateType? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): SPPStateModel {
      val type: SPPStateType? = (list[0] as Int?)?.let {
        SPPStateType.ofRaw(it)
      }
      return SPPStateModel(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type?.raw,
    )
  }
}

/**
 * 设备升级
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
internal data class DfuConfig (
  /** ota文件包路径 */
  val filePath: String? = null,
  /**设备的uuid, iOS使用 */
  val uuid: String? = null,
  /**设备的ble地址 安卓使用 */
  val macAddress: String? = null,
  /**设备的id */
  val deviceId: String? = null,
  /**平台，默认为nordic，目前只支持nordic */
  val platform: Long? = null,
  /**设备是否支持配对，根据功能表V3_dev_support_pair_each_connect  安卓使用 */
  val isDeviceSupportPairedWithPhoneSystem: Boolean? = null,
  /**每次接受到包数，可不填 */
  val prn: Long? = null,
  /**在重试过程中，如果多次升级失败，是否需要重启蓝牙 */
  val isNeedReOpenBluetoothSwitchIfFailed: Boolean? = null,
  /**最大重试次数 */
  val maxRetryTime: Long? = null,
  /**RTK平台的OTA，在升级之前是否需要授权 */
  val isNeedAuth: Boolean? = null,
  /**RTK平台的OTA，模式 */
  val otaWorkMode: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DfuConfig {
      val filePath = list[0] as String?
      val uuid = list[1] as String?
      val macAddress = list[2] as String?
      val deviceId = list[3] as String?
      val platform = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val isDeviceSupportPairedWithPhoneSystem = list[5] as Boolean?
      val prn = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val isNeedReOpenBluetoothSwitchIfFailed = list[7] as Boolean?
      val maxRetryTime = list[8].let { if (it is Int) it.toLong() else it as Long? }
      val isNeedAuth = list[9] as Boolean?
      val otaWorkMode = list[10].let { if (it is Int) it.toLong() else it as Long? }
      return DfuConfig(filePath, uuid, macAddress, deviceId, platform, isDeviceSupportPairedWithPhoneSystem, prn, isNeedReOpenBluetoothSwitchIfFailed, maxRetryTime, isNeedAuth, otaWorkMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      filePath,
      uuid,
      macAddress,
      deviceId,
      platform,
      isDeviceSupportPairedWithPhoneSystem,
      prn,
      isNeedReOpenBluetoothSwitchIfFailed,
      maxRetryTime,
      isNeedAuth,
      otaWorkMode,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object BluetoothDelegateCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BluetoothStateModel.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceModel.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceStateModel.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReceiveData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SPPStateModel.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WriteStateModel.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BluetoothStateModel -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is DeviceModel -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DeviceStateModel -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ReceiveData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SPPStateModel -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WriteStateModel -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
internal interface BluetoothDelegate {
  /** 发送数据状态 */
  fun writeState(state: WriteStateModel)
  /** 收到数据 */
  fun receiveData(data: ReceiveData)
  /** 搜索设备结果 */
  fun scanResult(list: List<DeviceModel>?)
  /** 蓝牙状态 */
  fun bluetoothState(state: BluetoothStateModel)
  /** 设备状态状态 */
  fun deviceState(state: DeviceStateModel)
  /** spp状态 */
  fun stateSPP(state: SPPStateModel)
  /** spp文件写完成 */
  fun writeSPPCompleteState(btMacAddress: String)
  /** 监听dfu完成状态 */
  fun dfuComplete()
  /** 监听dfu过程的错误 */
  fun dfuError(error: String)
  /**
   * 监听升级进度
   * 0-100
   */
  fun dfuProgress(progress: Long)
  /** 监听当前设备 */
  fun changeCurrentDevice(device: DeviceModel)
  /** 监听当前设备属性变更（目前针对btMacAddress 内部使用） */
  fun onCurrentDeviceAttrValChange(device: DeviceModel)
  /** bt状态 */
  fun stateBt(isPair: Boolean)

  companion object {
    /** The codec used by BluetoothDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      BluetoothDelegateCodec
    }
    /** Sets up an instance of `BluetoothDelegate` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: BluetoothDelegate?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.writeState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as WriteStateModel
            var wrapped: List<Any?>
            try {
              api.writeState(stateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.receiveData", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as ReceiveData
            var wrapped: List<Any?>
            try {
              api.receiveData(dataArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.scanResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val listArg = args[0] as List<DeviceModel>?
            var wrapped: List<Any?>
            try {
              api.scanResult(listArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.bluetoothState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as BluetoothStateModel
            var wrapped: List<Any?>
            try {
              api.bluetoothState(stateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.deviceState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as DeviceStateModel
            var wrapped: List<Any?>
            try {
              api.deviceState(stateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.stateSPP", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as SPPStateModel
            var wrapped: List<Any?>
            try {
              api.stateSPP(stateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.writeSPPCompleteState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val btMacAddressArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.writeSPPCompleteState(btMacAddressArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuComplete", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.dfuComplete()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuError", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val errorArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.dfuError(errorArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuProgress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val progressArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.dfuProgress(progressArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.changeCurrentDevice", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as DeviceModel
            var wrapped: List<Any?>
            try {
              api.changeCurrentDevice(deviceArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.onCurrentDeviceAttrValChange", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as DeviceModel
            var wrapped: List<Any?>
            try {
              api.onCurrentDeviceAttrValChange(deviceArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.BluetoothDelegate.stateBt", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isPairArg = args[0] as Boolean
            var wrapped: List<Any?>
            try {
              api.stateBt(isPairArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object BluetoothCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BluetoothStateModel.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceModel.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceModel.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceStateModel.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DfuConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WriteStateModel.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BluetoothStateModel -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is DeviceModel -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DeviceModel -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DeviceStateModel -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DfuConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WriteStateModel -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Bluetooth(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Bluetooth. */
    val codec: MessageCodec<Any?> by lazy {
      BluetoothCodec
    }
  }
  /** 最后一次连接设备 */
  fun currentDevice(callback: (DeviceModel?) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.currentDevice", codec)
    channel.send(null) {
      val result = it as DeviceModel?
      callback(result)
    }
  }
  /**
   * 注册,程序开始运行调用
   * heartPingSecond:心跳包间隔(ios)
   * outputToConsole：控制台输出日志
   */
  fun register(heartPingSecondArg: Long, outputToConsoleArg: Boolean, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.register", codec)
    channel.send(listOf(heartPingSecondArg, outputToConsoleArg)) {
      callback()
    }
  }
  /**
   * 开始搜索
   * macAddress（Android）:根据Mac地址搜索
   * 返回指定搜索的设备，如未指定返回null
   */
  fun startScan(macAddressArg: String?, callback: (List<DeviceModel?>?) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.startScan", codec)
    channel.send(listOf(macAddressArg)) {
      val result = it as List<DeviceModel?>?
      callback(result)
    }
  }
  /**
   * 搜索筛选条件
   * deviceName: 只搜索deviceName的设备
   * deviceID：只搜索deviceID的设备
   * macAddress：只搜索macAddress的设备
   * uuid：只搜索uuid的设备
   */
  fun scanFilter(deviceNameArg: List<String>?, deviceIDArg: List<Long>?, macAddressArg: List<String>?, uuidArg: List<String>?, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.scanFilter", codec)
    channel.send(listOf(deviceNameArg, deviceIDArg, macAddressArg, uuidArg)) {
      callback()
    }
  }
  /** 停止搜索 */
  fun stopScan(callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.stopScan", codec)
    channel.send(null) {
      callback()
    }
  }
  /**
   * 连接
   * device: Mac地址必传，iOS要带上uuid，最好使用搜索返回的对象
   */
  fun connect(deviceArg: DeviceModel?, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.connect", codec)
    channel.send(listOf(deviceArg)) {
      callback()
    }
  }
  /** 使用这个重连设备 */
  fun autoConnect(deviceArg: DeviceModel?, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.autoConnect", codec)
    channel.send(listOf(deviceArg)) {
      callback()
    }
  }
  /** 取消连接 */
  fun cancelConnect(macAddressArg: String?, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.cancelConnect", codec)
    channel.send(listOf(macAddressArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 获取蓝牙状态 */
  fun getBluetoothState(callback: (BluetoothStateModel) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.getBluetoothState", codec)
    channel.send(null) {
      val result = it as BluetoothStateModel
      callback(result)
    }
  }
  /** 获取设备连接状态 */
  fun getDeviceState(deviceArg: DeviceModel?, callback: (DeviceStateModel) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.getDeviceState", codec)
    channel.send(listOf(deviceArg)) {
      val result = it as DeviceStateModel
      callback(result)
    }
  }
  /**
   * 发送数据
   * data:数据
   * device: 发送数据的设备
   * type:0 BLE数据, 1 SPP数据
   * platform: 0 爱都, 1 恒玄, 2 VC
   */
  fun writeData(dataArg: ByteArray, deviceArg: DeviceModel?, typeArg: Long, platformArg: Long, callback: (WriteStateModel) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.writeData", codec)
    channel.send(listOf(dataArg, deviceArg, typeArg, platformArg)) {
      val result = it as WriteStateModel
      callback(result)
    }
  }
  /** bt配对（android） */
  fun setBtPair(deviceArg: DeviceModel, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.setBtPair", codec)
    channel.send(listOf(deviceArg)) {
      callback()
    }
  }
  /** 取消配对（android） */
  fun cancelPair(deviceArg: DeviceModel?, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.cancelPair", codec)
    channel.send(listOf(deviceArg)) {
      callback()
    }
  }
  /** 连接SPP */
  fun connectSPP(btMacAddressArg: String, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.connectSPP", codec)
    channel.send(listOf(btMacAddressArg)) {
      callback()
    }
  }
  /** 断开SPP */
  fun disconnectSPP(btMacAddressArg: String, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.disconnectSPP", codec)
    channel.send(listOf(btMacAddressArg)) {
      callback()
    }
  }
  /**发起dfu升级 */
  fun startNordicDFU(configArg: DfuConfig, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.startNordicDFU", codec)
    channel.send(listOf(configArg)) {
      callback()
    }
  }
  /** 日志路径 */
  fun logPath(callback: (String?) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Bluetooth.logPath", codec)
    channel.send(null) {
      val result = it as String?
      callback(result)
    }
  }
}
