// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_cmd

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
internal data class CancelToken (
  val token: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): CancelToken {
      val token = list[0] as String?
      return CancelToken(token)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      token,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
internal data class Response (
  val code: Long? = null,
  val json: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): Response {
      val code = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val json = list[1] as String?
      return Response(code, json)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      code,
      json,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object CmdCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CancelToken.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CancelToken.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Response.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CancelToken -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is CancelToken -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Response -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Cmd(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Cmd. */
    val codec: MessageCodec<Any?> by lazy {
      CmdCodec
    }
  }
  /**
   * 基础指令调用
   *
   * priority 优先级 null / 0: low， 1: normal， 2: high，3： veryHigh
   */
  fun send(evtTypeArg: Long, jsonArg: String?, cancelTokenArg: CancelToken?, priorityArg: Long?, callback: (Response) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Cmd.send", codec)
    channel.send(listOf(evtTypeArg, jsonArg, cancelTokenArg, priorityArg)) {
      val result = it as Response
      callback(result)
    }
  }
  /** 根据token标识在字典中匹配实现 */
  fun cancelSend(cancelTokenArg: CancelToken, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Cmd.cancelSend", codec)
    channel.send(listOf(cancelTokenArg)) {
      callback()
    }
  }
}
