// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_device_log

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
internal interface DeviceLogDelegate {
  /** 监听日志获取状态 */
  fun listenLogStatus(status: Boolean)
  /** 监听日志目录地址 */
  fun listenLogDirPath(dirPath: String)
  /** 日志整体进度 0-100 */
  fun callbackLogProgress(progress: Double)

  companion object {
    /** The codec used by DeviceLogDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `DeviceLogDelegate` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceLogDelegate?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogStatus", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val statusArg = args[0] as Boolean
            var wrapped: List<Any?>
            try {
              api.listenLogStatus(statusArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogDirPath", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dirPathArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.listenLogDirPath(dirPathArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.callbackLogProgress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val progressArg = args[0] as Double
            var wrapped: List<Any?>
            try {
              api.callbackLogProgress(progressArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class DeviceLog(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by DeviceLog. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
  }
  /** 判断日志状态 */
  fun getLogIng(callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLog.getLogIng", codec)
    channel.send(null) {
      val result = it as Boolean
      callback(result)
    }
  }
  /**
   * 获取所有日志目录地址，每个日志目录下存放以时间戳命名的文件
   * flash 日志目录 =>  Flash
   * 电池日志目录 => Battery
   * 过热日志目录 => Heat
   * 旧的重启日志目录 => Reboot
   */
  fun logDirPath(callback: (String) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLog.logDirPath", codec)
    channel.send(null) {
      val result = it as String
      callback(result)
    }
  }
  /**
   * 开始获取日志
   * type 1: 旧的重启日志 2: 通用日志 3: 复位日志
   * 4: 硬件日志 5: 算法日志 6: 新重启日志 7:电池日志 8: 过热日志
   */
  fun startGet(typesArg: List<Long>, timeOutArg: Long, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLog.startGet", codec)
    channel.send(listOf(typesArg, timeOutArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 取消 */
  fun cancel(callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceLog.cancel", codec)
    channel.send(null) {
      callback()
    }
  }
}
