// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_device

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 设备信息
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
internal data class DeviceInfo (
  /** 设备模式 0：运动模式，1：睡眠模式 */
  val deviceMode: Long? = null,
  /** 电量状态 0:正常, 1:正在充电, 2:充满, 3:电量低 */
  val battStatus: Long? = null,
  /** 电量级别 0～100 */
  val battLevel: Long? = null,
  /** 是否重启 0:未重启 1:重启 */
  val rebootFlag: Long? = null,
  /** 绑定状态 0:未绑定 1:已绑定 */
  val bindState: Long? = null,
  /**
   * 绑定类型 0:默认 1:单击 2:长按 3:屏幕点击 横向确认和取消,确认在左边 4:屏幕点击 横向确认和取消,确认在右边
   * 5:屏幕点击 竖向确认和取消,确认在上边 6:屏幕点击 竖向确认和取消,确认在下边 7:点击(右边一个按键)
   */
  val bindType: Long? = null,
  /** 绑定超时 最长为15秒,0表示不超时 */
  val bindTimeout: Long? = null,
  /**
   * 设备平台 0:nordic, 10:realtek 8762x, 20:cypress psoc6, 30:Apollo3, 40:汇顶, 50:nordic+泰凌微,
   * 60:泰凌微+5340+no nand flash, 70:汇顶+富瑞坤, 80:5340
   */
  val platform: Long? = null,
  /** 设备形状类型 0：无效；1：圆形；2：方形的； 3：椭圆 */
  val deviceShapeType: Long? = null,
  /** 设备类型 0：无效；1：手环；2：手表 */
  val deviceType: Long? = null,
  /** 自定义表盘主版本 从1开始 0:不支持对应的自定义表盘功能 */
  val dialMainVersion: Long? = null,
  /** 固件绑定时候显示勾ui界面 0:不需要 1:需要 */
  val showBindChoiceUi: Long? = null,
  /** 设备id */
  val deviceId: Long? = null,
  /** 设备固件主版本号 */
  val firmwareVersion: Long? = null,
  /** 设备SN */
  val sn: String? = null,
  /** BtName */
  val btName: String? = null,
  /** GPS芯片平台 0：无效 1：索尼 sony 2：洛达 Airoh 3：芯与物 icoe */
  val gpsPlatform: Long? = null,
  /**
   * （SDK 内部专用， 外部慎用！！！）
   * 当前设备mac地址 - 无冒号
   */
  val macAddress: String? = null,
  /**
   * （SDK 内部专用， 外部慎用！！！）
   * 当前设备mac地址 - 带冒号
   */
  val macAddressFull: String? = null,
  /**
   * （SDK 内部专用， 外部慎用！！！）
   * 注意：该名称是由调用 libManager.markConnectedDevice(...)传入，sdk不会主去刷新该值
   * 需要获取最新值可以使用 CmdEvtType.getDeviceName 指令
   */
  val deviceName: String? = null,
  /**
   * （SDK 内部专用， 外部慎用！！！）
   * OTA模式
   */
  val otaMode: Boolean? = null,
  /**
   * （（SDK 内部专用， 外部慎用！！！）
   * UUID ios专用
   */
  val uuid: String? = null,
  /** BT macAddress - 带冒号 */
  val macAddressBt: String? = null,
  /** 固件版本version1 */
  val fwVersion1: Long? = null,
  /** 固件版本version2 */
  val fwVersion2: Long? = null,
  /** 固件版本version3 */
  val fwVersion3: Long? = null,
  /** BT版本生效标志位 0：无效 1：说明固件有对应的BT固件 */
  val fwBtFlag: Long? = null,
  /** BT的版本version1 */
  val fwBtVersion1: Long? = null,
  /** BT的版本version2 */
  val fwBtVersion2: Long? = null,
  /** BT的版本version3 */
  val fwBtVersion3: Long? = null,
  /** BT的所需要匹配的版本version1 */
  val fwBtMatchVersion1: Long? = null,
  /** BT的所需要匹配的版本version2 */
  val fwBtMatchVersion2: Long? = null,
  /** BT的所需要匹配的版本version3 */
  val fwBtMatchVersion3: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeviceInfo {
      val deviceMode = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val battStatus = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val battLevel = list[2].let { if (it is Int) it.toLong() else it as Long? }
      val rebootFlag = list[3].let { if (it is Int) it.toLong() else it as Long? }
      val bindState = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val bindType = list[5].let { if (it is Int) it.toLong() else it as Long? }
      val bindTimeout = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val platform = list[7].let { if (it is Int) it.toLong() else it as Long? }
      val deviceShapeType = list[8].let { if (it is Int) it.toLong() else it as Long? }
      val deviceType = list[9].let { if (it is Int) it.toLong() else it as Long? }
      val dialMainVersion = list[10].let { if (it is Int) it.toLong() else it as Long? }
      val showBindChoiceUi = list[11].let { if (it is Int) it.toLong() else it as Long? }
      val deviceId = list[12].let { if (it is Int) it.toLong() else it as Long? }
      val firmwareVersion = list[13].let { if (it is Int) it.toLong() else it as Long? }
      val sn = list[14] as String?
      val btName = list[15] as String?
      val gpsPlatform = list[16].let { if (it is Int) it.toLong() else it as Long? }
      val macAddress = list[17] as String?
      val macAddressFull = list[18] as String?
      val deviceName = list[19] as String?
      val otaMode = list[20] as Boolean?
      val uuid = list[21] as String?
      val macAddressBt = list[22] as String?
      val fwVersion1 = list[23].let { if (it is Int) it.toLong() else it as Long? }
      val fwVersion2 = list[24].let { if (it is Int) it.toLong() else it as Long? }
      val fwVersion3 = list[25].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtFlag = list[26].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtVersion1 = list[27].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtVersion2 = list[28].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtVersion3 = list[29].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtMatchVersion1 = list[30].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtMatchVersion2 = list[31].let { if (it is Int) it.toLong() else it as Long? }
      val fwBtMatchVersion3 = list[32].let { if (it is Int) it.toLong() else it as Long? }
      return DeviceInfo(deviceMode, battStatus, battLevel, rebootFlag, bindState, bindType, bindTimeout, platform, deviceShapeType, deviceType, dialMainVersion, showBindChoiceUi, deviceId, firmwareVersion, sn, btName, gpsPlatform, macAddress, macAddressFull, deviceName, otaMode, uuid, macAddressBt, fwVersion1, fwVersion2, fwVersion3, fwBtFlag, fwBtVersion1, fwBtVersion2, fwBtVersion3, fwBtMatchVersion1, fwBtMatchVersion2, fwBtMatchVersion3)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      deviceMode,
      battStatus,
      battLevel,
      rebootFlag,
      bindState,
      bindType,
      bindTimeout,
      platform,
      deviceShapeType,
      deviceType,
      dialMainVersion,
      showBindChoiceUi,
      deviceId,
      firmwareVersion,
      sn,
      btName,
      gpsPlatform,
      macAddress,
      macAddressFull,
      deviceName,
      otaMode,
      uuid,
      macAddressBt,
      fwVersion1,
      fwVersion2,
      fwVersion3,
      fwBtFlag,
      fwBtVersion1,
      fwBtVersion2,
      fwBtVersion3,
      fwBtMatchVersion1,
      fwBtMatchVersion2,
      fwBtMatchVersion3,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object DeviceDelegateCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DeviceInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
internal interface DeviceDelegate {
  /** 设备信息变更通知 */
  fun listenDeviceChanged(deviceInfo: DeviceInfo)
  /** 绑定时获取的设备信息通知(绑定专用) */
  fun listenDeviceOnBind(deviceInfo: DeviceInfo)

  companion object {
    /** The codec used by DeviceDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceDelegateCodec
    }
    /** Sets up an instance of `DeviceDelegate` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceDelegate?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceDelegate.listenDeviceChanged", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceInfoArg = args[0] as DeviceInfo
            var wrapped: List<Any?>
            try {
              api.listenDeviceChanged(deviceInfoArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.DeviceDelegate.listenDeviceOnBind", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceInfoArg = args[0] as DeviceInfo
            var wrapped: List<Any?>
            try {
              api.listenDeviceOnBind(deviceInfoArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Device(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Device. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
  }
  /** 刷新设备信息（SDK内部使用） */
  fun refreshDeviceInfo(forcedArg: Boolean, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfo", codec)
    channel.send(listOf(forcedArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 刷新设备信息 绑定前使用（SDK内部使用） */
  fun refreshDeviceInfoBeforeBind(forcedArg: Boolean, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfoBeforeBind", codec)
    channel.send(listOf(forcedArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 刷新设备三级版本（SDK内部使用） */
  fun refreshFirmwareVersion(forcedArg: Boolean, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.refreshFirmwareVersion", codec)
    channel.send(listOf(forcedArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 刷新设备扩展信息（SDK内部使用） */
  fun refreshDeviceExtInfo(callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.refreshDeviceExtInfo", codec)
    channel.send(null) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 设置设备BT MacAddress（SDK内部使用） */
  fun setDeviceBtMacAddress(macAddressBtArg: String, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.setDeviceBtMacAddress", codec)
    channel.send(listOf(macAddressBtArg)) {
      callback()
    }
  }
  /** 清理数据 (SDK内部使用) */
  fun cleanDataOnMemory(callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Device.cleanDataOnMemory", codec)
    channel.send(null) {
      callback()
    }
  }
}
