// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_func_table

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
internal interface FuncTableDelegate {
  /** 功能表变更通知 */
  fun listenFuncTableChanged(funcTableJson: String)
  /** 绑定时获取的功能表通知(绑定专用) */
  fun listenFuncTableOnBind(funcTableJson: String)

  companion object {
    /** The codec used by FuncTableDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `FuncTableDelegate` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: FuncTableDelegate?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableChanged", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val funcTableJsonArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.listenFuncTableChanged(funcTableJsonArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableOnBind", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val funcTableJsonArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.listenFuncTableOnBind(funcTableJsonArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class FuncTable(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by FuncTable. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
  }
  /** 加载指定设备功能表 返回json */
  fun loadFuncTableByDisk(macAddressArg: String, callback: (String) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.FuncTable.loadFuncTableByDisk", codec)
    channel.send(listOf(macAddressArg)) {
      val result = it as String
      callback(result)
    }
  }
  /** 导出功能表 返回json文件绝对路径 */
  fun exportFuncTableFile(macAddressArg: String, callback: (String) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.FuncTable.exportFuncTableFile", codec)
    channel.send(listOf(macAddressArg)) {
      val result = it as String
      callback(result)
    }
  }
}
