// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_measure

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** 测量类型 */
internal enum class MeasureType(val raw: Int) {
  /** 血压 */
  BLOODPRESSURE(0),
  /** 心率 */
  HEARTRATE(1),
  /** 血氧 */
  SPO2(2),
  /** 压力 */
  STRESS(3),
  /** 一键测量 */
  ONECLICK(4),
  /** 体温 */
  TEMPERATURE(5),
  /** 身体成分 */
  BODYCOMPOSITION(6);

  companion object {
    fun ofRaw(raw: Int): MeasureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** 测量状态 */
internal enum class MeasureStatus(val raw: Int) {
  /** 不支持 */
  NOTSUPPORT(0),
  /** 正在测量 */
  MEASURING(1),
  /** 测量成功 */
  SUCCESS(2),
  /** 测量失败 */
  FAILED(3),
  /** 设备正在运动模式 */
  DEVICEINSPORTMODE(4),
  /** 返回测量中数据 */
  MEASURINGDATA(5),
  /** 超时 (APP) */
  TIMEOUT(6),
  /** 停止 (APP) */
  STOPPED(7),
  /** 断连 (APP) */
  DISCONNECTED(8),
  /** 未佩戴 (设备通知 72) */
  UNWORN(9);

  companion object {
    fun ofRaw(raw: Int): MeasureStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 测量结果模型
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
internal data class MeasureResult (
  /** 状态 */
  val status: MeasureStatus? = null,
  /** 收缩压 (高压) */
  val systolicBp: Long? = null,
  /** 舒张压 (低压) */
  val diastolicBp: Long? = null,
  /** 值 (心率/血氧/压力) */
  val value: Long? = null,
  /** 一键测量-心率 */
  val oneClickHr: Long? = null,
  /** 一键测量-压力 */
  val oneClickStress: Long? = null,
  /** 一键测量-血氧 */
  val oneClickSpo2: Long? = null,
  /** 体温值 (单位摄氏度,该值扩大了10倍, 如 366 表示 36.6度) */
  val temperatureValue: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MeasureResult {
      val status: MeasureStatus? = (list[0] as Int?)?.let {
        MeasureStatus.ofRaw(it)
      }
      val systolicBp = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val diastolicBp = list[2].let { if (it is Int) it.toLong() else it as Long? }
      val value = list[3].let { if (it is Int) it.toLong() else it as Long? }
      val oneClickHr = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val oneClickStress = list[5].let { if (it is Int) it.toLong() else it as Long? }
      val oneClickSpo2 = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val temperatureValue = list[7].let { if (it is Int) it.toLong() else it as Long? }
      return MeasureResult(status, systolicBp, diastolicBp, value, oneClickHr, oneClickStress, oneClickSpo2, temperatureValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      status?.raw,
      systolicBp,
      diastolicBp,
      value,
      oneClickHr,
      oneClickStress,
      oneClickSpo2,
      temperatureValue,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object MeasureDelegateCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MeasureResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MeasureResult -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
internal interface MeasureDelegate {
  /** 测量结果监听 */
  fun listenMeasureResult(result: MeasureResult)

  companion object {
    /** The codec used by MeasureDelegate. */
    val codec: MessageCodec<Any?> by lazy {
      MeasureDelegateCodec
    }
    /** Sets up an instance of `MeasureDelegate` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: MeasureDelegate?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.MeasureDelegate.listenMeasureResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val resultArg = args[0] as MeasureResult
            var wrapped: List<Any?>
            try {
              api.listenMeasureResult(resultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object MeasureCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MeasureResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MeasureResult -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Measure(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Measure. */
    val codec: MessageCodec<Any?> by lazy {
      MeasureCodec
    }
  }
  /** 开始测量 */
  fun startMeasure(typeArg: MeasureType, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Measure.startMeasure", codec)
    channel.send(listOf(typeArg.raw)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 停止测量 */
  fun stopMeasure(typeArg: MeasureType, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Measure.stopMeasure", codec)
    channel.send(listOf(typeArg.raw)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /** 获取当前测量数据 */
  fun getMeasureData(typeArg: MeasureType, callback: (MeasureResult) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Measure.getMeasureData", codec)
    channel.send(listOf(typeArg.raw)) {
      val result = it as MeasureResult
      callback(result)
    }
  }
}
