// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.idosmart.pigeongen.api_tools

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
internal class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 设备信息
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
internal data class VersionInfo (
  /** 协议库版本号 */
  val verMain: String? = null,
  /** c库版本 */
  val verClib: String? = null,
  /** Alexa库版本 */
  val verAlexa: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VersionInfo {
      val verMain = list[0] as String?
      val verClib = list[1] as String?
      val verAlexa = list[2] as String?
      return VersionInfo(verMain, verClib, verAlexa)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      verMain,
      verClib,
      verAlexa,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object ToolCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VersionInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VersionInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
internal class Tool(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by Tool. */
    val codec: MessageCodec<Any?> by lazy {
      ToolCodec
    }
  }
  /**
   * 图片转换格式 png->bmp
   * ```dart
   * inPath 用于转换的png路径(包含文件名及后缀)
   * outPath 转换完的bmp路径(包含文件名及后缀)
   * format 转换成bmp的文件格式
   * 返回 0 成功
   * ```dart
   */
  fun png2Bmp(inPathArg: String, outPathArg: String, formatArg: Long, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.png2Bmp", codec)
    channel.send(listOf(inPathArg, outPathArg, formatArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * 压缩png图片质量
   * ```dart
   * inputFilePath   输入文件路径
   * outputFilePath 输出文件路径
   * 返回 0 成功
   * ```
   */
  fun compressToPNG(inputFilePathArg: String, outputFilePathArg: String, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.compressToPNG", codec)
    channel.send(listOf(inputFilePathArg, outputFilePathArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * 创建EPO.DAT文件
   * ```dart
   * dirPath 存放要制作epo文件的目录
   * epoFilePath 制作的epo文件存放路径
   * ```
   */
  fun makeEpoFile(dirPathArg: String, epoFilePathArg: String, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.makeEpoFile", codec)
    channel.send(listOf(dirPathArg, epoFilePathArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /**
   * 设置流数据是否输出开关
   *
   * iswrite 控制写入流数据开关公开 0不写入 1写入 默认不写入流数据
   * 0 成功
   */
  fun setWriteStreamByte(isWriteArg: Boolean, callback: (Boolean) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.setWriteStreamByte", codec)
    channel.send(listOf(isWriteArg)) {
      val result = it as Boolean
      callback(result)
    }
  }
  /**
   * gsp运动后优化轨迹,根据运动类型初始化速度阈值，若输入其他运动类型，会导致无运动轨迹
   *
   * [motionTypeIn] 运动类型：
   * ```dart
   * 1、户外走路 = 52, 走路 = 1, 徒步 = 4, 运动类型设为0
   * 2、户外跑步 = 48, 跑步 = 2, 运动类型设为1
   * 3、户外骑行 = 50, 骑行 = 3, 运动型性设为2
   * ```dart
   */
  fun gpsInitType(motionTypeInArg: Long, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.gpsInitType", codec)
    channel.send(listOf(motionTypeInArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * gps数据实时处理入口,需要对输出的数据进行判断，若纬度为-180则为错误值，不应该输出
   * ```dart
   * { lon,经度,数据类型double
   *  lat,纬度,数据类型double
   *  timestamp,时间戳,数据类型int
   *  accuracy,定位精度,数据类型double
   *  gpsaccuracystatus,定位等级，0 = 定位未知, 1 = 定位好, 2 = 定位差,数据类型int }
   * ```dart
   */
  fun gpsAlgProcessRealtime(jsonArg: String, callback: (String) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.gpsAlgProcessRealtime", codec)
    channel.send(listOf(jsonArg)) {
      val result = it as String
      callback(result)
    }
  }
  /**
   * 平滑数据，结果保存在数组lat和lon中
   * ```dart
   * {lat,纬度数组,长度为len,数据类型double
   *  lon,经度数组,长度为len,数据类型double len,数据长度}
   * ```dart
   */
  fun gpsSmoothData(jsonArg: String, callback: (String) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.gpsSmoothData", codec)
    channel.send(listOf(jsonArg)) {
      val result = it as String
      callback(result)
    }
  }
  /**
   *  v2发送来电提醒以及来电电话号码和来电联系人(部分设备实现)
   * ```dart
   * contactText：联系人名称
   * phoneNumber：号码
   * 返回 0 成功
   * ```
   */
  fun setV2CallEvt(contactTextArg: String, phoneNumberArg: String, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.setV2CallEvt", codec)
    channel.send(listOf(contactTextArg, phoneNumberArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * v2发送信息提醒以及信息内容(部分设备实现)
   *
   * ```dart
   * type 信息类型
   * contactText 通知内容
   * phoneNumber 号码
   * dataText 消息内容
   * 返回 0 成功
   * ```
   */
  fun setV2NoticeEvt(typeArg: Long, contactTextArg: String, phoneNumberArg: String, dataTextArg: String, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.setV2NoticeEvt", codec)
    channel.send(listOf(typeArg, contactTextArg, phoneNumberArg, dataTextArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * v2发送来电提醒状态为来电已接, 告诉设备停止提醒用户(部分设备实现)
   *
   * 返回 0 成功
   */
  fun stopV2CallEvt(callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.stopV2CallEvt", codec)
    channel.send(null) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /**
   * v2发送来电提醒状态为来电已拒, 告诉设备停止提醒用户(部分设备实现)
   *
   * 返回 0 成功
   */
  fun missedV2MissedCallEvt(callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.missedV2MissedCallEvt", codec)
    channel.send(null) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
  /** 记录原生层log */
  fun logNative(msgArg: String, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.logNative", codec)
    channel.send(listOf(msgArg)) {
      callback()
    }
  }
  /** 获取版本号 */
  fun getSDKVersionInfo(callback: (VersionInfo?) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.getSDKVersionInfo", codec)
    channel.send(null) {
      val result = it as VersionInfo?
      callback(result)
    }
  }
  /**
   * 获取mp3音频采样率
   * ```dart
   * mp3FilePath 输入带路径MP3文件名
   * return int 输入的MP3文件的采样率如：441000， 异常返回-1
   * ```
   */
  fun mp3SamplingRate(mp3FilePathArg: String, callback: (Long) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.protocol_channel.Tool.mp3SamplingRate", codec)
    channel.send(listOf(mp3FilePathArg)) {
      val result = if (it is Int) it.toLong() else it as Long
      callback(result)
    }
  }
}
