///错误类型
const SUCCESS = 0;
const ERROR_INVALID_PARAM = 1;
const ERROR_FILE_NOT_FIND = 2;
const ERROR_FILE_OPERATE_FAILED = 3;
const ERROR_INVALID_STATE = 4;
const ERROR_NULL = 5;
const ERROR_TIMEOUT = 13;
const ERROR_MAX_TIME = 22;

///错误详情
const DATA_TRAN_ERROR_VALUE_STATUS_ERROR = 0x01; //状态错误
const DATA_TRAN_ERROR_VALUE_TIMEOUT_ERROR = 0x02; //超时
