// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Nordic.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

/// Nordic DFU 升级状态枚举 | Nordic DFU upgrade state enum
@implementation NordicDFUStateBox
- (instancetype)initWithValue:(NordicDFUState)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *ApiNordicHostGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void ApiNordicHostSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ApiNordicHost> *api) {
  /// 开始 Nordic DFU 升级 | Start Nordic DFU upgrade
  /// deviceIdentifier: iOS 传 UUID，Android 传 MAC 地址 | iOS passes UUID, Android passes MAC address
  /// filePath: 固件文件路径 | Firmware file path
  /// mtu: ios使用
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.native_channel.ApiNordicHost.startDFU"
        binaryMessenger:binaryMessenger
        codec:ApiNordicHostGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startDFUDeviceIdentifier:filePath:mtu:error:)], @"ApiNordicHost api (%@) doesn't respond to @selector(startDFUDeviceIdentifier:filePath:mtu:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_deviceIdentifier = GetNullableObjectAtIndex(args, 0);
        NSString *arg_filePath = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_mtu = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api startDFUDeviceIdentifier:arg_deviceIdentifier filePath:arg_filePath mtu:arg_mtu error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// 停止 Nordic DFU 升级 | Stop Nordic DFU upgrade
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.native_channel.ApiNordicHost.stopDFU"
        binaryMessenger:binaryMessenger
        codec:ApiNordicHostGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopDFUWithError:)], @"ApiNordicHost api (%@) doesn't respond to @selector(stopDFUWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopDFUWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *ApiNordicFlutterGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

@interface ApiNordicFlutter ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation ApiNordicFlutter

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onDFUStateChangedState:(NordicDFUState)arg_state errorMessage:(NSString *)arg_errorMessage completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.native_channel.ApiNordicFlutter.onDFUStateChanged"
      binaryMessenger:self.binaryMessenger
      codec:ApiNordicFlutterGetCodec()];
  [channel sendMessage:@[[NSNumber numberWithInteger: arg_state], arg_errorMessage ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onDFUProgressProgress:(NSNumber *)arg_progress speed:(NSString *)arg_speed completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.native_channel.ApiNordicFlutter.onDFUProgress"
      binaryMessenger:self.binaryMessenger
      codec:ApiNordicFlutterGetCodec()];
  [channel sendMessage:@[arg_progress ?: [NSNull null], arg_speed ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)logLogMsg:(NSString *)arg_logMsg completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.native_channel.ApiNordicFlutter.log"
      binaryMessenger:self.binaryMessenger
      codec:ApiNordicFlutterGetCodec()];
  [channel sendMessage:@[arg_logMsg ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

