// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, IDOSFBoardType) {
  IDOSFBoardTypeX55 = 0,
  IDOSFBoardTypeX56 = 1,
  IDOSFBoardTypeX52 = 2,
};

/// Wrapper for IDOSFBoardType to allow for nullability.
@interface IDOSFBoardTypeBox : NSObject
@property(nonatomic, assign) IDOSFBoardType value;
- (instancetype)initWithValue:(IDOSFBoardType)value;
@end

typedef NS_ENUM(NSUInteger, OTAUpdateState) {
  OTAUpdateStateInit = 0,
  OTAUpdateStateNoFile = 1,
  OTAUpdateStateBleStateChange = 2,
  OTAUpdateStateEnterOta = 3,
  OTAUpdateStateReconnectDevice = 4,
  OTAUpdateStateDidReconnectDevice = 5,
  OTAUpdateStateStarting = 6,
  OTAUpdateStateUploading = 7,
  OTAUpdateStateCompleted = 8,
  OTAUpdateStateFail = 9,
};

/// Wrapper for OTAUpdateState to allow for nullability.
@interface OTAUpdateStateBox : NSObject
@property(nonatomic, assign) OTAUpdateState value;
- (instancetype)initWithValue:(OTAUpdateState)value;
@end


/// The codec used by ApiSifliHost.
NSObject<FlutterMessageCodec> *ApiSifliHostGetCodec(void);

/// Flutter调用原生的Api，
@protocol ApiSifliHost
///开始进行升级
- (void)startOTAFiles:(NSArray *)files deviceUUID:(NSString *)deviceUUID error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startOTANorFiles:(NSArray *)files deviceUUID:(NSString *)deviceUUID platform:(NSNumber *)platform isIndfu:(NSNumber *)isIndfu error:(FlutterError *_Nullable *_Nonnull)error;
/// 停止升级
- (void)stopWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 将png格式文件序列转为ezipBin类型。转换失败返回nil。V2.2
/// pngDatas png文件数据序列数组 （如果数组是多张图片，则会几张图片组合拼接成一张图片）
/// eColor 颜色字符串 color type as below: rgb565, rgb565A, rbg888, rgb888A
/// eType eizp类型 0 keep original alpha channel;1 no alpha chanel
/// binType bin类型 0 to support rotation; 1 for no rotation
/// boardType 主板芯片类型 @See SFBoardType 0:55x 1:56x  2:52x
/// @return ezip or apng result, nil for fail
- (nullable FlutterStandardTypedData *)sifliEBinFromPngPngDatas:(FlutterStandardTypedData *)pngDatas eColor:(NSString *)eColor type:(NSNumber *)type binType:(NSNumber *)binType boardType:(IDOSFBoardType)boardType error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ApiSifliHostSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ApiSifliHost> *_Nullable api);

/// The codec used by ApiSifliFlutter.
NSObject<FlutterMessageCodec> *ApiSifliFlutterGetCodec(void);

@interface ApiSifliFlutter : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
/// 升级状态 | Upgrade status
/// state 状态值 | Status value
/// desc 描述日志 | Status value
- (void)updateManageStateState:(OTAUpdateState)state desc:(NSString *)desc completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// 升级过程的进度 | Progress of the upgrade process
/// progress 进度 (0 ~ 1) | Progress (0 ~ 1)
/// message 升级日志信息 | Upgrade log information
- (void)updateManagerProgressProgress:(NSNumber *)progress message:(NSString *)message completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)logLogMsg:(NSString *)logMsg completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
