// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum ApiLoginState {
  /// 登录中
  logging,
  /// 已登录
  logined,
  /// 未登录
  logout,
}

/// Alexa 语音状态 (未启用)
enum ApiVoiceState {
  /// 无状态
  none,
  /// 准备
  ready,
  /// 开始
  starting,
  /// 结束
  finished,
}

/// 国家及语言
enum ApiLanguageType {
  /// 德语
  german,
  /// 英语 澳大利亚
  australia,
  /// 英语 加拿大
  canadaEn,
  /// 英语 英国
  unitedKingdom,
  /// 英语 印度
  india,
  ///英语 美国
  usa,
  /// 西班牙语 西班牙
  spainEs,
  /// 西班牙语 墨西哥
  mexico,
  /// 西班牙语 美国
  spainUs,
  /// 法语 加拿大
  frenchCanada,
  /// 法语 法国
  frenchFrench,
  /// 印地语 印度
  hindiIndia,
  /// 意大利语
  italianItaly,
  /// 日语
  japan,
  /// 葡萄牙语
  portugal,
}

/// 健康数据类型
enum ApiGetValueType {
  /// 当天步数
  pedometer,
  /// 当天卡路里
  calorie,
  /// 当天最近一次测量的心率
  heartRate,
  /// 当天血氧
  spO2,
  /// 当天距离（米）
  kilometer,
  /// 当天室内游泳距离（米）
  swimmingDistance,
  /// 当天睡眠得分
  sleepScore,
  /// 当天跑步次数
  runningCount,
  /// 当天游泳次数
  swimmingCount,
  /// 当天运动次数
  dayWorkoutCount,
  /// 当周运动次数
  weekWorkoutCount,
  /// 身体电量
  bodyBattery,
}

class AlexaAuthDelegate {
  /// Constructor for [AlexaAuthDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AlexaAuthDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// Alexa认证需要打开的url和userCode
  Future<void> callbackPairCode(String arg_userCode, String arg_verificationUri) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.callbackPairCode', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_userCode, arg_verificationUri]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听登录状态
  Future<void> loginStateChanged(ApiLoginState arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.loginStateChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听语音状态
  Future<void> voiceStateChanged(ApiVoiceState arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaAuthDelegate.voiceStateChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class AlexaDataSource {
  /// Constructor for [AlexaDataSource].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AlexaDataSource({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 获取健康数据
  Future<int> getHealthValue(ApiGetValueType arg_valueType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaDataSource.getHealthValue', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_valueType.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as int?)!;
    }
  }

  /// 获取心率
  Future<int> getHrValue(int arg_dataType, int arg_timeType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaDataSource.getHrValue', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_dataType, arg_timeType]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as int?)!;
    }
  }

  /// 功能控制
  ///
  /// funType 0 关闭找手机功能
  Future<void> functionControl(int arg_funType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.AlexaDataSource.functionControl', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_funType]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class Alexa {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 是否已登录
  bool isLogin();

  /// 获取当前语言
  ApiLanguageType currentLanguage();

  /// 注册alexa
  /// ```dart
  /// clientId Alexa后台生成的ID
  /// writeToFile 写log文件
  /// outputToConsole 打印到控制台
  /// logLevel 日志级别（该值只会在debug模式下有效）
  /// ```
  Future<void> registerAlexa(String clientId);

  /// 网络变更需实时调用此方法(重要!!!)
  void onNetworkChanged(bool hasNetwork);

  /// 切换语言 默认英语
  Future<bool> changeLanguage(ApiLanguageType type);

  /// Alexa CBL授权
  /// ```dart
  /// productId 在alexa后台注册的产品ID
  /// func 回调Alexa认证需要打开的url和userCode
  /// 返回 0 成功，1 失败，2 超时
  /// ```
  Future<int> authorizeRequest(String productId);

  /// 停止登录 (结束当前执行中的相关登录操作)
  void stopLogin();

  /// 退出登录
  void logout();

  /// 是否支持语音测试
  Future<bool> isSupportAudioTesting();

  /// 测试pcm上传 (内部使用)
  Future<bool> testUploadPCM(String pcmPath);

  void debugTest();

  void refreshToken();

  static void setup(Alexa? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.isLogin', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = api.isLogin();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.currentLanguage', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final ApiLanguageType output = api.currentLanguage();
          return output.index;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.registerAlexa', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Alexa.registerAlexa was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_clientId = (args[0] as String?);
          assert(arg_clientId != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Alexa.registerAlexa was null, expected non-null String.');
          await api.registerAlexa(arg_clientId!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.onNetworkChanged', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Alexa.onNetworkChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_hasNetwork = (args[0] as bool?);
          assert(arg_hasNetwork != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Alexa.onNetworkChanged was null, expected non-null bool.');
          api.onNetworkChanged(arg_hasNetwork!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.changeLanguage', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Alexa.changeLanguage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ApiLanguageType? arg_type = args[0] == null ? null : ApiLanguageType.values[args[0]! as int];
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Alexa.changeLanguage was null, expected non-null ApiLanguageType.');
          final bool output = await api.changeLanguage(arg_type!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.authorizeRequest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Alexa.authorizeRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_productId = (args[0] as String?);
          assert(arg_productId != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Alexa.authorizeRequest was null, expected non-null String.');
          final int output = await api.authorizeRequest(arg_productId!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.stopLogin', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.stopLogin();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.logout', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.logout();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.isSupportAudioTesting', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = await api.isSupportAudioTesting();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.testUploadPCM', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Alexa.testUploadPCM was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_pcmPath = (args[0] as String?);
          assert(arg_pcmPath != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Alexa.testUploadPCM was null, expected non-null String.');
          final bool output = await api.testUploadPCM(arg_pcmPath!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.debugTest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.debugTest();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Alexa.refreshToken', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.refreshToken();
          return;
        });
      }
    }
  }
}
