// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// 连接状态：
/// 断开连接，
/// 连接中，
/// 已连接，
/// 断开连接中
enum DeviceStateType {
  disconnected,
  connecting,
  connected,
  disconnecting,
}

/// 蓝牙状态：
/// 未知，
/// 系统服务重启中，
/// 不支持，
/// 未授权，
/// 蓝牙关闭，
/// 蓝牙打开
enum BluetoothStateType {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

/// 扫描状态
/// 扫描中
/// 扫描结束
/// 找到设备（android）
enum BluetoothScanType {
  scanning,
  stop,
  find,
}

/// 连接错误
/// 无状态
/// UUID或Mac地址异常
/// 蓝牙关闭
/// 主动断开连接
/// 连接失败
/// 连接超时
/// 发现服务失败
/// 发现特征失败
/// 配对异常
/// 获取基本信息失败
/// 设备已绑定并且不支持重复绑定
/// app 绑定的设备被重置了
/// 连接被终止，比如在 ota 中，不需要执行重连了
enum ConnectErrorType {
  none,
  abnormalUUIDMacAddress,
  bluetoothOff,
  connectCancel,
  fail,
  timeOut,
  serviceFail,
  characteristicsFail,
  pairFail,
  informationFail,
  cancelByUser,
  deviceAlreadyBindAndNotSupportRebind,
  deviceHasBeenReset,
  connectTerminated,
}

/// 写数据状态
/// 有响应
/// 无响应
/// 错误
enum WriteType {
  withResponse,
  withoutResponse,
  error,
}

/// spp:
/// 开始连接
/// 连接成功
/// 连接失败
/// 断链
enum SPPStateType {
  onStart,
  onSuccess,
  onFail,
  onBreak,
}

class DeviceModel {
  DeviceModel({
    this.rssi,
    this.name,
    this.state,
    this.uuid,
    this.macAddress,
    this.otaMacAddress,
    this.btMacAddress,
    this.deviceId,
    this.deviceType,
    this.isOta,
    this.isTlwOta,
    this.bltVersion,
    this.isPair,
    this.platform,
  });

  /// rssi
  int? rssi;

  /// 设备名称
  String? name;

  /// 设备状态
  DeviceStateType? state;

  ///uuid
  String? uuid;

  ///mac address
  String? macAddress;

  /// ota mac address
  String? otaMacAddress;

  /// bt mac address
  String? btMacAddress;

  /// 设备ID
  int? deviceId;

  /// 设备类型 0:无效 1: 手表 2: 手环
  int? deviceType;

  /// 是否ota模式
  bool? isOta;

  ///是否泰凌微ota
  bool? isTlwOta;

  ///bt版本号
  int? bltVersion;

  ///配对状态（Android）
  bool? isPair;

  ///平台
  int? platform;

  Object encode() {
    return <Object?>[
      rssi,
      name,
      state?.index,
      uuid,
      macAddress,
      otaMacAddress,
      btMacAddress,
      deviceId,
      deviceType,
      isOta,
      isTlwOta,
      bltVersion,
      isPair,
      platform,
    ];
  }

  static DeviceModel decode(Object result) {
    result as List<Object?>;
    return DeviceModel(
      rssi: result[0] as int?,
      name: result[1] as String?,
      state: result[2] != null
          ? DeviceStateType.values[result[2]! as int]
          : null,
      uuid: result[3] as String?,
      macAddress: result[4] as String?,
      otaMacAddress: result[5] as String?,
      btMacAddress: result[6] as String?,
      deviceId: result[7] as int?,
      deviceType: result[8] as int?,
      isOta: result[9] as bool?,
      isTlwOta: result[10] as bool?,
      bltVersion: result[11] as int?,
      isPair: result[12] as bool?,
      platform: result[13] as int?,
    );
  }
}

class BluetoothStateModel {
  BluetoothStateModel({
    this.type,
    this.scanType,
  });

  BluetoothStateType? type;

  BluetoothScanType? scanType;

  Object encode() {
    return <Object?>[
      type?.index,
      scanType?.index,
    ];
  }

  static BluetoothStateModel decode(Object result) {
    result as List<Object?>;
    return BluetoothStateModel(
      type: result[0] != null
          ? BluetoothStateType.values[result[0]! as int]
          : null,
      scanType: result[1] != null
          ? BluetoothScanType.values[result[1]! as int]
          : null,
    );
  }
}

class DeviceStateModel {
  DeviceStateModel({
    this.uuid,
    this.macAddress,
    this.state,
    this.errorState,
  });

  String? uuid;

  String? macAddress;

  DeviceStateType? state;

  ConnectErrorType? errorState;

  Object encode() {
    return <Object?>[
      uuid,
      macAddress,
      state?.index,
      errorState?.index,
    ];
  }

  static DeviceStateModel decode(Object result) {
    result as List<Object?>;
    return DeviceStateModel(
      uuid: result[0] as String?,
      macAddress: result[1] as String?,
      state: result[2] != null
          ? DeviceStateType.values[result[2]! as int]
          : null,
      errorState: result[3] != null
          ? ConnectErrorType.values[result[3]! as int]
          : null,
    );
  }
}

class WriteStateModel {
  WriteStateModel({
    this.state,
    this.uuid,
    this.macAddress,
    this.type,
  });

  /// 写入状态是否成功
  bool? state;

  /// uuid
  String? uuid;

  /// mac address
  String? macAddress;

  /// 写入类型
  WriteType? type;

  Object encode() {
    return <Object?>[
      state,
      uuid,
      macAddress,
      type?.index,
    ];
  }

  static WriteStateModel decode(Object result) {
    result as List<Object?>;
    return WriteStateModel(
      state: result[0] as bool?,
      uuid: result[1] as String?,
      macAddress: result[2] as String?,
      type: result[3] != null
          ? WriteType.values[result[3]! as int]
          : null,
    );
  }
}

class ReceiveData {
  ReceiveData({
    this.data,
    this.uuid,
    this.macAddress,
    this.spp,
    this.platform,
  });

  /// 蓝牙字节数据
  Uint8List? data;

  /// uuid
  String? uuid;

  /// mac address
  String? macAddress;

  /// spp
  bool? spp;

  /// 0 爱都, 1 恒玄, 2 VC
  int? platform;

  Object encode() {
    return <Object?>[
      data,
      uuid,
      macAddress,
      spp,
      platform,
    ];
  }

  static ReceiveData decode(Object result) {
    result as List<Object?>;
    return ReceiveData(
      data: result[0] as Uint8List?,
      uuid: result[1] as String?,
      macAddress: result[2] as String?,
      spp: result[3] as bool?,
      platform: result[4] as int?,
    );
  }
}

class SPPStateModel {
  SPPStateModel({
    this.type,
  });

  SPPStateType? type;

  Object encode() {
    return <Object?>[
      type?.index,
    ];
  }

  static SPPStateModel decode(Object result) {
    result as List<Object?>;
    return SPPStateModel(
      type: result[0] != null
          ? SPPStateType.values[result[0]! as int]
          : null,
    );
  }
}

/// 设备升级
class DfuConfig {
  DfuConfig({
    this.filePath,
    this.uuid,
    this.macAddress,
    this.deviceId,
    this.platform,
    this.isDeviceSupportPairedWithPhoneSystem,
    this.prn,
    this.isNeedReOpenBluetoothSwitchIfFailed,
    this.maxRetryTime,
    this.isNeedAuth,
    this.otaWorkMode,
  });

  /// ota文件包路径
  String? filePath;

  ///设备的uuid, iOS使用
  String? uuid;

  ///设备的ble地址 安卓使用
  String? macAddress;

  ///设备的id
  String? deviceId;

  ///平台，默认为nordic，目前只支持nordic
  int? platform;

  ///设备是否支持配对，根据功能表V3_dev_support_pair_each_connect  安卓使用
  bool? isDeviceSupportPairedWithPhoneSystem;

  ///每次接受到包数，可不填
  int? prn;

  ///在重试过程中，如果多次升级失败，是否需要重启蓝牙
  bool? isNeedReOpenBluetoothSwitchIfFailed;

  ///最大重试次数
  int? maxRetryTime;

  ///RTK平台的OTA，在升级之前是否需要授权
  bool? isNeedAuth;

  ///RTK平台的OTA，模式
  int? otaWorkMode;

  Object encode() {
    return <Object?>[
      filePath,
      uuid,
      macAddress,
      deviceId,
      platform,
      isDeviceSupportPairedWithPhoneSystem,
      prn,
      isNeedReOpenBluetoothSwitchIfFailed,
      maxRetryTime,
      isNeedAuth,
      otaWorkMode,
    ];
  }

  static DfuConfig decode(Object result) {
    result as List<Object?>;
    return DfuConfig(
      filePath: result[0] as String?,
      uuid: result[1] as String?,
      macAddress: result[2] as String?,
      deviceId: result[3] as String?,
      platform: result[4] as int?,
      isDeviceSupportPairedWithPhoneSystem: result[5] as bool?,
      prn: result[6] as int?,
      isNeedReOpenBluetoothSwitchIfFailed: result[7] as bool?,
      maxRetryTime: result[8] as int?,
      isNeedAuth: result[9] as bool?,
      otaWorkMode: result[10] as int?,
    );
  }
}

class _BluetoothDelegateCodec extends StandardMessageCodec {
  const _BluetoothDelegateCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BluetoothStateModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is DeviceModel) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is DeviceStateModel) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ReceiveData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SPPStateModel) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is WriteStateModel) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BluetoothStateModel.decode(readValue(buffer)!);
      case 129: 
        return DeviceModel.decode(readValue(buffer)!);
      case 130: 
        return DeviceStateModel.decode(readValue(buffer)!);
      case 131: 
        return ReceiveData.decode(readValue(buffer)!);
      case 132: 
        return SPPStateModel.decode(readValue(buffer)!);
      case 133: 
        return WriteStateModel.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BluetoothDelegate {
  /// Constructor for [BluetoothDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BluetoothDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _BluetoothDelegateCodec();

  /// 发送数据状态
  Future<void> writeState(WriteStateModel arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.writeState', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 收到数据
  Future<void> receiveData(ReceiveData arg_data) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.receiveData', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_data]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 搜索设备结果
  Future<void> scanResult(List<DeviceModel?>? arg_list) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.scanResult', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_list]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 蓝牙状态
  Future<void> bluetoothState(BluetoothStateModel arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.bluetoothState', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设备状态状态
  Future<void> deviceState(DeviceStateModel arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.deviceState', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// spp状态
  Future<void> stateSPP(SPPStateModel arg_state) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.stateSPP', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_state]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// spp文件写完成
  Future<void> writeSPPCompleteState(String arg_btMacAddress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.writeSPPCompleteState', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_btMacAddress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听dfu完成状态
  Future<void> dfuComplete() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuComplete', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听dfu过程的错误
  Future<void> dfuError(String arg_error) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuError', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_error]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听升级进度
  /// 0-100
  Future<void> dfuProgress(int arg_progress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.dfuProgress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_progress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听当前设备
  Future<void> changeCurrentDevice(DeviceModel arg_device) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.changeCurrentDevice', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_device]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听当前设备属性变更（目前针对btMacAddress 内部使用）
  Future<void> onCurrentDeviceAttrValChange(DeviceModel arg_device) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.onCurrentDeviceAttrValChange', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_device]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// bt状态
  Future<void> stateBt(bool arg_isPair) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.BluetoothDelegate.stateBt', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_isPair]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _BluetoothCodec extends StandardMessageCodec {
  const _BluetoothCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BluetoothStateModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is DeviceModel) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is DeviceModel) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is DeviceStateModel) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is DfuConfig) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is WriteStateModel) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BluetoothStateModel.decode(readValue(buffer)!);
      case 129: 
        return DeviceModel.decode(readValue(buffer)!);
      case 130: 
        return DeviceModel.decode(readValue(buffer)!);
      case 131: 
        return DeviceStateModel.decode(readValue(buffer)!);
      case 132: 
        return DfuConfig.decode(readValue(buffer)!);
      case 133: 
        return WriteStateModel.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class Bluetooth {
  static const MessageCodec<Object?> codec = _BluetoothCodec();

  /// 最后一次连接设备
  DeviceModel? currentDevice();

  /// 注册,程序开始运行调用
  /// heartPingSecond:心跳包间隔(ios)
  /// outputToConsole：控制台输出日志
  void register(int heartPingSecond, bool outputToConsole);

  /// 开始搜索
  /// macAddress（Android）:根据Mac地址搜索
  /// 返回指定搜索的设备，如未指定返回null
  Future<List<DeviceModel?>?> startScan(String? macAddress);

  /// 搜索筛选条件
  /// deviceName: 只搜索deviceName的设备
  /// deviceID：只搜索deviceID的设备
  /// macAddress：只搜索macAddress的设备
  /// uuid：只搜索uuid的设备
  void scanFilter(List<String?>? deviceName, List<int?>? deviceID, List<String?>? macAddress, List<String?>? uuid);

  /// 停止搜索
  void stopScan();

  /// 连接
  /// device: Mac地址必传，iOS要带上uuid，最好使用搜索返回的对象
  void connect(DeviceModel? device);

  /// 使用这个重连设备
  void autoConnect(DeviceModel? device);

  /// 取消连接
  Future<bool> cancelConnect(String? macAddress);

  /// 获取蓝牙状态
  Future<BluetoothStateModel> getBluetoothState();

  /// 获取设备连接状态
  Future<DeviceStateModel> getDeviceState(DeviceModel? device);

  /// 发送数据
  /// data:数据
  /// device: 发送数据的设备
  /// type:0 BLE数据, 1 SPP数据
  /// platform: 0 爱都, 1 恒玄, 2 VC
  Future<WriteStateModel> writeData(Uint8List data, DeviceModel? device, int type, int platform);

  /// bt配对（android）
  void setBtPair(DeviceModel device);

  /// 取消配对（android）
  void cancelPair(DeviceModel? device);

  /// 连接SPP
  void connectSPP(String btMacAddress);

  /// 断开SPP
  void disconnectSPP(String btMacAddress);

  ///发起dfu升级
  void startNordicDFU(DfuConfig config);

  /// 日志路径
  Future<String?> logPath();

  static void setup(Bluetooth? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.currentDevice', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final DeviceModel? output = api.currentDevice();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.register', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.register was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_heartPingSecond = (args[0] as int?);
          assert(arg_heartPingSecond != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.register was null, expected non-null int.');
          final bool? arg_outputToConsole = (args[1] as bool?);
          assert(arg_outputToConsole != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.register was null, expected non-null bool.');
          api.register(arg_heartPingSecond!, arg_outputToConsole!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.startScan', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.startScan was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddress = (args[0] as String?);
          final List<DeviceModel?>? output = await api.startScan(arg_macAddress);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.scanFilter', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.scanFilter was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<String?>? arg_deviceName = (args[0] as List<Object?>?)?.cast<String?>();
          final List<int?>? arg_deviceID = (args[1] as List<Object?>?)?.cast<int?>();
          final List<String?>? arg_macAddress = (args[2] as List<Object?>?)?.cast<String?>();
          final List<String?>? arg_uuid = (args[3] as List<Object?>?)?.cast<String?>();
          api.scanFilter(arg_deviceName, arg_deviceID, arg_macAddress, arg_uuid);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.stopScan', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.stopScan();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.connect', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.connect was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceModel? arg_device = (args[0] as DeviceModel?);
          api.connect(arg_device);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.autoConnect', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.autoConnect was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceModel? arg_device = (args[0] as DeviceModel?);
          api.autoConnect(arg_device);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.cancelConnect', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.cancelConnect was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddress = (args[0] as String?);
          final bool output = await api.cancelConnect(arg_macAddress);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.getBluetoothState', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final BluetoothStateModel output = await api.getBluetoothState();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.getDeviceState', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.getDeviceState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceModel? arg_device = (args[0] as DeviceModel?);
          final DeviceStateModel output = await api.getDeviceState(arg_device);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.writeData', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.writeData was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Uint8List? arg_data = (args[0] as Uint8List?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.writeData was null, expected non-null Uint8List.');
          final DeviceModel? arg_device = (args[1] as DeviceModel?);
          final int? arg_type = (args[2] as int?);
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.writeData was null, expected non-null int.');
          final int? arg_platform = (args[3] as int?);
          assert(arg_platform != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.writeData was null, expected non-null int.');
          final WriteStateModel output = await api.writeData(arg_data!, arg_device, arg_type!, arg_platform!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.setBtPair', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.setBtPair was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceModel? arg_device = (args[0] as DeviceModel?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.setBtPair was null, expected non-null DeviceModel.');
          api.setBtPair(arg_device!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.cancelPair', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.cancelPair was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceModel? arg_device = (args[0] as DeviceModel?);
          api.cancelPair(arg_device);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.connectSPP', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.connectSPP was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_btMacAddress = (args[0] as String?);
          assert(arg_btMacAddress != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.connectSPP was null, expected non-null String.');
          api.connectSPP(arg_btMacAddress!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.disconnectSPP', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.disconnectSPP was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_btMacAddress = (args[0] as String?);
          assert(arg_btMacAddress != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.disconnectSPP was null, expected non-null String.');
          api.disconnectSPP(arg_btMacAddress!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.startNordicDFU', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.startNordicDFU was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DfuConfig? arg_config = (args[0] as DfuConfig?);
          assert(arg_config != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Bluetooth.startNordicDFU was null, expected non-null DfuConfig.');
          api.startNordicDFU(arg_config!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Bluetooth.logPath', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final String? output = await api.logPath();
          return output;
        });
      }
    }
  }
}
