// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// 设备信息
class DeviceInfo {
  DeviceInfo({
    this.deviceMode,
    this.battStatus,
    this.battLevel,
    this.rebootFlag,
    this.bindState,
    this.bindType,
    this.bindTimeout,
    this.platform,
    this.deviceShapeType,
    this.deviceType,
    this.dialMainVersion,
    this.showBindChoiceUi,
    this.deviceId,
    this.firmwareVersion,
    this.sn,
    this.btName,
    this.gpsPlatform,
    this.macAddress,
    this.macAddressFull,
    this.deviceName,
    this.otaMode,
    this.uuid,
    this.macAddressBt,
    this.fwVersion1,
    this.fwVersion2,
    this.fwVersion3,
    this.fwBtFlag,
    this.fwBtVersion1,
    this.fwBtVersion2,
    this.fwBtVersion3,
    this.fwBtMatchVersion1,
    this.fwBtMatchVersion2,
    this.fwBtMatchVersion3,
  });

  /// 设备模式 0：运动模式，1：睡眠模式
  int? deviceMode;

  /// 电量状态 0:正常, 1:正在充电, 2:充满, 3:电量低
  int? battStatus;

  /// 电量级别 0～100
  int? battLevel;

  /// 是否重启 0:未重启 1:重启
  int? rebootFlag;

  /// 绑定状态 0:未绑定 1:已绑定
  int? bindState;

  /// 绑定类型 0:默认 1:单击 2:长按 3:屏幕点击 横向确认和取消,确认在左边 4:屏幕点击 横向确认和取消,确认在右边
  /// 5:屏幕点击 竖向确认和取消,确认在上边 6:屏幕点击 竖向确认和取消,确认在下边 7:点击(右边一个按键)
  int? bindType;

  /// 绑定超时 最长为15秒,0表示不超时
  int? bindTimeout;

  /// 设备平台 0:nordic, 10:realtek 8762x, 20:cypress psoc6, 30:Apollo3, 40:汇顶, 50:nordic+泰凌微,
  /// 60:泰凌微+5340+no nand flash, 70:汇顶+富瑞坤, 80:5340
  int? platform;

  /// 设备形状类型 0：无效；1：圆形；2：方形的； 3：椭圆
  int? deviceShapeType;

  /// 设备类型 0：无效；1：手环；2：手表
  int? deviceType;

  /// 自定义表盘主版本 从1开始 0:不支持对应的自定义表盘功能
  int? dialMainVersion;

  /// 固件绑定时候显示勾ui界面 0:不需要 1:需要
  int? showBindChoiceUi;

  /// 设备id
  int? deviceId;

  /// 设备固件主版本号
  int? firmwareVersion;

  /// 设备SN
  String? sn;

  /// BtName
  String? btName;

  /// GPS芯片平台 0：无效 1：索尼 sony 2：洛达 Airoh 3：芯与物 icoe
  int? gpsPlatform;

  /// （SDK 内部专用， 外部慎用！！！）
  /// 当前设备mac地址 - 无冒号
  String? macAddress;

  /// （SDK 内部专用， 外部慎用！！！）
  /// 当前设备mac地址 - 带冒号
  String? macAddressFull;

  /// （SDK 内部专用， 外部慎用！！！）
  /// 注意：该名称是由调用 libManager.markConnectedDevice(...)传入，sdk不会主去刷新该值
  /// 需要获取最新值可以使用 CmdEvtType.getDeviceName 指令
  String? deviceName;

  /// （SDK 内部专用， 外部慎用！！！）
  /// OTA模式
  bool? otaMode;

  /// （（SDK 内部专用， 外部慎用！！！）
  /// UUID ios专用
  String? uuid;

  /// BT macAddress - 带冒号
  String? macAddressBt;

  /// 固件版本version1
  int? fwVersion1;

  /// 固件版本version2
  int? fwVersion2;

  /// 固件版本version3
  int? fwVersion3;

  /// BT版本生效标志位 0：无效 1：说明固件有对应的BT固件
  int? fwBtFlag;

  /// BT的版本version1
  int? fwBtVersion1;

  /// BT的版本version2
  int? fwBtVersion2;

  /// BT的版本version3
  int? fwBtVersion3;

  /// BT的所需要匹配的版本version1
  int? fwBtMatchVersion1;

  /// BT的所需要匹配的版本version2
  int? fwBtMatchVersion2;

  /// BT的所需要匹配的版本version3
  int? fwBtMatchVersion3;

  Object encode() {
    return <Object?>[
      deviceMode,
      battStatus,
      battLevel,
      rebootFlag,
      bindState,
      bindType,
      bindTimeout,
      platform,
      deviceShapeType,
      deviceType,
      dialMainVersion,
      showBindChoiceUi,
      deviceId,
      firmwareVersion,
      sn,
      btName,
      gpsPlatform,
      macAddress,
      macAddressFull,
      deviceName,
      otaMode,
      uuid,
      macAddressBt,
      fwVersion1,
      fwVersion2,
      fwVersion3,
      fwBtFlag,
      fwBtVersion1,
      fwBtVersion2,
      fwBtVersion3,
      fwBtMatchVersion1,
      fwBtMatchVersion2,
      fwBtMatchVersion3,
    ];
  }

  static DeviceInfo decode(Object result) {
    result as List<Object?>;
    return DeviceInfo(
      deviceMode: result[0] as int?,
      battStatus: result[1] as int?,
      battLevel: result[2] as int?,
      rebootFlag: result[3] as int?,
      bindState: result[4] as int?,
      bindType: result[5] as int?,
      bindTimeout: result[6] as int?,
      platform: result[7] as int?,
      deviceShapeType: result[8] as int?,
      deviceType: result[9] as int?,
      dialMainVersion: result[10] as int?,
      showBindChoiceUi: result[11] as int?,
      deviceId: result[12] as int?,
      firmwareVersion: result[13] as int?,
      sn: result[14] as String?,
      btName: result[15] as String?,
      gpsPlatform: result[16] as int?,
      macAddress: result[17] as String?,
      macAddressFull: result[18] as String?,
      deviceName: result[19] as String?,
      otaMode: result[20] as bool?,
      uuid: result[21] as String?,
      macAddressBt: result[22] as String?,
      fwVersion1: result[23] as int?,
      fwVersion2: result[24] as int?,
      fwVersion3: result[25] as int?,
      fwBtFlag: result[26] as int?,
      fwBtVersion1: result[27] as int?,
      fwBtVersion2: result[28] as int?,
      fwBtVersion3: result[29] as int?,
      fwBtMatchVersion1: result[30] as int?,
      fwBtMatchVersion2: result[31] as int?,
      fwBtMatchVersion3: result[32] as int?,
    );
  }
}

class _DeviceDelegateCodec extends StandardMessageCodec {
  const _DeviceDelegateCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeviceInfo) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return DeviceInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DeviceDelegate {
  /// Constructor for [DeviceDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _DeviceDelegateCodec();

  /// 设备信息变更通知
  Future<void> listenDeviceChanged(DeviceInfo arg_deviceInfo) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.DeviceDelegate.listenDeviceChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_deviceInfo]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 绑定时获取的设备信息通知(绑定专用)
  Future<void> listenDeviceOnBind(DeviceInfo arg_deviceInfo) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.DeviceDelegate.listenDeviceOnBind', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_deviceInfo]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class Device {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 刷新设备信息（SDK内部使用）
  Future<bool> refreshDeviceInfo(bool forced);

  /// 刷新设备信息 绑定前使用（SDK内部使用）
  Future<bool> refreshDeviceInfoBeforeBind(bool forced);

  /// 刷新设备三级版本（SDK内部使用）
  Future<bool> refreshFirmwareVersion(bool forced);

  /// 刷新设备扩展信息（SDK内部使用）
  Future<bool> refreshDeviceExtInfo();

  /// 设置设备BT MacAddress（SDK内部使用）
  void setDeviceBtMacAddress(String macAddressBt);

  /// 清理数据 (SDK内部使用)
  void cleanDataOnMemory();

  static void setup(Device? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfo', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfo was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_forced = (args[0] as bool?);
          assert(arg_forced != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfo was null, expected non-null bool.');
          final bool output = await api.refreshDeviceInfo(arg_forced!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfoBeforeBind', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfoBeforeBind was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_forced = (args[0] as bool?);
          assert(arg_forced != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshDeviceInfoBeforeBind was null, expected non-null bool.');
          final bool output = await api.refreshDeviceInfoBeforeBind(arg_forced!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.refreshFirmwareVersion', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshFirmwareVersion was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_forced = (args[0] as bool?);
          assert(arg_forced != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Device.refreshFirmwareVersion was null, expected non-null bool.');
          final bool output = await api.refreshFirmwareVersion(arg_forced!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.refreshDeviceExtInfo', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = await api.refreshDeviceExtInfo();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.setDeviceBtMacAddress', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Device.setDeviceBtMacAddress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddressBt = (args[0] as String?);
          assert(arg_macAddressBt != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Device.setDeviceBtMacAddress was null, expected non-null String.');
          api.setDeviceBtMacAddress(arg_macAddressBt!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Device.cleanDataOnMemory', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.cleanDataOnMemory();
          return;
        });
      }
    }
  }
}
