// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class DeviceLogDelegate {
  /// Constructor for [DeviceLogDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceLogDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 监听日志获取状态
  Future<void> listenLogStatus(bool arg_status) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_status]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 监听日志目录地址
  Future<void> listenLogDirPath(String arg_dirPath) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.listenLogDirPath', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_dirPath]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 日志整体进度 0-100
  Future<void> callbackLogProgress(double arg_progress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.DeviceLogDelegate.callbackLogProgress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_progress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class DeviceLog {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 判断日志状态
  bool getLogIng();

  /// 获取所有日志目录地址，每个日志目录下存放以时间戳命名的文件
  /// flash 日志目录 =>  Flash
  /// 电池日志目录 => Battery
  /// 过热日志目录 => Heat
  /// 旧的重启日志目录 => Reboot
  Future<String> logDirPath();

  /// 开始获取日志
  /// type 1: 旧的重启日志 2: 通用日志 3: 复位日志
  /// 4: 硬件日志 5: 算法日志 6: 新重启日志 7:电池日志 8: 过热日志
  Future<bool> startGet(List<int?> types, int timeOut);

  /// 取消
  void cancel();

  static void setup(DeviceLog? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.DeviceLog.getLogIng', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = api.getLogIng();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.DeviceLog.logDirPath', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final String output = await api.logDirPath();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.DeviceLog.startGet', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.DeviceLog.startGet was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<int?>? arg_types = (args[0] as List<Object?>?)?.cast<int?>();
          assert(arg_types != null,
              'Argument for dev.flutter.pigeon.protocol_channel.DeviceLog.startGet was null, expected non-null List<int?>.');
          final int? arg_timeOut = (args[1] as int?);
          assert(arg_timeOut != null,
              'Argument for dev.flutter.pigeon.protocol_channel.DeviceLog.startGet was null, expected non-null int.');
          final bool output = await api.startGet(arg_types!, arg_timeOut!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.DeviceLog.cancel', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.cancel();
          return;
        });
      }
    }
  }
}
