// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// EPO升级状态
enum ApiEpoUpgradeStatus {
  /// 空闲
  idle,
  /// 准备更新
  ready,
  /// 下载中
  downing,
  /// 制作中
  making,
  /// 发送中
  sending,
  /// 安装中
  installing,
  /// 成功
  success,
  /// 失败
  failure,
}

class ApiOTAGpsInfo {
  ApiOTAGpsInfo({
    this.tcxoOffset,
    this.longitude,
    this.latitude,
    this.altitude,
  });

  ///	晶振偏移
  int? tcxoOffset;

  /// 经度
  double? longitude;

  /// 纬度
  double? latitude;

  /// 海拔高度
  double? altitude;

  Object encode() {
    return <Object?>[
      tcxoOffset,
      longitude,
      latitude,
      altitude,
    ];
  }

  static ApiOTAGpsInfo decode(Object result) {
    result as List<Object?>;
    return ApiOTAGpsInfo(
      tcxoOffset: result[0] as int?,
      longitude: result[1] as double?,
      latitude: result[2] as double?,
      altitude: result[3] as double?,
    );
  }
}

class _ApiEpoManagerDelegateCodec extends StandardMessageCodec {
  const _ApiEpoManagerDelegateCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ApiOTAGpsInfo) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ApiOTAGpsInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ApiEpoManagerDelegate {
  /// Constructor for [ApiEpoManagerDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApiEpoManagerDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _ApiEpoManagerDelegateCodec();

  /// 升级状态
  Future<void> onEpoStatusChanged(ApiEpoUpgradeStatus arg_status) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoStatusChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_status.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 下载进度
  Future<void> onEpoDownloadProgress(double arg_progress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoDownloadProgress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_progress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 发送进度
  Future<void> onEpoSendProgress(double arg_progress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoSendProgress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_progress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 升级完成（成功或失败）
  /// errorCode：0 升级成功，非0升级失败
  Future<void> onEpoComplete(int arg_errorCode) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onEpoComplete', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_errorCode]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// app提供当前手机gps信息，用于设备快速定位
  Future<ApiOTAGpsInfo?> onGetGps() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.ApiEpoManagerDelegate.onGetGps', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as ApiOTAGpsInfo?);
    }
  }
}

abstract class ApiEPOManager {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 启用自动epo升级，默认为 关
  ///
  /// ```dart
  /// 触发条件：
  /// 1、每次快速配置完成后倒计时1分钟；
  /// 2、数据同步完成后立即执行；
  /// ```
  bool enableAutoUpgrade();

  /// 启用自动epo升级，默认为 关
  ///
  /// ```dart
  /// 触发条件：
  /// 1、每次快速配置完成后倒计时1分钟；
  /// 2、数据同步完成后立即执行；
  /// ```
  void setEnableAutoUpgrade(bool value);

  /// 获取最后一次更新的时间戳，单位：秒
  ///
  /// 无记录则返回0
  Future<int> lastUpdateTimestamp();

  /// 是否需要更新
  Future<bool> shouldUpdateForEPO(bool isForce);

  /// 启动升级任务
  ///
  /// ```dart
  /// isForce 是否强制更新
  /// retryCount 重试次数，默认0次
  /// ```
  void willStartInstall(bool isForce, int retryCount);

  /// 停止升级任务
  ///
  /// 注：只支持下载中和发送中的任务，不支持正在升级的任务
  void stop();

  static void setup(ApiEPOManager? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.enableAutoUpgrade', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = api.enableAutoUpgrade();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.setEnableAutoUpgrade', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.setEnableAutoUpgrade was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_value = (args[0] as bool?);
          assert(arg_value != null,
              'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.setEnableAutoUpgrade was null, expected non-null bool.');
          api.setEnableAutoUpgrade(arg_value!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.lastUpdateTimestamp', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final int output = await api.lastUpdateTimestamp();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.shouldUpdateForEPO', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.shouldUpdateForEPO was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_isForce = (args[0] as bool?);
          assert(arg_isForce != null,
              'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.shouldUpdateForEPO was null, expected non-null bool.');
          final bool output = await api.shouldUpdateForEPO(arg_isForce!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.willStartInstall', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.willStartInstall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_isForce = (args[0] as bool?);
          assert(arg_isForce != null,
              'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.willStartInstall was null, expected non-null bool.');
          final int? arg_retryCount = (args[1] as int?);
          assert(arg_retryCount != null,
              'Argument for dev.flutter.pigeon.protocol_channel.ApiEPOManager.willStartInstall was null, expected non-null int.');
          api.willStartInstall(arg_isForce!, arg_retryCount!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.ApiEPOManager.stop', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.stop();
          return;
        });
      }
    }
  }
}
