// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// 传输文件类型
enum ApiTransType {
  /// 固件升级
  fw,
  /// 图片资源升级
  fzbin,
  /// 字库升级
  bin,
  /// 语言包升级
  lang,
  /// BT升级
  bt,
  /// 表盘
  iwf_lz,
  /// 表盘 思澈
  watch,
  /// 壁纸表盘
  wallpaper_z,
  /// 通讯录文件
  ml,
  /// agps 在线
  online_ubx,
  /// agps 线下
  offline_ubx,
  /// 音乐（使用 MusicFileModel）
  mp3,
  /// 消息图标 （使用 MessageFileModel）
  msg,
  /// 运动图标 - 单个（使用SportFileModel）
  sport,
  /// 运动图标 - 动画（使用SportFileModel）
  sports,
  /// epo升级
  epo,
  /// gps
  gps,
  bpbin,
  /// alexa 语音
  voice,
  /// 提示音
  ton,
  /// 小程序
  app,
  /// 其它类型：不限后缀，不对文件二次加工，直接上传到设备
  /// ```
  /// hid: 检测引导程序hid更新(android专用)
  /// xx: xxxxx
  /// ```
  other,
}

enum ApiTransStatus {
  none,
  /// 无效类型
  invalid,
  /// 文件不存在
  notExists,
  /// 存在传输任务
  busy,
  /// 配置
  config,
  /// 传输前操作
  beforeOpt,
  /// 传输中
  trans,
  /// 传输完成
  finished,
  /// 快速配置中，不支持文件传输
  onFastSynchronizing,
  /// 传输失败
  error,
}

class BaseFile {
  BaseFile({
    this.fileType,
    this.filePath,
    this.fileName,
    this.fileSize,
    this.originalFileSize,
    this.evtType,
    this.packName,
    this.musicId,
    this.singerName,
    this.useSpp,
    this.sportType,
    this.iconType,
    this.isSports,
  });

  /// 文件类型
  ApiTransType? fileType;

  /// 文件绝对地址
  String? filePath;

  /// 文件名
  String? fileName;

  /// 文件大小
  int? fileSize;

  /// 原始文件大小（压缩前）,暂时只用于表盘
  int? originalFileSize;

  /// 事件类型
  /// 参考 通消息通知
  /// ```dart
  /// 0x01：短信
  /// 0x02：邮件
  /// 0x03：微信
  /// 0x04：QQ
  /// 0x05：新浪微博
  /// 0x06：facebook
  /// 0x07：twitter
  /// 0x08：WhatsApp
  /// 0x09：Messenger
  /// 0x0A：Instagram
  /// 0x0B：Linked in
  /// 0x0C：日历
  /// 0x0D：skype；
  /// 0x0E：闹钟
  /// 0x0F：pokeman
  /// 0x10：VKontakte
  /// 0x11：Line
  /// 0x12：Viber
  /// 0x13：KakaoTalk
  /// 0x14：Gmail
  /// 0x15：Outlook,
  /// 0x16：Snapchat
  /// 0x17：TELEGRAM
  /// 0x18：other
  /// 0x20：chatwork
  /// 0x21：slack
  /// 0x22：Yahoo Mail
  /// 0x23：Tumblr,
  /// 0x24：Youtube
  /// 0x25：Yahoo Pinterest
  /// 0x26：TikTok
  /// 0x27：Redbus
  /// 0x28：Dailyhunt
  /// 0x29：Hotstar
  /// 0x2A：Inshorts
  /// 0x2B：Paytm
  /// 0x2C：Amazon
  /// 0x2D：Flipkart
  /// 0x2E：Prime
  /// 0x2F：Netflix
  /// 0x30：Gpay
  /// 0x31：Phonpe
  /// 0x32：Swiggy
  /// 0x33：Zomato
  /// 0x34：Make My trip
  /// 0x35：Jio Tv
  /// 0x36：keep
  /// 0x37：Microsoft
  /// 0x38：WhatsApp Business
  /// 0x39：niosefit
  /// 0x3A：missed_calls未接来电
  /// 0x3B：Gpap
  /// 0x3C：YTmusic
  /// 0x3D：Uber
  /// 0x3E：Ola
  /// 0x3F：事项提醒
  /// 0x40：Google meet
  /// ```
  int? evtType;

  /// 应用包名
  String? packName;

  /// 音乐id
  int? musicId;

  /// 歌手名
  String? singerName;

  /// 使用SPP传输
  bool? useSpp;

  /// 运动模式
  int? sportType;

  /// 图标类型 1:单张小运动图片 2:单张大运动图片 3:多运动动画图片 4:单张中运动图片 5:运动最小图标
  int? iconType;

  /// 运动图标 - 动画
  bool? isSports;

  Object encode() {
    return <Object?>[
      fileType?.index,
      filePath,
      fileName,
      fileSize,
      originalFileSize,
      evtType,
      packName,
      musicId,
      singerName,
      useSpp,
      sportType,
      iconType,
      isSports,
    ];
  }

  static BaseFile decode(Object result) {
    result as List<Object?>;
    return BaseFile(
      fileType: result[0] != null
          ? ApiTransType.values[result[0]! as int]
          : null,
      filePath: result[1] as String?,
      fileName: result[2] as String?,
      fileSize: result[3] as int?,
      originalFileSize: result[4] as int?,
      evtType: result[5] as int?,
      packName: result[6] as String?,
      musicId: result[7] as int?,
      singerName: result[8] as String?,
      useSpp: result[9] as bool?,
      sportType: result[10] as int?,
      iconType: result[11] as int?,
      isSports: result[12] as bool?,
    );
  }
}

class CancelTransferToken {
  CancelTransferToken({
    this.token,
  });

  String? token;

  Object encode() {
    return <Object?>[
      token,
    ];
  }

  static CancelTransferToken decode(Object result) {
    result as List<Object?>;
    return CancelTransferToken(
      token: result[0] as String?,
    );
  }
}

class ApiDeviceTransItem {
  ApiDeviceTransItem({
    this.fileType,
    this.fileSize,
    this.fileCompressionType,
    this.fileName,
    this.filePath,
  });

  /// 文件类型
  /// ```dart
  /// 0x13 语音备忘录文件 .voice
  /// 0x15 acc算法日志文件 .accdata
  /// 0x16 gps算法日志文件 .gpslog
  /// ```
  int? fileType;

  /// 文件大小 单位 字节
  int? fileSize;

  int? fileCompressionType;

  /// 文件名称
  String? fileName;

  /// 接收成功后的文件路径
  String? filePath;

  Object encode() {
    return <Object?>[
      fileType,
      fileSize,
      fileCompressionType,
      fileName,
      filePath,
    ];
  }

  static ApiDeviceTransItem decode(Object result) {
    result as List<Object?>;
    return ApiDeviceTransItem(
      fileType: result[0] as int?,
      fileSize: result[1] as int?,
      fileCompressionType: result[2] as int?,
      fileName: result[3] as String?,
      filePath: result[4] as String?,
    );
  }
}

class _FileTransferDelegateCodec extends StandardMessageCodec {
  const _FileTransferDelegateCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ApiDeviceTransItem) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ApiDeviceTransItem.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FileTransferDelegate {
  /// Constructor for [FileTransferDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FileTransferDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FileTransferDelegateCodec();

  /// 监听当前上传的文件类型
  Future<void> listenTransFileTypeChanged(ApiTransType? arg_fileType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.listenTransFileTypeChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_fileType?.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 多文件传输类型
  Future<void> fileTransStatusMultiple(int arg_index, ApiTransStatus arg_status) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.fileTransStatusMultiple', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_index, arg_status.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 多文件传输进度
  Future<void> fileTransProgressMultiple(int arg_currentIndex, int arg_totalCount, double arg_currentProgress, double arg_totalProgress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.fileTransProgressMultiple', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_currentIndex, arg_totalCount, arg_currentProgress, arg_totalProgress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 文件传输错误码
  Future<void> fileTransErrorCode(int arg_index, int arg_errorCode, int arg_errorCodeFromDevice, int arg_finishingTime) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.fileTransErrorCode', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_index, arg_errorCode, arg_errorCodeFromDevice, arg_finishingTime]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设备文件->app传输进度
  Future<void> deviceToAppTransItem(ApiDeviceTransItem arg_deviceTransItem) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.deviceToAppTransItem', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_deviceTransItem]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设备文件->app传输进度
  Future<void> deviceToAppTransProgress(double arg_progress) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.deviceToAppTransProgress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_progress]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设备文件->app传输结果
  ///
  /// isCompleted 传输结果，receiveFilePath 接收后的文件（isCompleted为true时有效）
  Future<void> deviceToAppTransStatus(bool arg_isCompleted, String? arg_receiveFilePath) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FileTransferDelegate.deviceToAppTransStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_isCompleted, arg_receiveFilePath]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _FileTransferCodec extends StandardMessageCodec {
  const _FileTransferCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BaseFile) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is CancelTransferToken) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CancelTransferToken) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BaseFile.decode(readValue(buffer)!);
      case 129: 
        return CancelTransferToken.decode(readValue(buffer)!);
      case 130: 
        return CancelTransferToken.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FileTransfer {
  static const MessageCodec<Object?> codec = _FileTransferCodec();

  /// 是否在执行传输
  bool isTransmitting();

  /// 当前传输中的文件类型
  ApiTransType? transFileType();

  /// 执行文件传输（批量）
  Future<List<bool?>> transferMultiple(List<BaseFile?> fileItems, bool cancelPrevTranTask, CancelTransferToken? cancelToken);

  void cancelTransfer(CancelTransferToken cancelToken);

  /// 获取压缩前.iwf文件大小
  Future<int> iwfFileSize(String filePath, int type);

  /// 注册 设备文件->app传输 (仅最后一次注册有效）
  ///
  /// ```dart
  /// taskFunc 接收到的文件任务
  /// ```
  void registerDeviceTranFileToApp();

  /// 取消设备文件->app传输 注册
  void unregisterDeviceTranFileToApp();

  /// 允许接收文件
  Future<bool> acceptReceiveFile();

  /// 拒绝接收文件
  Future<bool> rejectReceiveFile();

  /// APP主动停止设备传输文件到APP
  Future<bool> stopReceiveFile();

  static void setup(FileTransfer? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.isTransmitting', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = api.isTransmitting();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.transFileType', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final ApiTransType? output = api.transFileType();
          return output?.index;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.transferMultiple', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.transferMultiple was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<BaseFile?>? arg_fileItems = (args[0] as List<Object?>?)?.cast<BaseFile?>();
          assert(arg_fileItems != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.transferMultiple was null, expected non-null List<BaseFile?>.');
          final bool? arg_cancelPrevTranTask = (args[1] as bool?);
          assert(arg_cancelPrevTranTask != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.transferMultiple was null, expected non-null bool.');
          final CancelTransferToken? arg_cancelToken = (args[2] as CancelTransferToken?);
          final List<bool?> output = await api.transferMultiple(arg_fileItems!, arg_cancelPrevTranTask!, arg_cancelToken);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.cancelTransfer', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.cancelTransfer was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CancelTransferToken? arg_cancelToken = (args[0] as CancelTransferToken?);
          assert(arg_cancelToken != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.cancelTransfer was null, expected non-null CancelTransferToken.');
          api.cancelTransfer(arg_cancelToken!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.iwfFileSize', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.iwfFileSize was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_filePath = (args[0] as String?);
          assert(arg_filePath != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.iwfFileSize was null, expected non-null String.');
          final int? arg_type = (args[1] as int?);
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FileTransfer.iwfFileSize was null, expected non-null int.');
          final int output = await api.iwfFileSize(arg_filePath!, arg_type!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.registerDeviceTranFileToApp', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.registerDeviceTranFileToApp();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.unregisterDeviceTranFileToApp', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.unregisterDeviceTranFileToApp();
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.acceptReceiveFile', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = await api.acceptReceiveFile();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.rejectReceiveFile', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = await api.rejectReceiveFile();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FileTransfer.stopReceiveFile', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final bool output = await api.stopReceiveFile();
          return output;
        });
      }
    }
  }
}
