// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class FuncTableDelegate {
  /// Constructor for [FuncTableDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FuncTableDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 功能表变更通知
  Future<void> listenFuncTableChanged(String arg_funcTableJson) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableChanged', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_funcTableJson]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// 绑定时获取的功能表通知(绑定专用)
  Future<void> listenFuncTableOnBind(String arg_funcTableJson) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.FuncTableDelegate.listenFuncTableOnBind', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_funcTableJson]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class FuncTable {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// 加载指定设备功能表 返回json
  Future<String> loadFuncTableByDisk(String macAddress);

  /// 导出功能表 返回json文件绝对路径
  Future<String> exportFuncTableFile(String macAddress);

  static void setup(FuncTable? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FuncTable.loadFuncTableByDisk', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.FuncTable.loadFuncTableByDisk was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddress = (args[0] as String?);
          assert(arg_macAddress != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FuncTable.loadFuncTableByDisk was null, expected non-null String.');
          final String output = await api.loadFuncTableByDisk(arg_macAddress!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.FuncTable.exportFuncTableFile', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.FuncTable.exportFuncTableFile was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddress = (args[0] as String?);
          assert(arg_macAddress != null,
              'Argument for dev.flutter.pigeon.protocol_channel.FuncTable.exportFuncTableFile was null, expected non-null String.');
          final String output = await api.exportFuncTableFile(arg_macAddress!);
          return output;
        });
      }
    }
  }
}
