// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// 测量类型
enum MeasureType {
  /// 血压
  bloodPressure,
  /// 心率
  heartRate,
  /// 血氧
  spo2,
  /// 压力
  stress,
  /// 一键测量
  oneClick,
  /// 体温
  temperature,
  /// 身体成分
  bodyComposition,
}

/// 测量状态
enum MeasureStatus {
  /// 不支持
  notSupport,
  /// 正在测量
  measuring,
  /// 测量成功
  success,
  /// 测量失败
  failed,
  /// 设备正在运动模式
  deviceInSportMode,
  /// 返回测量中数据
  measuringData,
  /// 超时 (APP)
  timeout,
  /// 停止 (APP)
  stopped,
  /// 断连 (APP)
  disconnected,
  /// 未佩戴 (设备通知 72)
  unworn,
}

/// 测量结果模型
class MeasureResult {
  MeasureResult({
    this.status,
    this.systolicBp,
    this.diastolicBp,
    this.value,
    this.oneClickHr,
    this.oneClickStress,
    this.oneClickSpo2,
    this.temperatureValue,
  });

  /// 状态
  MeasureStatus? status;

  /// 收缩压 (高压)
  int? systolicBp;

  /// 舒张压 (低压)
  int? diastolicBp;

  /// 值 (心率/血氧/压力)
  int? value;

  /// 一键测量-心率
  int? oneClickHr;

  /// 一键测量-压力
  int? oneClickStress;

  /// 一键测量-血氧
  int? oneClickSpo2;

  /// 体温值 (单位摄氏度,该值扩大了10倍, 如 366 表示 36.6度)
  int? temperatureValue;

  Object encode() {
    return <Object?>[
      status?.index,
      systolicBp,
      diastolicBp,
      value,
      oneClickHr,
      oneClickStress,
      oneClickSpo2,
      temperatureValue,
    ];
  }

  static MeasureResult decode(Object result) {
    result as List<Object?>;
    return MeasureResult(
      status: result[0] != null
          ? MeasureStatus.values[result[0]! as int]
          : null,
      systolicBp: result[1] as int?,
      diastolicBp: result[2] as int?,
      value: result[3] as int?,
      oneClickHr: result[4] as int?,
      oneClickStress: result[5] as int?,
      oneClickSpo2: result[6] as int?,
      temperatureValue: result[7] as int?,
    );
  }
}

class _MeasureDelegateCodec extends StandardMessageCodec {
  const _MeasureDelegateCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MeasureResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MeasureResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MeasureDelegate {
  /// Constructor for [MeasureDelegate].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MeasureDelegate({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _MeasureDelegateCodec();

  /// 测量结果监听
  Future<void> listenMeasureResult(MeasureResult arg_result) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.protocol_channel.MeasureDelegate.listenMeasureResult', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_result]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _MeasureCodec extends StandardMessageCodec {
  const _MeasureCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MeasureResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MeasureResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class Measure {
  static const MessageCodec<Object?> codec = _MeasureCodec();

  /// 开始测量
  Future<bool> startMeasure(MeasureType type);

  /// 停止测量
  Future<bool> stopMeasure(MeasureType type);

  /// 获取当前测量数据
  Future<MeasureResult> getMeasureData(MeasureType type);

  static void setup(Measure? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Measure.startMeasure', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Measure.startMeasure was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MeasureType? arg_type = args[0] == null ? null : MeasureType.values[args[0]! as int];
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Measure.startMeasure was null, expected non-null MeasureType.');
          final bool output = await api.startMeasure(arg_type!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Measure.stopMeasure', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Measure.stopMeasure was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MeasureType? arg_type = args[0] == null ? null : MeasureType.values[args[0]! as int];
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Measure.stopMeasure was null, expected non-null MeasureType.');
          final bool output = await api.stopMeasure(arg_type!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.protocol_channel.Measure.getMeasureData', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.protocol_channel.Measure.getMeasureData was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MeasureType? arg_type = args[0] == null ? null : MeasureType.values[args[0]! as int];
          assert(arg_type != null,
              'Argument for dev.flutter.pigeon.protocol_channel.Measure.getMeasureData was null, expected non-null MeasureType.');
          final MeasureResult output = await api.getMeasureData(arg_type!);
          return output;
        });
      }
    }
  }
}
