name: protocol_channel
description: ido protocol_channel lib (private)
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.5.0'
  flutter: '>=3.24.3'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protocol_lib:
    path: ../protocol_lib/
  protocol_alexa:
    path: ../protocol_alexa/
  flutter_bluetooth:
    path: ../../bluetooth_sdk/
  ido_logger:
    path: ../plugins/ido_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^11.0.1
  build_runner: ^2.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.idosmart.protocol_channel
        pluginClass: ProtocolChannelPlugin
      ios:
        pluginClass: ProtocolChannelPlugin
